// ─── Cipher Challenge Puzzle Bank — 250 puzzles ─────────────────────────────
// lib/puzzles-challenge.ts

export interface ChallengePuzzle {
  id: string; cipher: string; difficulty: "Easy" | "Medium" | "Hard"
  plaintext: string; ciphertext: string; keyInfo: string
  hint1: string; hint2: string; hint3: string
}

export const CHALLENGE_PUZZLES: ChallengePuzzle[] = [
  { id:"c1", cipher:"Caesar", difficulty:"Easy",
    plaintext:"HELLO WORLD", ciphertext:"IFMMP XPSME", keyInfo:"Shift 1",
    hint1:"This is a Caesar cipher — each letter is shifted by the same amount.", hint2:"The shift value is 1. Count 1 letters forward in the alphabet.", hint3:"Key: Shift 1. A→B, B→C" },
  { id:"c2", cipher:"Caesar", difficulty:"Easy",
    plaintext:"ATTACK NOW", ciphertext:"CVVCEM PQY", keyInfo:"Shift 2",
    hint1:"This is a Caesar cipher — each letter is shifted by the same amount.", hint2:"The shift value is 2. Count 2 letters forward in the alphabet.", hint3:"Key: Shift 2. A→C, B→D" },
  { id:"c3", cipher:"Caesar", difficulty:"Easy",
    plaintext:"SEND BACKUP", ciphertext:"VHQG EDFNXS", keyInfo:"Shift 3",
    hint1:"This is a Caesar cipher — each letter is shifted by the same amount.", hint2:"The shift value is 3. Count 3 letters forward in the alphabet.", hint3:"Key: Shift 3. A→D, B→E" },
  { id:"c4", cipher:"Caesar", difficulty:"Easy",
    plaintext:"HOLD THE LINE", ciphertext:"LSPH XLI PMRI", keyInfo:"Shift 4",
    hint1:"This is a Caesar cipher — each letter is shifted by the same amount.", hint2:"The shift value is 4. Count 4 letters forward in the alphabet.", hint3:"Key: Shift 4. A→E, B→F" },
  { id:"c5", cipher:"Caesar", difficulty:"Easy",
    plaintext:"BREAK FREE", ciphertext:"GWJFP KWJJ", keyInfo:"Shift 5",
    hint1:"This is a Caesar cipher — each letter is shifted by the same amount.", hint2:"The shift value is 5. Count 5 letters forward in the alphabet.", hint3:"Key: Shift 5. A→F, B→G" },
  { id:"c6", cipher:"Caesar", difficulty:"Easy",
    plaintext:"FIRE AT WILL", ciphertext:"LOXK GZ CORR", keyInfo:"Shift 6",
    hint1:"This is a Caesar cipher — each letter is shifted by the same amount.", hint2:"The shift value is 6. Count 6 letters forward in the alphabet.", hint3:"Key: Shift 6. A→G, B→H" },
  { id:"c7", cipher:"Caesar", difficulty:"Easy",
    plaintext:"OPEN THE GATE", ciphertext:"VWLU AOL NHAL", keyInfo:"Shift 7",
    hint1:"This is a Caesar cipher — each letter is shifted by the same amount.", hint2:"The shift value is 7. Count 7 letters forward in the alphabet.", hint3:"Key: Shift 7. A→H, B→I" },
  { id:"c8", cipher:"Caesar", difficulty:"Easy",
    plaintext:"FIND THE KEY", ciphertext:"NQVL BPM SMG", keyInfo:"Shift 8",
    hint1:"This is a Caesar cipher — each letter is shifted by the same amount.", hint2:"The shift value is 8. Count 8 letters forward in the alphabet.", hint3:"Key: Shift 8. A→I, B→J" },
  { id:"c9", cipher:"Caesar", difficulty:"Easy",
    plaintext:"DECODE THIS", ciphertext:"MNLXMN CQRB", keyInfo:"Shift 9",
    hint1:"This is a Caesar cipher — each letter is shifted by the same amount.", hint2:"The shift value is 9. Count 9 letters forward in the alphabet.", hint3:"Key: Shift 9. A→J, B→K" },
  { id:"c10", cipher:"Caesar", difficulty:"Easy",
    plaintext:"SECRET CODE", ciphertext:"COMBOD MYNO", keyInfo:"Shift 10",
    hint1:"This is a Caesar cipher — each letter is shifted by the same amount.", hint2:"The shift value is 10. Count 10 letters forward in the alphabet.", hint3:"Key: Shift 10. A→K, B→L" },
  { id:"c11", cipher:"Caesar", difficulty:"Easy",
    plaintext:"MOVE OUT NOW", ciphertext:"XZGP ZFE YZH", keyInfo:"Shift 11",
    hint1:"This is a Caesar cipher — each letter is shifted by the same amount.", hint2:"The shift value is 11. Count 11 letters forward in the alphabet.", hint3:"Key: Shift 11. A→L, B→M" },
  { id:"c12", cipher:"Caesar", difficulty:"Easy",
    plaintext:"RALLY HERE", ciphertext:"DMXXK TQDQ", keyInfo:"Shift 12",
    hint1:"This is a Caesar cipher — each letter is shifted by the same amount.", hint2:"The shift value is 12. Count 12 letters forward in the alphabet.", hint3:"Key: Shift 12. A→M, B→N" },
  { id:"c13", cipher:"Caesar", difficulty:"Easy",
    plaintext:"STORM THE BASE", ciphertext:"FGBEZ GUR ONFR", keyInfo:"Shift 13",
    hint1:"This is a Caesar cipher — each letter is shifted by the same amount.", hint2:"The shift value is 13. Count 13 letters forward in the alphabet.", hint3:"Key: Shift 13. A→N, B→O" },
  { id:"c14", cipher:"Caesar", difficulty:"Easy",
    plaintext:"ENTER THE VAULT", ciphertext:"SBHSF HVS JOIZH", keyInfo:"Shift 14",
    hint1:"This is a Caesar cipher — each letter is shifted by the same amount.", hint2:"The shift value is 14. Count 14 letters forward in the alphabet.", hint3:"Key: Shift 14. A→O, B→P" },
  { id:"c15", cipher:"Caesar", difficulty:"Easy",
    plaintext:"TIME IS UP", ciphertext:"IXBT XH JE", keyInfo:"Shift 15",
    hint1:"This is a Caesar cipher — each letter is shifted by the same amount.", hint2:"The shift value is 15. Count 15 letters forward in the alphabet.", hint3:"Key: Shift 15. A→P, B→Q" },
  { id:"c16", cipher:"Caesar", difficulty:"Easy",
    plaintext:"SIGNAL CLEAR", ciphertext:"IYWDQB SBUQH", keyInfo:"Shift 16",
    hint1:"This is a Caesar cipher — each letter is shifted by the same amount.", hint2:"The shift value is 16. Count 16 letters forward in the alphabet.", hint3:"Key: Shift 16. A→Q, B→R" },
  { id:"c17", cipher:"Caesar", difficulty:"Easy",
    plaintext:"ABORT MISSION", ciphertext:"RSFIK DZJJZFE", keyInfo:"Shift 17",
    hint1:"This is a Caesar cipher — each letter is shifted by the same amount.", hint2:"The shift value is 17. Count 17 letters forward in the alphabet.", hint3:"Key: Shift 17. A→R, B→S" },
  { id:"c18", cipher:"Caesar", difficulty:"Easy",
    plaintext:"MARK THE TARGET", ciphertext:"ESJC LZW LSJYWL", keyInfo:"Shift 18",
    hint1:"This is a Caesar cipher — each letter is shifted by the same amount.", hint2:"The shift value is 18. Count 18 letters forward in the alphabet.", hint3:"Key: Shift 18. A→S, B→T" },
  { id:"c19", cipher:"Caesar", difficulty:"Easy",
    plaintext:"RETURN TO BASE", ciphertext:"KXMNKG MH UTLX", keyInfo:"Shift 19",
    hint1:"This is a Caesar cipher — each letter is shifted by the same amount.", hint2:"The shift value is 19. Count 19 letters forward in the alphabet.", hint3:"Key: Shift 19. A→T, B→U" },
  { id:"c20", cipher:"Caesar", difficulty:"Easy",
    plaintext:"GO DARK NOW", ciphertext:"AI XULE HIQ", keyInfo:"Shift 20",
    hint1:"This is a Caesar cipher — each letter is shifted by the same amount.", hint2:"The shift value is 20. Count 20 letters forward in the alphabet.", hint3:"Key: Shift 20. A→U, B→V" },
  { id:"c21", cipher:"Caesar", difficulty:"Easy",
    plaintext:"THE CODE FALLS", ciphertext:"OCZ XJYZ AVGGN", keyInfo:"Shift 21",
    hint1:"This is a Caesar cipher — each letter is shifted by the same amount.", hint2:"The shift value is 21. Count 21 letters forward in the alphabet.", hint3:"Key: Shift 21. A→V, B→W" },
  { id:"c22", cipher:"Caesar", difficulty:"Easy",
    plaintext:"CIPHER BROKEN", ciphertext:"YELDAN XNKGAJ", keyInfo:"Shift 22",
    hint1:"This is a Caesar cipher — each letter is shifted by the same amount.", hint2:"The shift value is 22. Count 22 letters forward in the alphabet.", hint3:"Key: Shift 22. A→W, B→X" },
  { id:"c23", cipher:"Caesar", difficulty:"Easy",
    plaintext:"KEY REVEALED", ciphertext:"HBV OBSBXIBA", keyInfo:"Shift 23",
    hint1:"This is a Caesar cipher — each letter is shifted by the same amount.", hint2:"The shift value is 23. Count 23 letters forward in the alphabet.", hint3:"Key: Shift 23. A→X, B→Y" },
  { id:"c24", cipher:"Caesar", difficulty:"Easy",
    plaintext:"LOCK AND LOAD", ciphertext:"JMAI YLB JMYB", keyInfo:"Shift 24",
    hint1:"This is a Caesar cipher — each letter is shifted by the same amount.", hint2:"The shift value is 24. Count 24 letters forward in the alphabet.", hint3:"Key: Shift 24. A→Y, B→Z" },
  { id:"c25", cipher:"Caesar", difficulty:"Easy",
    plaintext:"EYES OPEN", ciphertext:"DXDR NODM", keyInfo:"Shift 25",
    hint1:"This is a Caesar cipher — each letter is shifted by the same amount.", hint2:"The shift value is 25. Count 25 letters forward in the alphabet.", hint3:"Key: Shift 25. A→Z, B→A" },
  { id:"c26", cipher:"Caesar", difficulty:"Easy",
    plaintext:"STAND DOWN NOW", ciphertext:"TUBOE EPXO OPX", keyInfo:"Shift 1",
    hint1:"This is a Caesar cipher — each letter is shifted by the same amount.", hint2:"The shift value is 1. Count 1 letters forward in the alphabet.", hint3:"Key: Shift 1. A→B, B→C" },
  { id:"c27", cipher:"Caesar", difficulty:"Easy",
    plaintext:"ADVANCE QUICKLY", ciphertext:"CFXCPEG SWKEMNA", keyInfo:"Shift 2",
    hint1:"This is a Caesar cipher — each letter is shifted by the same amount.", hint2:"The shift value is 2. Count 2 letters forward in the alphabet.", hint3:"Key: Shift 2. A→C, B→D" },
  { id:"c28", cipher:"Caesar", difficulty:"Easy",
    plaintext:"COVER ME NOW", ciphertext:"FRYHU PH QRZ", keyInfo:"Shift 3",
    hint1:"This is a Caesar cipher — each letter is shifted by the same amount.", hint2:"The shift value is 3. Count 3 letters forward in the alphabet.", hint3:"Key: Shift 3. A→D, B→E" },
  { id:"c29", cipher:"Caesar", difficulty:"Easy",
    plaintext:"SILENT APPROACH", ciphertext:"WMPIRX ETTVSEGL", keyInfo:"Shift 4",
    hint1:"This is a Caesar cipher — each letter is shifted by the same amount.", hint2:"The shift value is 4. Count 4 letters forward in the alphabet.", hint3:"Key: Shift 4. A→E, B→F" },
  { id:"c30", cipher:"Caesar", difficulty:"Easy",
    plaintext:"BREACH NOW", ciphertext:"GWJFHM STB", keyInfo:"Shift 5",
    hint1:"This is a Caesar cipher — each letter is shifted by the same amount.", hint2:"The shift value is 5. Count 5 letters forward in the alphabet.", hint3:"Key: Shift 5. A→F, B→G" },
  { id:"c31", cipher:"Caesar", difficulty:"Easy",
    plaintext:"FLANK THEM NOW", ciphertext:"LRGTQ ZNKS TUC", keyInfo:"Shift 6",
    hint1:"This is a Caesar cipher — each letter is shifted by the same amount.", hint2:"The shift value is 6. Count 6 letters forward in the alphabet.", hint3:"Key: Shift 6. A→G, B→H" },
  { id:"c32", cipher:"Caesar", difficulty:"Easy",
    plaintext:"HOLD YOUR FIRE", ciphertext:"OVSK FVBY MPYL", keyInfo:"Shift 7",
    hint1:"This is a Caesar cipher — each letter is shifted by the same amount.", hint2:"The shift value is 7. Count 7 letters forward in the alphabet.", hint3:"Key: Shift 7. A→H, B→I" },
  { id:"c33", cipher:"Caesar", difficulty:"Easy",
    plaintext:"SECURE THE ZONE", ciphertext:"AMKCZM BPM HWVM", keyInfo:"Shift 8",
    hint1:"This is a Caesar cipher — each letter is shifted by the same amount.", hint2:"The shift value is 8. Count 8 letters forward in the alphabet.", hint3:"Key: Shift 8. A→I, B→J" },
  { id:"c34", cipher:"Caesar", difficulty:"Easy",
    plaintext:"EXTRACT ASSET", ciphertext:"NGCAJLC JBBNC", keyInfo:"Shift 9",
    hint1:"This is a Caesar cipher — each letter is shifted by the same amount.", hint2:"The shift value is 9. Count 9 letters forward in the alphabet.", hint3:"Key: Shift 9. A→J, B→K" },
  { id:"c35", cipher:"Caesar", difficulty:"Easy",
    plaintext:"MOVE FAST", ciphertext:"WYFO PKCD", keyInfo:"Shift 10",
    hint1:"This is a Caesar cipher — each letter is shifted by the same amount.", hint2:"The shift value is 10. Count 10 letters forward in the alphabet.", hint3:"Key: Shift 10. A→K, B→L" },
  { id:"c36", cipher:"Caesar", difficulty:"Easy",
    plaintext:"NIGHT VISION ON", ciphertext:"YTRSE GTDTZY ZY", keyInfo:"Shift 11",
    hint1:"This is a Caesar cipher — each letter is shifted by the same amount.", hint2:"The shift value is 11. Count 11 letters forward in the alphabet.", hint3:"Key: Shift 11. A→L, B→M" },
  { id:"c37", cipher:"Caesar", difficulty:"Easy",
    plaintext:"RADIO SILENCE", ciphertext:"DMPUA EUXQZOQ", keyInfo:"Shift 12",
    hint1:"This is a Caesar cipher — each letter is shifted by the same amount.", hint2:"The shift value is 12. Count 12 letters forward in the alphabet.", hint3:"Key: Shift 12. A→M, B→N" },
  { id:"c38", cipher:"Caesar", difficulty:"Easy",
    plaintext:"WATCH YOUR SIX", ciphertext:"JNGPU LBHE FVK", keyInfo:"Shift 13",
    hint1:"This is a Caesar cipher — each letter is shifted by the same amount.", hint2:"The shift value is 13. Count 13 letters forward in the alphabet.", hint3:"Key: Shift 13. A→N, B→O" },
  { id:"c39", cipher:"Caesar", difficulty:"Easy",
    plaintext:"FRIENDLIES AHEAD", ciphertext:"TFWSBRZWSG OVSOR", keyInfo:"Shift 14",
    hint1:"This is a Caesar cipher — each letter is shifted by the same amount.", hint2:"The shift value is 14. Count 14 letters forward in the alphabet.", hint3:"Key: Shift 14. A→O, B→P" },
  { id:"c40", cipher:"Caesar", difficulty:"Easy",
    plaintext:"ENEMY SPOTTED", ciphertext:"TCTBN HEDIITS", keyInfo:"Shift 15",
    hint1:"This is a Caesar cipher — each letter is shifted by the same amount.", hint2:"The shift value is 15. Count 15 letters forward in the alphabet.", hint3:"Key: Shift 15. A→P, B→Q" },
  { id:"c41", cipher:"Caesar", difficulty:"Easy",
    plaintext:"PACKAGE SECURED", ciphertext:"FQSAQWU IUSKHUT", keyInfo:"Shift 16",
    hint1:"This is a Caesar cipher — each letter is shifted by the same amount.", hint2:"The shift value is 16. Count 16 letters forward in the alphabet.", hint3:"Key: Shift 16. A→Q, B→R" },
  { id:"c42", cipher:"Caesar", difficulty:"Easy",
    plaintext:"RENDEZVOUS SET", ciphertext:"IVEUVQMFLJ JVK", keyInfo:"Shift 17",
    hint1:"This is a Caesar cipher — each letter is shifted by the same amount.", hint2:"The shift value is 17. Count 17 letters forward in the alphabet.", hint3:"Key: Shift 17. A→R, B→S" },
  { id:"c43", cipher:"Caesar", difficulty:"Easy",
    plaintext:"INTEL CONFIRMED", ciphertext:"AFLWD UGFXAJEWV", keyInfo:"Shift 18",
    hint1:"This is a Caesar cipher — each letter is shifted by the same amount.", hint2:"The shift value is 18. Count 18 letters forward in the alphabet.", hint3:"Key: Shift 18. A→S, B→T" },
  { id:"c44", cipher:"Caesar", difficulty:"Easy",
    plaintext:"TARGET ACQUIRED", ciphertext:"MTKZXM TVJNBKXW", keyInfo:"Shift 19",
    hint1:"This is a Caesar cipher — each letter is shifted by the same amount.", hint2:"The shift value is 19. Count 19 letters forward in the alphabet.", hint3:"Key: Shift 19. A→T, B→U" },
  { id:"c45", cipher:"Caesar", difficulty:"Easy",
    plaintext:"MISSION GO", ciphertext:"GCMMCIH AI", keyInfo:"Shift 20",
    hint1:"This is a Caesar cipher — each letter is shifted by the same amount.", hint2:"The shift value is 20. Count 20 letters forward in the alphabet.", hint3:"Key: Shift 20. A→U, B→V" },
  { id:"c46", cipher:"Caesar", difficulty:"Easy",
    plaintext:"CODE RED NOW", ciphertext:"XJYZ MZY IJR", keyInfo:"Shift 21",
    hint1:"This is a Caesar cipher — each letter is shifted by the same amount.", hint2:"The shift value is 21. Count 21 letters forward in the alphabet.", hint3:"Key: Shift 21. A→V, B→W" },
  { id:"c47", cipher:"Caesar", difficulty:"Easy",
    plaintext:"FULL LOCKDOWN", ciphertext:"BQHH HKYGZKSJ", keyInfo:"Shift 22",
    hint1:"This is a Caesar cipher — each letter is shifted by the same amount.", hint2:"The shift value is 22. Count 22 letters forward in the alphabet.", hint3:"Key: Shift 22. A→W, B→X" },
  { id:"c48", cipher:"Caesar", difficulty:"Easy",
    plaintext:"INITIATE SEQUENCE", ciphertext:"FKFQFXQB PBNRBKZB", keyInfo:"Shift 23",
    hint1:"This is a Caesar cipher — each letter is shifted by the same amount.", hint2:"The shift value is 23. Count 23 letters forward in the alphabet.", hint3:"Key: Shift 23. A→X, B→Y" },
  { id:"c49", cipher:"Caesar", difficulty:"Easy",
    plaintext:"ENGAGE TARGETS", ciphertext:"CLEYEC RYPECRQ", keyInfo:"Shift 24",
    hint1:"This is a Caesar cipher — each letter is shifted by the same amount.", hint2:"The shift value is 24. Count 24 letters forward in the alphabet.", hint3:"Key: Shift 24. A→Y, B→Z" },
  { id:"c50", cipher:"Caesar", difficulty:"Easy",
    plaintext:"DISENGAGE NOW", ciphertext:"CHRDMFZFD MNV", keyInfo:"Shift 25",
    hint1:"This is a Caesar cipher — each letter is shifted by the same amount.", hint2:"The shift value is 25. Count 25 letters forward in the alphabet.", hint3:"Key: Shift 25. A→Z, B→A" },
  { id:"c51", cipher:"ROT13", difficulty:"Easy",
    plaintext:"HELLO", ciphertext:"URYYB", keyInfo:"ROT13",
    hint1:"ROT13: every letter is shifted by exactly 13 positions.", hint2:"ROT13 is its own inverse — apply it twice to get the original.", hint3:"A→N, B→O, C→P, ..., N→A, O→B ..." },
  { id:"c52", cipher:"ROT13", difficulty:"Easy",
    plaintext:"WORLD", ciphertext:"JBEYQ", keyInfo:"ROT13",
    hint1:"ROT13: every letter is shifted by exactly 13 positions.", hint2:"ROT13 is its own inverse — apply it twice to get the original.", hint3:"A→N, B→O, C→P, ..., N→A, O→B ..." },
  { id:"c53", cipher:"ROT13", difficulty:"Easy",
    plaintext:"CIPHER", ciphertext:"PVCURE", keyInfo:"ROT13",
    hint1:"ROT13: every letter is shifted by exactly 13 positions.", hint2:"ROT13 is its own inverse — apply it twice to get the original.", hint3:"A→N, B→O, C→P, ..., N→A, O→B ..." },
  { id:"c54", cipher:"ROT13", difficulty:"Easy",
    plaintext:"SECRET", ciphertext:"FRPERG", keyInfo:"ROT13",
    hint1:"ROT13: every letter is shifted by exactly 13 positions.", hint2:"ROT13 is its own inverse — apply it twice to get the original.", hint3:"A→N, B→O, C→P, ..., N→A, O→B ..." },
  { id:"c55", cipher:"ROT13", difficulty:"Easy",
    plaintext:"DECODE", ciphertext:"QRPBQR", keyInfo:"ROT13",
    hint1:"ROT13: every letter is shifted by exactly 13 positions.", hint2:"ROT13 is its own inverse — apply it twice to get the original.", hint3:"A→N, B→O, C→P, ..., N→A, O→B ..." },
  { id:"c56", cipher:"ROT13", difficulty:"Easy",
    plaintext:"ATTACK", ciphertext:"NGGNPX", keyInfo:"ROT13",
    hint1:"ROT13: every letter is shifted by exactly 13 positions.", hint2:"ROT13 is its own inverse — apply it twice to get the original.", hint3:"A→N, B→O, C→P, ..., N→A, O→B ..." },
  { id:"c57", cipher:"ROT13", difficulty:"Easy",
    plaintext:"DEFEND", ciphertext:"QRSRAQ", keyInfo:"ROT13",
    hint1:"ROT13: every letter is shifted by exactly 13 positions.", hint2:"ROT13 is its own inverse — apply it twice to get the original.", hint3:"A→N, B→O, C→P, ..., N→A, O→B ..." },
  { id:"c58", cipher:"ROT13", difficulty:"Easy",
    plaintext:"SIGNAL", ciphertext:"FVTANY", keyInfo:"ROT13",
    hint1:"ROT13: every letter is shifted by exactly 13 positions.", hint2:"ROT13 is its own inverse — apply it twice to get the original.", hint3:"A→N, B→O, C→P, ..., N→A, O→B ..." },
  { id:"c59", cipher:"ROT13", difficulty:"Easy",
    plaintext:"BEACON", ciphertext:"ORNPBA", keyInfo:"ROT13",
    hint1:"ROT13: every letter is shifted by exactly 13 positions.", hint2:"ROT13 is its own inverse — apply it twice to get the original.", hint3:"A→N, B→O, C→P, ..., N→A, O→B ..." },
  { id:"c60", cipher:"ROT13", difficulty:"Easy",
    plaintext:"SHADOW", ciphertext:"FUNQBJ", keyInfo:"ROT13",
    hint1:"ROT13: every letter is shifted by exactly 13 positions.", hint2:"ROT13 is its own inverse — apply it twice to get the original.", hint3:"A→N, B→O, C→P, ..., N→A, O→B ..." },
  { id:"c61", cipher:"ROT13", difficulty:"Easy",
    plaintext:"FALCON", ciphertext:"SNYPBA", keyInfo:"ROT13",
    hint1:"ROT13: every letter is shifted by exactly 13 positions.", hint2:"ROT13 is its own inverse — apply it twice to get the original.", hint3:"A→N, B→O, C→P, ..., N→A, O→B ..." },
  { id:"c62", cipher:"ROT13", difficulty:"Easy",
    plaintext:"VECTOR", ciphertext:"IRPGBE", keyInfo:"ROT13",
    hint1:"ROT13: every letter is shifted by exactly 13 positions.", hint2:"ROT13 is its own inverse — apply it twice to get the original.", hint3:"A→N, B→O, C→P, ..., N→A, O→B ..." },
  { id:"c63", cipher:"ROT13", difficulty:"Easy",
    plaintext:"MATRIX", ciphertext:"ZNGEVK", keyInfo:"ROT13",
    hint1:"ROT13: every letter is shifted by exactly 13 positions.", hint2:"ROT13 is its own inverse — apply it twice to get the original.", hint3:"A→N, B→O, C→P, ..., N→A, O→B ..." },
  { id:"c64", cipher:"ROT13", difficulty:"Easy",
    plaintext:"PYTHON", ciphertext:"CLGUBA", keyInfo:"ROT13",
    hint1:"ROT13: every letter is shifted by exactly 13 positions.", hint2:"ROT13 is its own inverse — apply it twice to get the original.", hint3:"A→N, B→O, C→P, ..., N→A, O→B ..." },
  { id:"c65", cipher:"ROT13", difficulty:"Easy",
    plaintext:"BINARY", ciphertext:"OVANEL", keyInfo:"ROT13",
    hint1:"ROT13: every letter is shifted by exactly 13 positions.", hint2:"ROT13 is its own inverse — apply it twice to get the original.", hint3:"A→N, B→O, C→P, ..., N→A, O→B ..." },
  { id:"c66", cipher:"ROT13", difficulty:"Easy",
    plaintext:"ROCKET", ciphertext:"EBPXRG", keyInfo:"ROT13",
    hint1:"ROT13: every letter is shifted by exactly 13 positions.", hint2:"ROT13 is its own inverse — apply it twice to get the original.", hint3:"A→N, B→O, C→P, ..., N→A, O→B ..." },
  { id:"c67", cipher:"ROT13", difficulty:"Easy",
    plaintext:"PLANET", ciphertext:"CYNARG", keyInfo:"ROT13",
    hint1:"ROT13: every letter is shifted by exactly 13 positions.", hint2:"ROT13 is its own inverse — apply it twice to get the original.", hint3:"A→N, B→O, C→P, ..., N→A, O→B ..." },
  { id:"c68", cipher:"ROT13", difficulty:"Easy",
    plaintext:"SYSTEM", ciphertext:"FLFGRZ", keyInfo:"ROT13",
    hint1:"ROT13: every letter is shifted by exactly 13 positions.", hint2:"ROT13 is its own inverse — apply it twice to get the original.", hint3:"A→N, B→O, C→P, ..., N→A, O→B ..." },
  { id:"c69", cipher:"ROT13", difficulty:"Easy",
    plaintext:"NETWORK", ciphertext:"ARGJBEX", keyInfo:"ROT13",
    hint1:"ROT13: every letter is shifted by exactly 13 positions.", hint2:"ROT13 is its own inverse — apply it twice to get the original.", hint3:"A→N, B→O, C→P, ..., N→A, O→B ..." },
  { id:"c70", cipher:"ROT13", difficulty:"Easy",
    plaintext:"KERNEL", ciphertext:"XREARY", keyInfo:"ROT13",
    hint1:"ROT13: every letter is shifted by exactly 13 positions.", hint2:"ROT13 is its own inverse — apply it twice to get the original.", hint3:"A→N, B→O, C→P, ..., N→A, O→B ..." },
  { id:"c71", cipher:"ROT13", difficulty:"Easy",
    plaintext:"SERVER", ciphertext:"FREIRE", keyInfo:"ROT13",
    hint1:"ROT13: every letter is shifted by exactly 13 positions.", hint2:"ROT13 is its own inverse — apply it twice to get the original.", hint3:"A→N, B→O, C→P, ..., N→A, O→B ..." },
  { id:"c72", cipher:"ROT13", difficulty:"Easy",
    plaintext:"CLIENT", ciphertext:"PYVRAG", keyInfo:"ROT13",
    hint1:"ROT13: every letter is shifted by exactly 13 positions.", hint2:"ROT13 is its own inverse — apply it twice to get the original.", hint3:"A→N, B→O, C→P, ..., N→A, O→B ..." },
  { id:"c73", cipher:"ROT13", difficulty:"Easy",
    plaintext:"BRIDGE", ciphertext:"OEVQTR", keyInfo:"ROT13",
    hint1:"ROT13: every letter is shifted by exactly 13 positions.", hint2:"ROT13 is its own inverse — apply it twice to get the original.", hint3:"A→N, B→O, C→P, ..., N→A, O→B ..." },
  { id:"c74", cipher:"ROT13", difficulty:"Easy",
    plaintext:"TUNNEL", ciphertext:"GHAARY", keyInfo:"ROT13",
    hint1:"ROT13: every letter is shifted by exactly 13 positions.", hint2:"ROT13 is its own inverse — apply it twice to get the original.", hint3:"A→N, B→O, C→P, ..., N→A, O→B ..." },
  { id:"c75", cipher:"ROT13", difficulty:"Easy",
    plaintext:"CIPHER TEXT", ciphertext:"PVCURE GRKG", keyInfo:"ROT13",
    hint1:"ROT13: every letter is shifted by exactly 13 positions.", hint2:"ROT13 is its own inverse — apply it twice to get the original.", hint3:"A→N, B→O, C→P, ..., N→A, O→B ..." },
  { id:"c76", cipher:"ROT13", difficulty:"Easy",
    plaintext:"SECRET CODE", ciphertext:"FRPERG PBQR", keyInfo:"ROT13",
    hint1:"ROT13: every letter is shifted by exactly 13 positions.", hint2:"ROT13 is its own inverse — apply it twice to get the original.", hint3:"A→N, B→O, C→P, ..., N→A, O→B ..." },
  { id:"c77", cipher:"ROT13", difficulty:"Easy",
    plaintext:"BREAK THE CODE", ciphertext:"OERNX GUR PBQR", keyInfo:"ROT13",
    hint1:"ROT13: every letter is shifted by exactly 13 positions.", hint2:"ROT13 is its own inverse — apply it twice to get the original.", hint3:"A→N, B→O, C→P, ..., N→A, O→B ..." },
  { id:"c78", cipher:"ROT13", difficulty:"Easy",
    plaintext:"FIND THE KEY", ciphertext:"SVAQ GUR XRL", keyInfo:"ROT13",
    hint1:"ROT13: every letter is shifted by exactly 13 positions.", hint2:"ROT13 is its own inverse — apply it twice to get the original.", hint3:"A→N, B→O, C→P, ..., N→A, O→B ..." },
  { id:"c79", cipher:"ROT13", difficulty:"Easy",
    plaintext:"OPEN THE DOOR", ciphertext:"BCRA GUR QBBE", keyInfo:"ROT13",
    hint1:"ROT13: every letter is shifted by exactly 13 positions.", hint2:"ROT13 is its own inverse — apply it twice to get the original.", hint3:"A→N, B→O, C→P, ..., N→A, O→B ..." },
  { id:"c80", cipher:"ROT13", difficulty:"Easy",
    plaintext:"NIGHT WATCH", ciphertext:"AVTUG JNGPU", keyInfo:"ROT13",
    hint1:"ROT13: every letter is shifted by exactly 13 positions.", hint2:"ROT13 is its own inverse — apply it twice to get the original.", hint3:"A→N, B→O, C→P, ..., N→A, O→B ..." },
  { id:"c81", cipher:"ROT13", difficulty:"Easy",
    plaintext:"FIRE AT WILL", ciphertext:"SVER NG JVYY", keyInfo:"ROT13",
    hint1:"ROT13: every letter is shifted by exactly 13 positions.", hint2:"ROT13 is its own inverse — apply it twice to get the original.", hint3:"A→N, B→O, C→P, ..., N→A, O→B ..." },
  { id:"c82", cipher:"ROT13", difficulty:"Easy",
    plaintext:"SEND BACKUP", ciphertext:"FRAQ ONPXHC", keyInfo:"ROT13",
    hint1:"ROT13: every letter is shifted by exactly 13 positions.", hint2:"ROT13 is its own inverse — apply it twice to get the original.", hint3:"A→N, B→O, C→P, ..., N→A, O→B ..." },
  { id:"c83", cipher:"ROT13", difficulty:"Easy",
    plaintext:"STORM THE GATE", ciphertext:"FGBEZ GUR TNGR", keyInfo:"ROT13",
    hint1:"ROT13: every letter is shifted by exactly 13 positions.", hint2:"ROT13 is its own inverse — apply it twice to get the original.", hint3:"A→N, B→O, C→P, ..., N→A, O→B ..." },
  { id:"c84", cipher:"ROT13", difficulty:"Easy",
    plaintext:"HOLD GROUND", ciphertext:"UBYQ TEBHAQ", keyInfo:"ROT13",
    hint1:"ROT13: every letter is shifted by exactly 13 positions.", hint2:"ROT13 is its own inverse — apply it twice to get the original.", hint3:"A→N, B→O, C→P, ..., N→A, O→B ..." },
  { id:"c85", cipher:"ROT13", difficulty:"Easy",
    plaintext:"ADVANCE TROOPS", ciphertext:"NQINAPR GEBBCF", keyInfo:"ROT13",
    hint1:"ROT13: every letter is shifted by exactly 13 positions.", hint2:"ROT13 is its own inverse — apply it twice to get the original.", hint3:"A→N, B→O, C→P, ..., N→A, O→B ..." },
  { id:"c86", cipher:"ROT13", difficulty:"Easy",
    plaintext:"RETREAT NOW", ciphertext:"ERGERNG ABJ", keyInfo:"ROT13",
    hint1:"ROT13: every letter is shifted by exactly 13 positions.", hint2:"ROT13 is its own inverse — apply it twice to get the original.", hint3:"A→N, B→O, C→P, ..., N→A, O→B ..." },
  { id:"c87", cipher:"ROT13", difficulty:"Easy",
    plaintext:"FLANK RIGHT", ciphertext:"SYNAX EVTUG", keyInfo:"ROT13",
    hint1:"ROT13: every letter is shifted by exactly 13 positions.", hint2:"ROT13 is its own inverse — apply it twice to get the original.", hint3:"A→N, B→O, C→P, ..., N→A, O→B ..." },
  { id:"c88", cipher:"ROT13", difficulty:"Easy",
    plaintext:"COVER LEFT", ciphertext:"PBIRE YRSG", keyInfo:"ROT13",
    hint1:"ROT13: every letter is shifted by exactly 13 positions.", hint2:"ROT13 is its own inverse — apply it twice to get the original.", hint3:"A→N, B→O, C→P, ..., N→A, O→B ..." },
  { id:"c89", cipher:"ROT13", difficulty:"Easy",
    plaintext:"EYES OPEN", ciphertext:"RLRF BCRA", keyInfo:"ROT13",
    hint1:"ROT13: every letter is shifted by exactly 13 positions.", hint2:"ROT13 is its own inverse — apply it twice to get the original.", hint3:"A→N, B→O, C→P, ..., N→A, O→B ..." },
  { id:"c90", cipher:"ROT13", difficulty:"Easy",
    plaintext:"STAND BY", ciphertext:"FGNAQ OL", keyInfo:"ROT13",
    hint1:"ROT13: every letter is shifted by exactly 13 positions.", hint2:"ROT13 is its own inverse — apply it twice to get the original.", hint3:"A→N, B→O, C→P, ..., N→A, O→B ..." },
  { id:"c91", cipher:"Atbash", difficulty:"Easy",
    plaintext:"HELLO", ciphertext:"SVOOL", keyInfo:"Reverse A↔Z",
    hint1:"Atbash: the alphabet is reversed. A↔Z, B↔Y, C↔X ...", hint2:"Each letter maps to its mirror position in the alphabet.", hint3:"Key: Reverse A↔Z. Plaintext first letter: H" },
  { id:"c92", cipher:"Atbash", difficulty:"Easy",
    plaintext:"WORLD", ciphertext:"DLIOW", keyInfo:"Reverse A↔Z",
    hint1:"Atbash: the alphabet is reversed. A↔Z, B↔Y, C↔X ...", hint2:"Each letter maps to its mirror position in the alphabet.", hint3:"Key: Reverse A↔Z. Plaintext first letter: W" },
  { id:"c93", cipher:"Atbash", difficulty:"Easy",
    plaintext:"CIPHER", ciphertext:"XRKSVI", keyInfo:"Reverse A↔Z",
    hint1:"Atbash: the alphabet is reversed. A↔Z, B↔Y, C↔X ...", hint2:"Each letter maps to its mirror position in the alphabet.", hint3:"Key: Reverse A↔Z. Plaintext first letter: C" },
  { id:"c94", cipher:"Atbash", difficulty:"Easy",
    plaintext:"SECRET", ciphertext:"HVXIVG", keyInfo:"Reverse A↔Z",
    hint1:"Atbash: the alphabet is reversed. A↔Z, B↔Y, C↔X ...", hint2:"Each letter maps to its mirror position in the alphabet.", hint3:"Key: Reverse A↔Z. Plaintext first letter: S" },
  { id:"c95", cipher:"Atbash", difficulty:"Easy",
    plaintext:"ATTACK", ciphertext:"ZGGZXP", keyInfo:"Reverse A↔Z",
    hint1:"Atbash: the alphabet is reversed. A↔Z, B↔Y, C↔X ...", hint2:"Each letter maps to its mirror position in the alphabet.", hint3:"Key: Reverse A↔Z. Plaintext first letter: A" },
  { id:"c96", cipher:"Atbash", difficulty:"Easy",
    plaintext:"DEFEND", ciphertext:"WVUVMW", keyInfo:"Reverse A↔Z",
    hint1:"Atbash: the alphabet is reversed. A↔Z, B↔Y, C↔X ...", hint2:"Each letter maps to its mirror position in the alphabet.", hint3:"Key: Reverse A↔Z. Plaintext first letter: D" },
  { id:"c97", cipher:"Atbash", difficulty:"Easy",
    plaintext:"SIGNAL", ciphertext:"HRTMZO", keyInfo:"Reverse A↔Z",
    hint1:"Atbash: the alphabet is reversed. A↔Z, B↔Y, C↔X ...", hint2:"Each letter maps to its mirror position in the alphabet.", hint3:"Key: Reverse A↔Z. Plaintext first letter: S" },
  { id:"c98", cipher:"Atbash", difficulty:"Easy",
    plaintext:"BEACON", ciphertext:"YVZXLM", keyInfo:"Reverse A↔Z",
    hint1:"Atbash: the alphabet is reversed. A↔Z, B↔Y, C↔X ...", hint2:"Each letter maps to its mirror position in the alphabet.", hint3:"Key: Reverse A↔Z. Plaintext first letter: B" },
  { id:"c99", cipher:"Atbash", difficulty:"Easy",
    plaintext:"SHADOW", ciphertext:"HSZWLD", keyInfo:"Reverse A↔Z",
    hint1:"Atbash: the alphabet is reversed. A↔Z, B↔Y, C↔X ...", hint2:"Each letter maps to its mirror position in the alphabet.", hint3:"Key: Reverse A↔Z. Plaintext first letter: S" },
  { id:"c100", cipher:"Atbash", difficulty:"Easy",
    plaintext:"FALCON", ciphertext:"UZOXLM", keyInfo:"Reverse A↔Z",
    hint1:"Atbash: the alphabet is reversed. A↔Z, B↔Y, C↔X ...", hint2:"Each letter maps to its mirror position in the alphabet.", hint3:"Key: Reverse A↔Z. Plaintext first letter: F" },
  { id:"c101", cipher:"Atbash", difficulty:"Easy",
    plaintext:"VECTOR", ciphertext:"EVXGLI", keyInfo:"Reverse A↔Z",
    hint1:"Atbash: the alphabet is reversed. A↔Z, B↔Y, C↔X ...", hint2:"Each letter maps to its mirror position in the alphabet.", hint3:"Key: Reverse A↔Z. Plaintext first letter: V" },
  { id:"c102", cipher:"Atbash", difficulty:"Easy",
    plaintext:"MATRIX", ciphertext:"NZGIRC", keyInfo:"Reverse A↔Z",
    hint1:"Atbash: the alphabet is reversed. A↔Z, B↔Y, C↔X ...", hint2:"Each letter maps to its mirror position in the alphabet.", hint3:"Key: Reverse A↔Z. Plaintext first letter: M" },
  { id:"c103", cipher:"Atbash", difficulty:"Easy",
    plaintext:"PYTHON", ciphertext:"KBGSLM", keyInfo:"Reverse A↔Z",
    hint1:"Atbash: the alphabet is reversed. A↔Z, B↔Y, C↔X ...", hint2:"Each letter maps to its mirror position in the alphabet.", hint3:"Key: Reverse A↔Z. Plaintext first letter: P" },
  { id:"c104", cipher:"Atbash", difficulty:"Easy",
    plaintext:"LAMBDA", ciphertext:"OZNYWZ", keyInfo:"Reverse A↔Z",
    hint1:"Atbash: the alphabet is reversed. A↔Z, B↔Y, C↔X ...", hint2:"Each letter maps to its mirror position in the alphabet.", hint3:"Key: Reverse A↔Z. Plaintext first letter: L" },
  { id:"c105", cipher:"Atbash", difficulty:"Easy",
    plaintext:"ROCKET", ciphertext:"ILXPVG", keyInfo:"Reverse A↔Z",
    hint1:"Atbash: the alphabet is reversed. A↔Z, B↔Y, C↔X ...", hint2:"Each letter maps to its mirror position in the alphabet.", hint3:"Key: Reverse A↔Z. Plaintext first letter: R" },
  { id:"c106", cipher:"Atbash", difficulty:"Easy",
    plaintext:"PLANET", ciphertext:"KOZMVG", keyInfo:"Reverse A↔Z",
    hint1:"Atbash: the alphabet is reversed. A↔Z, B↔Y, C↔X ...", hint2:"Each letter maps to its mirror position in the alphabet.", hint3:"Key: Reverse A↔Z. Plaintext first letter: P" },
  { id:"c107", cipher:"Atbash", difficulty:"Easy",
    plaintext:"ENIGMA", ciphertext:"VMRTNZ", keyInfo:"Reverse A↔Z",
    hint1:"Atbash: the alphabet is reversed. A↔Z, B↔Y, C↔X ...", hint2:"Each letter maps to its mirror position in the alphabet.", hint3:"Key: Reverse A↔Z. Plaintext first letter: E" },
  { id:"c108", cipher:"Atbash", difficulty:"Easy",
    plaintext:"CRYPTO", ciphertext:"XIBKGL", keyInfo:"Reverse A↔Z",
    hint1:"Atbash: the alphabet is reversed. A↔Z, B↔Y, C↔X ...", hint2:"Each letter maps to its mirror position in the alphabet.", hint3:"Key: Reverse A↔Z. Plaintext first letter: C" },
  { id:"c109", cipher:"Atbash", difficulty:"Easy",
    plaintext:"BINARY", ciphertext:"YRMZIB", keyInfo:"Reverse A↔Z",
    hint1:"Atbash: the alphabet is reversed. A↔Z, B↔Y, C↔X ...", hint2:"Each letter maps to its mirror position in the alphabet.", hint3:"Key: Reverse A↔Z. Plaintext first letter: B" },
  { id:"c110", cipher:"Atbash", difficulty:"Easy",
    plaintext:"SYSTEM", ciphertext:"HBHGVN", keyInfo:"Reverse A↔Z",
    hint1:"Atbash: the alphabet is reversed. A↔Z, B↔Y, C↔X ...", hint2:"Each letter maps to its mirror position in the alphabet.", hint3:"Key: Reverse A↔Z. Plaintext first letter: S" },
  { id:"c111", cipher:"Atbash", difficulty:"Easy",
    plaintext:"UNLOCK", ciphertext:"FMOLXP", keyInfo:"Reverse A↔Z",
    hint1:"Atbash: the alphabet is reversed. A↔Z, B↔Y, C↔X ...", hint2:"Each letter maps to its mirror position in the alphabet.", hint3:"Key: Reverse A↔Z. Plaintext first letter: U" },
  { id:"c112", cipher:"Atbash", difficulty:"Easy",
    plaintext:"ENCODE", ciphertext:"VMXLWV", keyInfo:"Reverse A↔Z",
    hint1:"Atbash: the alphabet is reversed. A↔Z, B↔Y, C↔X ...", hint2:"Each letter maps to its mirror position in the alphabet.", hint3:"Key: Reverse A↔Z. Plaintext first letter: E" },
  { id:"c113", cipher:"Atbash", difficulty:"Easy",
    plaintext:"DECODE", ciphertext:"WVXLWV", keyInfo:"Reverse A↔Z",
    hint1:"Atbash: the alphabet is reversed. A↔Z, B↔Y, C↔X ...", hint2:"Each letter maps to its mirror position in the alphabet.", hint3:"Key: Reverse A↔Z. Plaintext first letter: D" },
  { id:"c114", cipher:"Atbash", difficulty:"Easy",
    plaintext:"BREAKER", ciphertext:"YIVZPVI", keyInfo:"Reverse A↔Z",
    hint1:"Atbash: the alphabet is reversed. A↔Z, B↔Y, C↔X ...", hint2:"Each letter maps to its mirror position in the alphabet.", hint3:"Key: Reverse A↔Z. Plaintext first letter: B" },
  { id:"c115", cipher:"Atbash", difficulty:"Easy",
    plaintext:"KEYHOLE", ciphertext:"PVBSLOV", keyInfo:"Reverse A↔Z",
    hint1:"Atbash: the alphabet is reversed. A↔Z, B↔Y, C↔X ...", hint2:"Each letter maps to its mirror position in the alphabet.", hint3:"Key: Reverse A↔Z. Plaintext first letter: K" },
  { id:"c116", cipher:"Atbash", difficulty:"Easy",
    plaintext:"CODEWORD", ciphertext:"XLWVDLIW", keyInfo:"Reverse A↔Z",
    hint1:"Atbash: the alphabet is reversed. A↔Z, B↔Y, C↔X ...", hint2:"Each letter maps to its mirror position in the alphabet.", hint3:"Key: Reverse A↔Z. Plaintext first letter: C" },
  { id:"c117", cipher:"Atbash", difficulty:"Easy",
    plaintext:"FIREWALL", ciphertext:"URIVDZOO", keyInfo:"Reverse A↔Z",
    hint1:"Atbash: the alphabet is reversed. A↔Z, B↔Y, C↔X ...", hint2:"Each letter maps to its mirror position in the alphabet.", hint3:"Key: Reverse A↔Z. Plaintext first letter: F" },
  { id:"c118", cipher:"Atbash", difficulty:"Easy",
    plaintext:"DARKZONE", ciphertext:"WZIPALMV", keyInfo:"Reverse A↔Z",
    hint1:"Atbash: the alphabet is reversed. A↔Z, B↔Y, C↔X ...", hint2:"Each letter maps to its mirror position in the alphabet.", hint3:"Key: Reverse A↔Z. Plaintext first letter: D" },
  { id:"c119", cipher:"Atbash", difficulty:"Easy",
    plaintext:"REDSHIFT", ciphertext:"IVWHSRUG", keyInfo:"Reverse A↔Z",
    hint1:"Atbash: the alphabet is reversed. A↔Z, B↔Y, C↔X ...", hint2:"Each letter maps to its mirror position in the alphabet.", hint3:"Key: Reverse A↔Z. Plaintext first letter: R" },
  { id:"c120", cipher:"Atbash", difficulty:"Easy",
    plaintext:"BLUEBIRD", ciphertext:"YOFVYRIW", keyInfo:"Reverse A↔Z",
    hint1:"Atbash: the alphabet is reversed. A↔Z, B↔Y, C↔X ...", hint2:"Each letter maps to its mirror position in the alphabet.", hint3:"Key: Reverse A↔Z. Plaintext first letter: B" },
  { id:"c121", cipher:"Atbash", difficulty:"Easy",
    plaintext:"GHOST NET", ciphertext:"TSLHG MVG", keyInfo:"Reverse A↔Z",
    hint1:"Atbash: the alphabet is reversed. A↔Z, B↔Y, C↔X ...", hint2:"Each letter maps to its mirror position in the alphabet.", hint3:"Key: Reverse A↔Z. Plaintext first letter: G" },
  { id:"c122", cipher:"Atbash", difficulty:"Easy",
    plaintext:"IRON MASK", ciphertext:"RILM NZHP", keyInfo:"Reverse A↔Z",
    hint1:"Atbash: the alphabet is reversed. A↔Z, B↔Y, C↔X ...", hint2:"Each letter maps to its mirror position in the alphabet.", hint3:"Key: Reverse A↔Z. Plaintext first letter: I" },
  { id:"c123", cipher:"Atbash", difficulty:"Easy",
    plaintext:"COLD WAVE", ciphertext:"XLOW DZEV", keyInfo:"Reverse A↔Z",
    hint1:"Atbash: the alphabet is reversed. A↔Z, B↔Y, C↔X ...", hint2:"Each letter maps to its mirror position in the alphabet.", hint3:"Key: Reverse A↔Z. Plaintext first letter: C" },
  { id:"c124", cipher:"Atbash", difficulty:"Easy",
    plaintext:"DARK STAR", ciphertext:"WZIP HGZI", keyInfo:"Reverse A↔Z",
    hint1:"Atbash: the alphabet is reversed. A↔Z, B↔Y, C↔X ...", hint2:"Each letter maps to its mirror position in the alphabet.", hint3:"Key: Reverse A↔Z. Plaintext first letter: D" },
  { id:"c125", cipher:"Atbash", difficulty:"Easy",
    plaintext:"BLUE FLAG", ciphertext:"YOFV UOZT", keyInfo:"Reverse A↔Z",
    hint1:"Atbash: the alphabet is reversed. A↔Z, B↔Y, C↔X ...", hint2:"Each letter maps to its mirror position in the alphabet.", hint3:"Key: Reverse A↔Z. Plaintext first letter: B" },
  { id:"c126", cipher:"Atbash", difficulty:"Easy",
    plaintext:"RED ALERT", ciphertext:"IVW ZOVIG", keyInfo:"Reverse A↔Z",
    hint1:"Atbash: the alphabet is reversed. A↔Z, B↔Y, C↔X ...", hint2:"Each letter maps to its mirror position in the alphabet.", hint3:"Key: Reverse A↔Z. Plaintext first letter: R" },
  { id:"c127", cipher:"Atbash", difficulty:"Easy",
    plaintext:"CODE ZERO", ciphertext:"XLWV AVIL", keyInfo:"Reverse A↔Z",
    hint1:"Atbash: the alphabet is reversed. A↔Z, B↔Y, C↔X ...", hint2:"Each letter maps to its mirror position in the alphabet.", hint3:"Key: Reverse A↔Z. Plaintext first letter: C" },
  { id:"c128", cipher:"Atbash", difficulty:"Easy",
    plaintext:"LOCK DOWN", ciphertext:"OLXP WLDM", keyInfo:"Reverse A↔Z",
    hint1:"Atbash: the alphabet is reversed. A↔Z, B↔Y, C↔X ...", hint2:"Each letter maps to its mirror position in the alphabet.", hint3:"Key: Reverse A↔Z. Plaintext first letter: L" },
  { id:"c129", cipher:"Atbash", difficulty:"Easy",
    plaintext:"OPEN FIRE", ciphertext:"LKVM URIV", keyInfo:"Reverse A↔Z",
    hint1:"Atbash: the alphabet is reversed. A↔Z, B↔Y, C↔X ...", hint2:"Each letter maps to its mirror position in the alphabet.", hint3:"Key: Reverse A↔Z. Plaintext first letter: O" },
  { id:"c130", cipher:"Atbash", difficulty:"Easy",
    plaintext:"STAND OFF", ciphertext:"HGZMW LUU", keyInfo:"Reverse A↔Z",
    hint1:"Atbash: the alphabet is reversed. A↔Z, B↔Y, C↔X ...", hint2:"Each letter maps to its mirror position in the alphabet.", hint3:"Key: Reverse A↔Z. Plaintext first letter: S" },
  { id:"c131", cipher:"Vigenère", difficulty:"Medium",
    plaintext:"ATTACK AT DAWN", ciphertext:"KXRKGI KX BKAL", keyInfo:"Key: KEY",
    hint1:"Vigenère cipher — a repeating keyword shifts each letter differently.", hint2:"The key length is 3 letters.", hint3:"Key: KEY" },
  { id:"c132", cipher:"Vigenère", difficulty:"Medium",
    plaintext:"SEND HELP NOW", ciphertext:"UEGF HXNP GQW", keyInfo:"Key: CAT",
    hint1:"Vigenère cipher — a repeating keyword shifts each letter differently.", hint2:"The key length is 3 letters.", hint3:"Key: CAT" },
  { id:"c133", cipher:"Vigenère", difficulty:"Medium",
    plaintext:"HOLD THE LINE", ciphertext:"KCRG HNH ZOQS", keyInfo:"Key: DOG",
    hint1:"Vigenère cipher — a repeating keyword shifts each letter differently.", hint2:"The key length is 3 letters.", hint3:"Key: DOG" },
  { id:"c134", cipher:"Vigenère", difficulty:"Medium",
    plaintext:"BREACH THE WALL", ciphertext:"TLRSWU LBR OUYD", keyInfo:"Key: SUN",
    hint1:"Vigenère cipher — a repeating keyword shifts each letter differently.", hint2:"The key length is 3 letters.", hint3:"Key: SUN" },
  { id:"c135", cipher:"Vigenère", difficulty:"Medium",
    plaintext:"SECURE THE BASE", ciphertext:"SGGUTI TJI BCWE", keyInfo:"Key: ACE",
    hint1:"Vigenère cipher — a repeating keyword shifts each letter differently.", hint2:"The key length is 3 letters.", hint3:"Key: ACE" },
  { id:"c136", cipher:"Vigenère", difficulty:"Medium",
    plaintext:"EXTRACT THE KEY", ciphertext:"MZXZCGB VLM MIG", keyInfo:"Key: ICE",
    hint1:"Vigenère cipher — a repeating keyword shifts each letter differently.", hint2:"The key length is 3 letters.", hint3:"Key: ICE" },
  { id:"c137", cipher:"Vigenère", difficulty:"Medium",
    plaintext:"SIGNAL THE TEAM", ciphertext:"GIQBAV HHO HEKA", keyInfo:"Key: OAK",
    hint1:"Vigenère cipher — a repeating keyword shifts each letter differently.", hint2:"The key length is 3 letters.", hint3:"Key: OAK" },
  { id:"c138", cipher:"Vigenère", difficulty:"Medium",
    plaintext:"ABORT THE RUN", ciphertext:"FJUWB ZMM XZV", keyInfo:"Key: FIG",
    hint1:"Vigenère cipher — a repeating keyword shifts each letter differently.", hint2:"The key length is 3 letters.", hint3:"Key: FIG" },
  { id:"c139", cipher:"Vigenère", difficulty:"Medium",
    plaintext:"GO TO GROUND", ciphertext:"HO MP GKPUGE", keyInfo:"Key: BAT",
    hint1:"Vigenère cipher — a repeating keyword shifts each letter differently.", hint2:"The key length is 3 letters.", hint3:"Key: BAT" },
  { id:"c140", cipher:"Vigenère", difficulty:"Medium",
    plaintext:"THE HUNT BEGINS", ciphertext:"SHT GUCS BTFICR", keyInfo:"Key: ZAP",
    hint1:"Vigenère cipher — a repeating keyword shifts each letter differently.", hint2:"The key length is 3 letters.", hint3:"Key: ZAP" },
  { id:"c141", cipher:"Vigenère", difficulty:"Medium",
    plaintext:"OPEN THE VAULT", ciphertext:"APTZ TWQ VPGLI", keyInfo:"Key: MAP",
    hint1:"Vigenère cipher — a repeating keyword shifts each letter differently.", hint2:"The key length is 3 letters.", hint3:"Key: MAP" },
  { id:"c142", cipher:"Vigenère", difficulty:"Medium",
    plaintext:"FIND THE TARGET", ciphertext:"SMGQ XAR XTEKXG", keyInfo:"Key: NET",
    hint1:"Vigenère cipher — a repeating keyword shifts each letter differently.", hint2:"The key length is 3 letters.", hint3:"Key: NET" },
  { id:"c143", cipher:"Vigenère", difficulty:"Medium",
    plaintext:"CODE IS BROKEN", ciphertext:"QFES ZT PIPYVO", keyInfo:"Key: ORB",
    hint1:"Vigenère cipher — a repeating keyword shifts each letter differently.", hint2:"The key length is 3 letters.", hint3:"Key: ORB" },
  { id:"c144", cipher:"Vigenère", difficulty:"Medium",
    plaintext:"RALLY THE SQUAD", ciphertext:"AAJUY RQE QZUYM", keyInfo:"Key: JAY",
    hint1:"Vigenère cipher — a repeating keyword shifts each letter differently.", hint2:"The key length is 3 letters.", hint3:"Key: JAY" },
  { id:"c145", cipher:"Vigenère", difficulty:"Medium",
    plaintext:"MOVE IN SILENCE", ciphertext:"PSIH MA VMYHRPH", keyInfo:"Key: DEN",
    hint1:"Vigenère cipher — a repeating keyword shifts each letter differently.", hint2:"The key length is 3 letters.", hint3:"Key: DEN" },
  { id:"c146", cipher:"Vigenère", difficulty:"Medium",
    plaintext:"LIGHTS ARE OUT", ciphertext:"LZIHKU AIG OLV", keyInfo:"Key: ARC",
    hint1:"Vigenère cipher — a repeating keyword shifts each letter differently.", hint2:"The key length is 3 letters.", hint3:"Key: ARC" },
  { id:"c147", cipher:"Vigenère", difficulty:"Medium",
    plaintext:"FIRE ON SIGNAL", ciphertext:"YIFX OB LIUGAZ", keyInfo:"Key: TAO",
    hint1:"Vigenère cipher — a repeating keyword shifts each letter differently.", hint2:"The key length is 3 letters.", hint3:"Key: TAO" },
  { id:"c148", cipher:"Vigenère", difficulty:"Medium",
    plaintext:"STORM THE GATES", ciphertext:"TXSSQ XII KBXIT", keyInfo:"Key: BEE",
    hint1:"Vigenère cipher — a repeating keyword shifts each letter differently.", hint2:"The key length is 3 letters.", hint3:"Key: BEE" },
  { id:"c149", cipher:"Vigenère", difficulty:"Medium",
    plaintext:"WATCH THE CLOCK", ciphertext:"SEUYL UDI DHSDG", keyInfo:"Key: WEB",
    hint1:"Vigenère cipher — a repeating keyword shifts each letter differently.", hint2:"The key length is 3 letters.", hint3:"Key: WEB" },
  { id:"c150", cipher:"Vigenère", difficulty:"Medium",
    plaintext:"TIME TO STRIKE", ciphertext:"GQFR BH FBKVSX", keyInfo:"Key: NIT",
    hint1:"Vigenère cipher — a repeating keyword shifts each letter differently.", hint2:"The key length is 3 letters.", hint3:"Key: NIT" },
  { id:"c151", cipher:"Vigenère", difficulty:"Medium",
    plaintext:"THE PATH IS CLEAR", ciphertext:"SLR OEGG MF BPRZV", keyInfo:"Key: ZEN",
    hint1:"Vigenère cipher — a repeating keyword shifts each letter differently.", hint2:"The key length is 3 letters.", hint3:"Key: ZEN" },
  { id:"c152", cipher:"Vigenère", difficulty:"Medium",
    plaintext:"SHADOWS IN MOTION", ciphertext:"JFEUMAJ GR DMXZMR", keyInfo:"Key: RYE",
    hint1:"Vigenère cipher — a repeating keyword shifts each letter differently.", hint2:"The key length is 3 letters.", hint3:"Key: RYE" },
  { id:"c153", cipher:"Vigenère", difficulty:"Medium",
    plaintext:"KEEP YOUR COVER", ciphertext:"SZCX TMCM AWQCZ", keyInfo:"Key: IVY",
    hint1:"Vigenère cipher — a repeating keyword shifts each letter differently.", hint2:"The key length is 3 letters.", hint3:"Key: IVY" },
  { id:"c154", cipher:"Vigenère", difficulty:"Medium",
    plaintext:"RADIO IS DOWN", ciphertext:"VLPMZ UW OAAY", keyInfo:"Key: ELM",
    hint1:"Vigenère cipher — a repeating keyword shifts each letter differently.", hint2:"The key length is 3 letters.", hint3:"Key: ELM" },
  { id:"c155", cipher:"Vigenère", difficulty:"Medium",
    plaintext:"THE NET IS CLOSING", ciphertext:"HHX BEM WS VZOLWNZ", keyInfo:"Key: OAT",
    hint1:"Vigenère cipher — a repeating keyword shifts each letter differently.", hint2:"The key length is 3 letters.", hint3:"Key: OAT" },
  { id:"c156", cipher:"Vigenère", difficulty:"Medium",
    plaintext:"BURN THE EVIDENCE", ciphertext:"BJVN ILE TZISINRI", keyInfo:"Key: APE",
    hint1:"Vigenère cipher — a repeating keyword shifts each letter differently.", hint2:"The key length is 3 letters.", hint3:"Key: APE" },
  { id:"c157", cipher:"Vigenère", difficulty:"Medium",
    plaintext:"MARK THE LOCATION", ciphertext:"SNLQ GBK YIINNOBH", keyInfo:"Key: GNU",
    hint1:"Vigenère cipher — a repeating keyword shifts each letter differently.", hint2:"The key length is 3 letters.", hint3:"Key: GNU" },
  { id:"c158", cipher:"Vigenère", difficulty:"Medium",
    plaintext:"FLEE THE SCENE", ciphertext:"HZHG HKG GFGBH", keyInfo:"Key: COD",
    hint1:"Vigenère cipher — a repeating keyword shifts each letter differently.", hint2:"The key length is 3 letters.", hint3:"Key: COD" },
  { id:"c159", cipher:"Vigenère", difficulty:"Medium",
    plaintext:"COVER THE RETREAT", ciphertext:"FWHHZ FKM DHBDHIF", keyInfo:"Key: DIM",
    hint1:"Vigenère cipher — a repeating keyword shifts each letter differently.", hint2:"The key length is 3 letters.", hint3:"Key: DIM" },
  { id:"c160", cipher:"Vigenère", difficulty:"Medium",
    plaintext:"THE MISSION ENDS", ciphertext:"YVK RWYXWUS STIG", keyInfo:"Key: FOG",
    hint1:"Vigenère cipher — a repeating keyword shifts each letter differently.", hint2:"The key length is 3 letters.", hint3:"Key: FOG" },
  { id:"c161", cipher:"Vigenère", difficulty:"Medium",
    plaintext:"LAUNCH THE ATTACK", ciphertext:"SOJUQW AVT HHIHQZ", keyInfo:"Key: HOP",
    hint1:"Vigenère cipher — a repeating keyword shifts each letter differently.", hint2:"The key length is 3 letters.", hint3:"Key: HOP" },
  { id:"c162", cipher:"Vigenère", difficulty:"Medium",
    plaintext:"HOLD YOUR BREATH", ciphertext:"QCJM MMDF ZASYCV", keyInfo:"Key: JOY",
    hint1:"Vigenère cipher — a repeating keyword shifts each letter differently.", hint2:"The key length is 3 letters.", hint3:"Key: JOY" },
  { id:"c163", cipher:"Vigenère", difficulty:"Medium",
    plaintext:"THE KEY IS HIDDEN", ciphertext:"DPX UMR SA ASLWOV", keyInfo:"Key: KIT",
    hint1:"Vigenère cipher — a repeating keyword shifts each letter differently.", hint2:"The key length is 3 letters.", hint3:"Key: KIT" },
  { id:"c164", cipher:"Vigenère", difficulty:"Medium",
    plaintext:"DECODE THE MESSAGE", ciphertext:"OSIZRK EVK XSYDOMP", keyInfo:"Key: LOG",
    hint1:"Vigenère cipher — a repeating keyword shifts each letter differently.", hint2:"The key length is 3 letters.", hint3:"Key: LOG" },
  { id:"c165", cipher:"Vigenère", difficulty:"Medium",
    plaintext:"CRACK THE CIPHER", ciphertext:"OLDOE WTY FUJKQL", keyInfo:"Key: MUD",
    hint1:"Vigenère cipher — a repeating keyword shifts each letter differently.", hint2:"The key length is 3 letters.", hint3:"Key: MUD" },
  { id:"c166", cipher:"Vigenère", difficulty:"Medium",
    plaintext:"FIND THE ANSWER", ciphertext:"SCAQ NUR UAFQRE", keyInfo:"Key: NUN",
    hint1:"Vigenère cipher — a repeating keyword shifts each letter differently.", hint2:"The key length is 3 letters.", hint3:"Key: NUN" },
  { id:"c167", cipher:"Vigenère", difficulty:"Medium",
    plaintext:"THE VAULT IS EMPTY", ciphertext:"HWX JPNZI BG TFDIR", keyInfo:"Key: OPT",
    hint1:"Vigenère cipher — a repeating keyword shifts each letter differently.", hint2:"The key length is 3 letters.", hint3:"Key: OPT" },
  { id:"c168", cipher:"Vigenère", difficulty:"Medium",
    plaintext:"TRUST NO MACHINE", ciphertext:"IVAHX TD QGRLOCI", keyInfo:"Key: PEG",
    hint1:"Vigenère cipher — a repeating keyword shifts each letter differently.", hint2:"The key length is 3 letters.", hint3:"Key: PEG" },
  { id:"c169", cipher:"Vigenère", difficulty:"Medium",
    plaintext:"THE CODE HAS CHANGED", ciphertext:"JBE SIDU BAI WHQHGUX", keyInfo:"Key: QUA",
    hint1:"Vigenère cipher — a repeating keyword shifts each letter differently.", hint2:"The key length is 3 letters.", hint3:"Key: QUA" },
  { id:"c170", cipher:"Vigenère", difficulty:"Medium",
    plaintext:"NEW ORDERS RECEIVED", ciphertext:"EEJ FRQVRF IEPVIIVD", keyInfo:"Key: RAN",
    hint1:"Vigenère cipher — a repeating keyword shifts each letter differently.", hint2:"The key length is 3 letters.", hint3:"Key: RAN" },
  { id:"c171", cipher:"Vigenère", difficulty:"Medium",
    plaintext:"NIGHT OPS BEGIN", ciphertext:"FIVZT DHS QWGXF", keyInfo:"Key: SAP",
    hint1:"Vigenère cipher — a repeating keyword shifts each letter differently.", hint2:"The key length is 3 letters.", hint3:"Key: SAP" },
  { id:"c172", cipher:"Vigenère", difficulty:"Medium",
    plaintext:"DAYBREAK APPROACHES", ciphertext:"WUZULFTE BIJSHUDAYT", keyInfo:"Key: TUB",
    hint1:"Vigenère cipher — a repeating keyword shifts each letter differently.", hint2:"The key length is 3 letters.", hint3:"Key: TUB" },
  { id:"c173", cipher:"Vigenère", difficulty:"Medium",
    plaintext:"THE ENEMY RETREATS", ciphertext:"NYR YERGP EYKEYRGM", keyInfo:"Key: URN",
    hint1:"Vigenère cipher — a repeating keyword shifts each letter differently.", hint2:"The key length is 3 letters.", hint3:"Key: URN" },
  { id:"c174", cipher:"Vigenère", difficulty:"Medium",
    plaintext:"VICTORY IS OURS", ciphertext:"QIVOOKT IL JUKN", keyInfo:"Key: VAT",
    hint1:"Vigenère cipher — a repeating keyword shifts each letter differently.", hint2:"The key length is 3 letters.", hint3:"Key: VAT" },
  { id:"c175", cipher:"Vigenère", difficulty:"Medium",
    plaintext:"STAND DOWN TROOPS", ciphertext:"OTXJD AKWK PRLKPP", keyInfo:"Key: WAX",
    hint1:"Vigenère cipher — a repeating keyword shifts each letter differently.", hint2:"The key length is 3 letters.", hint3:"Key: WAX" },
  { id:"c176", cipher:"Vigenère", difficulty:"Medium",
    plaintext:"SECURE ALL POSTS", ciphertext:"QEOSRQ YLX NOERS", keyInfo:"Key: YAM",
    hint1:"Vigenère cipher — a repeating keyword shifts each letter differently.", hint2:"The key length is 3 letters.", hint3:"Key: YAM" },
  { id:"c177", cipher:"Vigenère", difficulty:"Medium",
    plaintext:"RETURN TO COMMAND", ciphertext:"QMMTZG SW VNUFZVW", keyInfo:"Key: ZIT",
    hint1:"Vigenère cipher — a repeating keyword shifts each letter differently.", hint2:"The key length is 3 letters.", hint3:"Key: ZIT" },
  { id:"c178", cipher:"Vigenère", difficulty:"Medium",
    plaintext:"DEBRIEF AT DAWN", ciphertext:"DFZRJCF BR DBUN", keyInfo:"Key: ABY",
    hint1:"Vigenère cipher — a repeating keyword shifts each letter differently.", hint2:"The key length is 3 letters.", hint3:"Key: ABY" },
  { id:"c179", cipher:"Vigenère", difficulty:"Medium",
    plaintext:"OPERATION COMPLETE", ciphertext:"ORXRCMIQG CQFPNXTG", keyInfo:"Key: ACT",
    hint1:"Vigenère cipher — a repeating keyword shifts each letter differently.", hint2:"The key length is 3 letters.", hint3:"Key: ACT" },
  { id:"c180", cipher:"Vigenère", difficulty:"Medium",
    plaintext:"MISSION ACCOMPLISHED", ciphertext:"MLGSLCN DQCRAPOWSKSD", keyInfo:"Key: ADO",
    hint1:"Vigenère cipher — a repeating keyword shifts each letter differently.", hint2:"The key length is 3 letters.", hint3:"Key: ADO" },
  { id:"c181", cipher:"Vigenère", difficulty:"Medium",
    plaintext:"THE PACKAGE IS SAFE", ciphertext:"TPH PIFKIJE QV SIIE", keyInfo:"Key: AID",
    hint1:"Vigenère cipher — a repeating keyword shifts each letter differently.", hint2:"The key length is 3 letters.", hint3:"Key: AID" },
  { id:"c182", cipher:"Vigenère", difficulty:"Medium",
    plaintext:"ALL CLEAR SIGNAL", ciphertext:"ATX CTQAZ EIOZAT", keyInfo:"Key: AIM",
    hint1:"Vigenère cipher — a repeating keyword shifts each letter differently.", hint2:"The key length is 3 letters.", hint3:"Key: AIM" },
  { id:"c183", cipher:"Vigenère", difficulty:"Medium",
    plaintext:"THE BRIDGE IS TAKEN", ciphertext:"TPV BZZDOV IA KASVN", keyInfo:"Key: AIR",
    hint1:"Vigenère cipher — a repeating keyword shifts each letter differently.", hint2:"The key length is 3 letters.", hint3:"Key: AIR" },
  { id:"c184", cipher:"Vigenère", difficulty:"Medium",
    plaintext:"REINFORCE THE FLANK", ciphertext:"RMBNNHRKX TPX FTTNS", keyInfo:"Key: AIT",
    hint1:"Vigenère cipher — a repeating keyword shifts each letter differently.", hint2:"The key length is 3 letters.", hint3:"Key: AIT" },
  { id:"c185", cipher:"Vigenère", difficulty:"Medium",
    plaintext:"ENEMY AT THE GATES", ciphertext:"EXEMI AT DHE QATOS", keyInfo:"Key: AKA",
    hint1:"Vigenère cipher — a repeating keyword shifts each letter differently.", hint2:"The key length is 3 letters.", hint3:"Key: AKA" },
  { id:"c186", cipher:"Vigenère", difficulty:"Medium",
    plaintext:"WE HOLD THIS LINE", ciphertext:"WP HOWD TSIS WINP", keyInfo:"Key: ALA",
    hint1:"Vigenère cipher — a repeating keyword shifts each letter differently.", hint2:"The key length is 3 letters.", hint3:"Key: ALA" },
  { id:"c187", cipher:"Vigenère", difficulty:"Medium",
    plaintext:"THE CIPHER IS BROKEN", ciphertext:"TSF CTQHPS ID CRZLEY", keyInfo:"Key: ALB",
    hint1:"Vigenère cipher — a repeating keyword shifts each letter differently.", hint2:"The key length is 3 letters.", hint3:"Key: ALB" },
  { id:"c188", cipher:"Vigenère", difficulty:"Medium",
    plaintext:"ENCRYPT ALL TRAFFIC", ciphertext:"EYGRJTT LPL EVAQJIN", keyInfo:"Key: ALE",
    hint1:"Vigenère cipher — a repeating keyword shifts each letter differently.", hint2:"The key length is 3 letters.", hint3:"Key: ALE" },
  { id:"c189", cipher:"Vigenère", difficulty:"Medium",
    plaintext:"CHANGE THE FREQUENCY", ciphertext:"CSTNRX TSX FCXQFXNNR", keyInfo:"Key: ALT",
    hint1:"Vigenère cipher — a repeating keyword shifts each letter differently.", hint2:"The key length is 3 letters.", hint3:"Key: ALT" },
  { id:"c190", cipher:"Vigenère", difficulty:"Medium",
    plaintext:"NEW CODE ISSUED", ciphertext:"NQE CALE UASGMD", keyInfo:"Key: AMI",
    hint1:"Vigenère cipher — a repeating keyword shifts each letter differently.", hint2:"The key length is 3 letters.", hint3:"Key: AMI" },
  { id:"c191", cipher:"Rail Fence", difficulty:"Hard",
    plaintext:"HELLOWORLD", ciphertext:"HLOOLELWRD", keyInfo:"2 rails",
    hint1:"Rail Fence cipher — letters are written in a zigzag pattern.", hint2:"This uses 2 rails. Write the ciphertext diagonally then read across.", hint3:"Number of rails: 2" },
  { id:"c192", cipher:"Rail Fence", difficulty:"Hard",
    plaintext:"ATTACKATDAWN", ciphertext:"ATCADWTAKTAN", keyInfo:"2 rails",
    hint1:"Rail Fence cipher — letters are written in a zigzag pattern.", hint2:"This uses 2 rails. Write the ciphertext diagonally then read across.", hint3:"Number of rails: 2" },
  { id:"c193", cipher:"Rail Fence", difficulty:"Hard",
    plaintext:"SENDBACKUP", ciphertext:"SNBCUEDAKP", keyInfo:"2 rails",
    hint1:"Rail Fence cipher — letters are written in a zigzag pattern.", hint2:"This uses 2 rails. Write the ciphertext diagonally then read across.", hint3:"Number of rails: 2" },
  { id:"c194", cipher:"Rail Fence", difficulty:"Hard",
    plaintext:"HOLDTHELINE", ciphertext:"HLTEIEODHLN", keyInfo:"2 rails",
    hint1:"Rail Fence cipher — letters are written in a zigzag pattern.", hint2:"This uses 2 rails. Write the ciphertext diagonally then read across.", hint3:"Number of rails: 2" },
  { id:"c195", cipher:"Rail Fence", difficulty:"Hard",
    plaintext:"BREAKTHECODE", ciphertext:"BEKHCDRATEOE", keyInfo:"2 rails",
    hint1:"Rail Fence cipher — letters are written in a zigzag pattern.", hint2:"This uses 2 rails. Write the ciphertext diagonally then read across.", hint3:"Number of rails: 2" },
  { id:"c196", cipher:"Rail Fence", difficulty:"Hard",
    plaintext:"FINDTHEKEY", ciphertext:"FNTEEIDHKY", keyInfo:"2 rails",
    hint1:"Rail Fence cipher — letters are written in a zigzag pattern.", hint2:"This uses 2 rails. Write the ciphertext diagonally then read across.", hint3:"Number of rails: 2" },
  { id:"c197", cipher:"Rail Fence", difficulty:"Hard",
    plaintext:"DECRYPTTHIS", ciphertext:"DCYTHSERPTI", keyInfo:"2 rails",
    hint1:"Rail Fence cipher — letters are written in a zigzag pattern.", hint2:"This uses 2 rails. Write the ciphertext diagonally then read across.", hint3:"Number of rails: 2" },
  { id:"c198", cipher:"Rail Fence", difficulty:"Hard",
    plaintext:"MISSIONGO", ciphertext:"MSINOISOG", keyInfo:"2 rails",
    hint1:"Rail Fence cipher — letters are written in a zigzag pattern.", hint2:"This uses 2 rails. Write the ciphertext diagonally then read across.", hint3:"Number of rails: 2" },
  { id:"c199", cipher:"Rail Fence", difficulty:"Hard",
    plaintext:"NIGHTWATCH", ciphertext:"NGTACIHWTH", keyInfo:"2 rails",
    hint1:"Rail Fence cipher — letters are written in a zigzag pattern.", hint2:"This uses 2 rails. Write the ciphertext diagonally then read across.", hint3:"Number of rails: 2" },
  { id:"c200", cipher:"Rail Fence", difficulty:"Hard",
    plaintext:"CODEISRED", ciphertext:"CDIRDOESE", keyInfo:"2 rails",
    hint1:"Rail Fence cipher — letters are written in a zigzag pattern.", hint2:"This uses 2 rails. Write the ciphertext diagonally then read across.", hint3:"Number of rails: 2" },
  { id:"c201", cipher:"Rail Fence", difficulty:"Hard",
    plaintext:"WEAREDISCOVERED", ciphertext:"WECRERDSOEEAIVD", keyInfo:"3 rails",
    hint1:"Rail Fence cipher — letters are written in a zigzag pattern.", hint2:"This uses 3 rails. Write the ciphertext diagonally then read across.", hint3:"Number of rails: 3" },
  { id:"c202", cipher:"Rail Fence", difficulty:"Hard",
    plaintext:"DEFENDTHEFORT", ciphertext:"DNETEEDHFRFTO", keyInfo:"3 rails",
    hint1:"Rail Fence cipher — letters are written in a zigzag pattern.", hint2:"This uses 3 rails. Write the ciphertext diagonally then read across.", hint3:"Number of rails: 3" },
  { id:"c203", cipher:"Rail Fence", difficulty:"Hard",
    plaintext:"SENDTHESIGNAL", ciphertext:"STILEDHSGANEN", keyInfo:"3 rails",
    hint1:"Rail Fence cipher — letters are written in a zigzag pattern.", hint2:"This uses 3 rails. Write the ciphertext diagonally then read across.", hint3:"Number of rails: 3" },
  { id:"c204", cipher:"Rail Fence", difficulty:"Hard",
    plaintext:"MEETATMIDNIGHT", ciphertext:"MADHETTINGTEMI", keyInfo:"3 rails",
    hint1:"Rail Fence cipher — letters are written in a zigzag pattern.", hint2:"This uses 3 rails. Write the ciphertext diagonally then read across.", hint3:"Number of rails: 3" },
  { id:"c205", cipher:"Rail Fence", difficulty:"Hard",
    plaintext:"THECODEISBROKEN", ciphertext:"TOSKHCDIBOEEERN", keyInfo:"3 rails",
    hint1:"Rail Fence cipher — letters are written in a zigzag pattern.", hint2:"This uses 3 rails. Write the ciphertext diagonally then read across.", hint3:"Number of rails: 3" },
  { id:"c206", cipher:"Rail Fence", difficulty:"Hard",
    plaintext:"SILENCEANDSHADOW", ciphertext:"SNNAIECADHDWLESO", keyInfo:"3 rails",
    hint1:"Rail Fence cipher — letters are written in a zigzag pattern.", hint2:"This uses 3 rails. Write the ciphertext diagonally then read across.", hint3:"Number of rails: 3" },
  { id:"c207", cipher:"Rail Fence", difficulty:"Hard",
    plaintext:"ESCAPETHETUNNEL", ciphertext:"EPENSAEHTNECTUL", keyInfo:"3 rails",
    hint1:"Rail Fence cipher — letters are written in a zigzag pattern.", hint2:"This uses 3 rails. Write the ciphertext diagonally then read across.", hint3:"Number of rails: 3" },
  { id:"c208", cipher:"Rail Fence", difficulty:"Hard",
    plaintext:"RENDEZVOUSATDAWN", ciphertext:"REUDEDZOSTANNVAW", keyInfo:"3 rails",
    hint1:"Rail Fence cipher — letters are written in a zigzag pattern.", hint2:"This uses 3 rails. Write the ciphertext diagonally then read across.", hint3:"Number of rails: 3" },
  { id:"c209", cipher:"Rail Fence", difficulty:"Hard",
    plaintext:"BURNAFTERREADING", ciphertext:"BARDUNFERAIGRTEN", keyInfo:"3 rails",
    hint1:"Rail Fence cipher — letters are written in a zigzag pattern.", hint2:"This uses 3 rails. Write the ciphertext diagonally then read across.", hint3:"Number of rails: 3" },
  { id:"c210", cipher:"Rail Fence", difficulty:"Hard",
    plaintext:"THEVAULTISOPEN", ciphertext:"TAIEHVUTSPNELO", keyInfo:"3 rails",
    hint1:"Rail Fence cipher — letters are written in a zigzag pattern.", hint2:"This uses 3 rails. Write the ciphertext diagonally then read across.", hint3:"Number of rails: 3" },
  { id:"c211", cipher:"Rail Fence", difficulty:"Hard",
    plaintext:"OPERATIONNIGHTFALL", ciphertext:"OANHLPRTONGTALEIIF", keyInfo:"3 rails",
    hint1:"Rail Fence cipher — letters are written in a zigzag pattern.", hint2:"This uses 3 rails. Write the ciphertext diagonally then read across.", hint3:"Number of rails: 3" },
  { id:"c212", cipher:"Rail Fence", difficulty:"Hard",
    plaintext:"DESTROYALLEVIDENCE", ciphertext:"DRLICETOALVDNESYEE", keyInfo:"3 rails",
    hint1:"Rail Fence cipher — letters are written in a zigzag pattern.", hint2:"This uses 3 rails. Write the ciphertext diagonally then read across.", hint3:"Number of rails: 3" },
  { id:"c213", cipher:"Rail Fence", difficulty:"Hard",
    plaintext:"FOLLOWTHEWHITERABBIT", ciphertext:"FOETBOLWHWIEABTLTHRI", keyInfo:"3 rails",
    hint1:"Rail Fence cipher — letters are written in a zigzag pattern.", hint2:"This uses 3 rails. Write the ciphertext diagonally then read across.", hint3:"Number of rails: 3" },
  { id:"c214", cipher:"Rail Fence", difficulty:"Hard",
    plaintext:"SECURETHEDOCUMENTS", ciphertext:"SREUTEUEHDCMNSCTOE", keyInfo:"3 rails",
    hint1:"Rail Fence cipher — letters are written in a zigzag pattern.", hint2:"This uses 3 rails. Write the ciphertext diagonally then read across.", hint3:"Number of rails: 3" },
  { id:"c215", cipher:"Rail Fence", difficulty:"Hard",
    plaintext:"ADVANCEATMIDNIGHT", ciphertext:"ANTNTDACAMDIHVEIG", keyInfo:"3 rails",
    hint1:"Rail Fence cipher — letters are written in a zigzag pattern.", hint2:"This uses 3 rails. Write the ciphertext diagonally then read across.", hint3:"Number of rails: 3" },
  { id:"c216", cipher:"Rail Fence", difficulty:"Hard",
    plaintext:"RETREATTOBASE", ciphertext:"REOEERATBSTTA", keyInfo:"3 rails",
    hint1:"Rail Fence cipher — letters are written in a zigzag pattern.", hint2:"This uses 3 rails. Write the ciphertext diagonally then read across.", hint3:"Number of rails: 3" },
  { id:"c217", cipher:"Rail Fence", difficulty:"Hard",
    plaintext:"EXTRACTTHEASSET", ciphertext:"EAHSXRCTESETTAT", keyInfo:"3 rails",
    hint1:"Rail Fence cipher — letters are written in a zigzag pattern.", hint2:"This uses 3 rails. Write the ciphertext diagonally then read across.", hint3:"Number of rails: 3" },
  { id:"c218", cipher:"Rail Fence", difficulty:"Hard",
    plaintext:"CONFIRMRENDEZVOUS", ciphertext:"CIEZSOFRRNEVUNMDO", keyInfo:"3 rails",
    hint1:"Rail Fence cipher — letters are written in a zigzag pattern.", hint2:"This uses 3 rails. Write the ciphertext diagonally then read across.", hint3:"Number of rails: 3" },
  { id:"c219", cipher:"Rail Fence", difficulty:"Hard",
    plaintext:"PROCEEDWITHCAUTION", ciphertext:"PEIAORCEWTCUINODHT", keyInfo:"3 rails",
    hint1:"Rail Fence cipher — letters are written in a zigzag pattern.", hint2:"This uses 3 rails. Write the ciphertext diagonally then read across.", hint3:"Number of rails: 3" },
  { id:"c220", cipher:"Rail Fence", difficulty:"Hard",
    plaintext:"THEKEYISBELOW", ciphertext:"TEBWHKYSEOEIL", keyInfo:"3 rails",
    hint1:"Rail Fence cipher — letters are written in a zigzag pattern.", hint2:"This uses 3 rails. Write the ciphertext diagonally then read across.", hint3:"Number of rails: 3" },
  { id:"c221", cipher:"Monoalphabetic", difficulty:"Hard",
    plaintext:"HELLO WORLD", ciphertext:"ITSSG VGKSR", keyInfo:"Q=A, W=B, E=C...",
    hint1:"Monoalphabetic substitution — each letter maps to a unique other letter.", hint2:"Use frequency analysis: E, T, A are the most common English letters.", hint3:"Substitution key: Q=A, W=B, E=C, R=D, T=E, Y=F ..." },
  { id:"c222", cipher:"Monoalphabetic", difficulty:"Hard",
    plaintext:"CRYPTO CODE", ciphertext:"EKNHZG EGRT", keyInfo:"Q=A, W=B, E=C...",
    hint1:"Monoalphabetic substitution — each letter maps to a unique other letter.", hint2:"Use frequency analysis: E, T, A are the most common English letters.", hint3:"Substitution key: Q=A, W=B, E=C, R=D, T=E, Y=F ..." },
  { id:"c223", cipher:"Monoalphabetic", difficulty:"Hard",
    plaintext:"SECRET KEY", ciphertext:"LTEKTZ ATN", keyInfo:"Q=A, W=B, E=C...",
    hint1:"Monoalphabetic substitution — each letter maps to a unique other letter.", hint2:"Use frequency analysis: E, T, A are the most common English letters.", hint3:"Substitution key: Q=A, W=B, E=C, R=D, T=E, Y=F ..." },
  { id:"c224", cipher:"Monoalphabetic", difficulty:"Hard",
    plaintext:"OPEN LOCK", ciphertext:"GHTF SGEA", keyInfo:"Q=A, W=B, E=C...",
    hint1:"Monoalphabetic substitution — each letter maps to a unique other letter.", hint2:"Use frequency analysis: E, T, A are the most common English letters.", hint3:"Substitution key: Q=A, W=B, E=C, R=D, T=E, Y=F ..." },
  { id:"c225", cipher:"Monoalphabetic", difficulty:"Hard",
    plaintext:"FIND EXIT", ciphertext:"YOFR TBOZ", keyInfo:"Q=A, W=B, E=C...",
    hint1:"Monoalphabetic substitution — each letter maps to a unique other letter.", hint2:"Use frequency analysis: E, T, A are the most common English letters.", hint3:"Substitution key: Q=A, W=B, E=C, R=D, T=E, Y=F ..." },
  { id:"c226", cipher:"Monoalphabetic", difficulty:"Hard",
    plaintext:"BREAK FREE", ciphertext:"WKTQA YKTT", keyInfo:"Q=A, W=B, E=C...",
    hint1:"Monoalphabetic substitution — each letter maps to a unique other letter.", hint2:"Use frequency analysis: E, T, A are the most common English letters.", hint3:"Substitution key: Q=A, W=B, E=C, R=D, T=E, Y=F ..." },
  { id:"c227", cipher:"Monoalphabetic", difficulty:"Hard",
    plaintext:"DARK FORCE", ciphertext:"RQKA YGKET", keyInfo:"Q=A, W=B, E=C...",
    hint1:"Monoalphabetic substitution — each letter maps to a unique other letter.", hint2:"Use frequency analysis: E, T, A are the most common English letters.", hint3:"Substitution key: Q=A, W=B, E=C, R=D, T=E, Y=F ..." },
  { id:"c228", cipher:"Monoalphabetic", difficulty:"Hard",
    plaintext:"LIGHT BEAM", ciphertext:"SOUIZ WTQD", keyInfo:"Q=A, W=B, E=C...",
    hint1:"Monoalphabetic substitution — each letter maps to a unique other letter.", hint2:"Use frequency analysis: E, T, A are the most common English letters.", hint3:"Substitution key: Q=A, W=B, E=C, R=D, T=E, Y=F ..." },
  { id:"c229", cipher:"Monoalphabetic", difficulty:"Hard",
    plaintext:"FAST TRACK", ciphertext:"YQLZ ZKQEA", keyInfo:"Q=A, W=B, E=C...",
    hint1:"Monoalphabetic substitution — each letter maps to a unique other letter.", hint2:"Use frequency analysis: E, T, A are the most common English letters.", hint3:"Substitution key: Q=A, W=B, E=C, R=D, T=E, Y=F ..." },
  { id:"c230", cipher:"Monoalphabetic", difficulty:"Hard",
    plaintext:"CODE ZERO", ciphertext:"EGRT MTKG", keyInfo:"Q=A, W=B, E=C...",
    hint1:"Monoalphabetic substitution — each letter maps to a unique other letter.", hint2:"Use frequency analysis: E, T, A are the most common English letters.", hint3:"Substitution key: Q=A, W=B, E=C, R=D, T=E, Y=F ..." },
  { id:"c231", cipher:"Monoalphabetic", difficulty:"Hard",
    plaintext:"THE CIPHER", ciphertext:"ZIT EOHITK", keyInfo:"Q=A, W=B, E=C...",
    hint1:"Monoalphabetic substitution — each letter maps to a unique other letter.", hint2:"Use frequency analysis: E, T, A are the most common English letters.", hint3:"Substitution key: Q=A, W=B, E=C, R=D, T=E, Y=F ..." },
  { id:"c232", cipher:"Monoalphabetic", difficulty:"Hard",
    plaintext:"KEY MASTER", ciphertext:"ATN DQLZTK", keyInfo:"Q=A, W=B, E=C...",
    hint1:"Monoalphabetic substitution — each letter maps to a unique other letter.", hint2:"Use frequency analysis: E, T, A are the most common English letters.", hint3:"Substitution key: Q=A, W=B, E=C, R=D, T=E, Y=F ..." },
  { id:"c233", cipher:"Monoalphabetic", difficulty:"Hard",
    plaintext:"DARK NIGHT", ciphertext:"RQKA FOUIZ", keyInfo:"Q=A, W=B, E=C...",
    hint1:"Monoalphabetic substitution — each letter maps to a unique other letter.", hint2:"Use frequency analysis: E, T, A are the most common English letters.", hint3:"Substitution key: Q=A, W=B, E=C, R=D, T=E, Y=F ..." },
  { id:"c234", cipher:"Monoalphabetic", difficulty:"Hard",
    plaintext:"FIRE STORM", ciphertext:"YOKT LZGKD", keyInfo:"Q=A, W=B, E=C...",
    hint1:"Monoalphabetic substitution — each letter maps to a unique other letter.", hint2:"Use frequency analysis: E, T, A are the most common English letters.", hint3:"Substitution key: Q=A, W=B, E=C, R=D, T=E, Y=F ..." },
  { id:"c235", cipher:"Monoalphabetic", difficulty:"Hard",
    plaintext:"COLD FRONT", ciphertext:"EGSR YKGFZ", keyInfo:"Q=A, W=B, E=C...",
    hint1:"Monoalphabetic substitution — each letter maps to a unique other letter.", hint2:"Use frequency analysis: E, T, A are the most common English letters.", hint3:"Substitution key: Q=A, W=B, E=C, R=D, T=E, Y=F ..." },
  { id:"c236", cipher:"Monoalphabetic", difficulty:"Hard",
    plaintext:"BLUE ALERT", ciphertext:"WSXT QSTKZ", keyInfo:"Q=A, W=B, E=C...",
    hint1:"Monoalphabetic substitution — each letter maps to a unique other letter.", hint2:"Use frequency analysis: E, T, A are the most common English letters.", hint3:"Substitution key: Q=A, W=B, E=C, R=D, T=E, Y=F ..." },
  { id:"c237", cipher:"Monoalphabetic", difficulty:"Hard",
    plaintext:"RED SIGNAL", ciphertext:"KTR LOUFQS", keyInfo:"Q=A, W=B, E=C...",
    hint1:"Monoalphabetic substitution — each letter maps to a unique other letter.", hint2:"Use frequency analysis: E, T, A are the most common English letters.", hint3:"Substitution key: Q=A, W=B, E=C, R=D, T=E, Y=F ..." },
  { id:"c238", cipher:"Monoalphabetic", difficulty:"Hard",
    plaintext:"NIGHT HAWK", ciphertext:"FOUIZ IQVA", keyInfo:"Q=A, W=B, E=C...",
    hint1:"Monoalphabetic substitution — each letter maps to a unique other letter.", hint2:"Use frequency analysis: E, T, A are the most common English letters.", hint3:"Substitution key: Q=A, W=B, E=C, R=D, T=E, Y=F ..." },
  { id:"c239", cipher:"Monoalphabetic", difficulty:"Hard",
    plaintext:"STORM BIRD", ciphertext:"LZGKD WOKR", keyInfo:"Q=A, W=B, E=C...",
    hint1:"Monoalphabetic substitution — each letter maps to a unique other letter.", hint2:"Use frequency analysis: E, T, A are the most common English letters.", hint3:"Substitution key: Q=A, W=B, E=C, R=D, T=E, Y=F ..." },
  { id:"c240", cipher:"Monoalphabetic", difficulty:"Hard",
    plaintext:"IRON GATE", ciphertext:"OKGF UQZT", keyInfo:"Q=A, W=B, E=C...",
    hint1:"Monoalphabetic substitution — each letter maps to a unique other letter.", hint2:"Use frequency analysis: E, T, A are the most common English letters.", hint3:"Substitution key: Q=A, W=B, E=C, R=D, T=E, Y=F ..." },
  { id:"c241", cipher:"Monoalphabetic", difficulty:"Hard",
    plaintext:"SHADOW MOVE", ciphertext:"LIQRGV DGCT", keyInfo:"Q=A, W=B, E=C...",
    hint1:"Monoalphabetic substitution — each letter maps to a unique other letter.", hint2:"Use frequency analysis: E, T, A are the most common English letters.", hint3:"Substitution key: Q=A, W=B, E=C, R=D, T=E, Y=F ..." },
  { id:"c242", cipher:"Monoalphabetic", difficulty:"Hard",
    plaintext:"GHOST LINE", ciphertext:"UIGLZ SOFT", keyInfo:"Q=A, W=B, E=C...",
    hint1:"Monoalphabetic substitution — each letter maps to a unique other letter.", hint2:"Use frequency analysis: E, T, A are the most common English letters.", hint3:"Substitution key: Q=A, W=B, E=C, R=D, T=E, Y=F ..." },
  { id:"c243", cipher:"Monoalphabetic", difficulty:"Hard",
    plaintext:"WAVE RIDER", ciphertext:"VQCT KORTK", keyInfo:"Q=A, W=B, E=C...",
    hint1:"Monoalphabetic substitution — each letter maps to a unique other letter.", hint2:"Use frequency analysis: E, T, A are the most common English letters.", hint3:"Substitution key: Q=A, W=B, E=C, R=D, T=E, Y=F ..." },
  { id:"c244", cipher:"Monoalphabetic", difficulty:"Hard",
    plaintext:"STAR FIELD", ciphertext:"LZQK YOTSR", keyInfo:"Q=A, W=B, E=C...",
    hint1:"Monoalphabetic substitution — each letter maps to a unique other letter.", hint2:"Use frequency analysis: E, T, A are the most common English letters.", hint3:"Substitution key: Q=A, W=B, E=C, R=D, T=E, Y=F ..." },
  { id:"c245", cipher:"Monoalphabetic", difficulty:"Hard",
    plaintext:"DARK ZONE", ciphertext:"RQKA MGFT", keyInfo:"Q=A, W=B, E=C...",
    hint1:"Monoalphabetic substitution — each letter maps to a unique other letter.", hint2:"Use frequency analysis: E, T, A are the most common English letters.", hint3:"Substitution key: Q=A, W=B, E=C, R=D, T=E, Y=F ..." },
  { id:"c246", cipher:"Monoalphabetic", difficulty:"Hard",
    plaintext:"FIRE EAGLE", ciphertext:"YOKT TQUST", keyInfo:"Q=A, W=B, E=C...",
    hint1:"Monoalphabetic substitution — each letter maps to a unique other letter.", hint2:"Use frequency analysis: E, T, A are the most common English letters.", hint3:"Substitution key: Q=A, W=B, E=C, R=D, T=E, Y=F ..." },
  { id:"c247", cipher:"Monoalphabetic", difficulty:"Hard",
    plaintext:"COLD STEEL", ciphertext:"EGSR LZTTS", keyInfo:"Q=A, W=B, E=C...",
    hint1:"Monoalphabetic substitution — each letter maps to a unique other letter.", hint2:"Use frequency analysis: E, T, A are the most common English letters.", hint3:"Substitution key: Q=A, W=B, E=C, R=D, T=E, Y=F ..." },
  { id:"c248", cipher:"Monoalphabetic", difficulty:"Hard",
    plaintext:"BLUE FLAME", ciphertext:"WSXT YSQDT", keyInfo:"Q=A, W=B, E=C...",
    hint1:"Monoalphabetic substitution — each letter maps to a unique other letter.", hint2:"Use frequency analysis: E, T, A are the most common English letters.", hint3:"Substitution key: Q=A, W=B, E=C, R=D, T=E, Y=F ..." },
  { id:"c249", cipher:"Monoalphabetic", difficulty:"Hard",
    plaintext:"RED ARROW", ciphertext:"KTR QKKGV", keyInfo:"Q=A, W=B, E=C...",
    hint1:"Monoalphabetic substitution — each letter maps to a unique other letter.", hint2:"Use frequency analysis: E, T, A are the most common English letters.", hint3:"Substitution key: Q=A, W=B, E=C, R=D, T=E, Y=F ..." },
  { id:"c250", cipher:"Monoalphabetic", difficulty:"Hard",
    plaintext:"NIGHT RAID", ciphertext:"FOUIZ KQOR", keyInfo:"Q=A, W=B, E=C...",
    hint1:"Monoalphabetic substitution — each letter maps to a unique other letter.", hint2:"Use frequency analysis: E, T, A are the most common English letters.", hint3:"Substitution key: Q=A, W=B, E=C, R=D, T=E, Y=F ..." },
]