// ─── Contest Puzzle Bank — 200 puzzles ─────────────────────────────────────
// lib/puzzles-contest.ts

export interface Puzzle {
  id: string; cipher: string; plaintext: string; ciphertext: string
  hints: string[]; difficulty: "Easy" | "Medium" | "Hard"; keyInfo: string; points: number
}

export const CONTEST_PUZZLES: Puzzle[] = [
  { id:"d1", cipher:"Caesar", difficulty:"Easy", points:100,
    keyInfo:"Shift: 1",
    plaintext:"HELLO WORLD",
    ciphertext:"IFMMP XPSME",
    hints:["Caesar cipher: shift each letter by 1", "A → B, B → C", "Decrypt: subtract 1 from each letter's position"] },
  { id:"d2", cipher:"Caesar", difficulty:"Easy", points:100,
    keyInfo:"Shift: 2",
    plaintext:"MEET ME AT NOON",
    ciphertext:"OGGV OG CV PQQP",
    hints:["Caesar cipher: shift each letter by 2", "A → C, B → D", "Decrypt: subtract 2 from each letter's position"] },
  { id:"d3", cipher:"Caesar", difficulty:"Easy", points:100,
    keyInfo:"Shift: 3",
    plaintext:"KEEP IT SECRET",
    ciphertext:"NHHS LW VHFUHW",
    hints:["Caesar cipher: shift each letter by 3", "A → D, B → E", "Decrypt: subtract 3 from each letter's position"] },
  { id:"d4", cipher:"Caesar", difficulty:"Easy", points:100,
    keyInfo:"Shift: 4",
    plaintext:"THE EAGLE FLIES",
    ciphertext:"XLI IEKPI JPMIW",
    hints:["Caesar cipher: shift each letter by 4", "A → E, B → F", "Decrypt: subtract 4 from each letter's position"] },
  { id:"d5", cipher:"Caesar", difficulty:"Easy", points:100,
    keyInfo:"Shift: 5",
    plaintext:"CODE IS ART",
    ciphertext:"HTIJ NX FWY",
    hints:["Caesar cipher: shift each letter by 5", "A → F, B → G", "Decrypt: subtract 5 from each letter's position"] },
  { id:"d6", cipher:"Caesar", difficulty:"Easy", points:100,
    keyInfo:"Shift: 6",
    plaintext:"SEEK AND FIND",
    ciphertext:"YKKQ GTJ LOTJ",
    hints:["Caesar cipher: shift each letter by 6", "A → G, B → H", "Decrypt: subtract 6 from each letter's position"] },
  { id:"d7", cipher:"Caesar", difficulty:"Easy", points:100,
    keyInfo:"Shift: 7",
    plaintext:"OPEN THE GATE",
    ciphertext:"VWLU AOL NHAL",
    hints:["Caesar cipher: shift each letter by 7", "A → H, B → I", "Decrypt: subtract 7 from each letter's position"] },
  { id:"d8", cipher:"Caesar", difficulty:"Easy", points:100,
    keyInfo:"Shift: 8",
    plaintext:"TIME IS NOW",
    ciphertext:"BQUM QA VWE",
    hints:["Caesar cipher: shift each letter by 8", "A → I, B → J", "Decrypt: subtract 8 from each letter's position"] },
  { id:"d9", cipher:"Caesar", difficulty:"Easy", points:100,
    keyInfo:"Shift: 9",
    plaintext:"BREAK THE CODE",
    ciphertext:"KANJT CQN LXMN",
    hints:["Caesar cipher: shift each letter by 9", "A → J, B → K", "Decrypt: subtract 9 from each letter's position"] },
  { id:"d10", cipher:"Caesar", difficulty:"Easy", points:100,
    keyInfo:"Shift: 1",
    plaintext:"FIND THE KEY",
    ciphertext:"GJOE UIF LFZ",
    hints:["Caesar cipher: shift each letter by 1", "A → B, B → C", "Decrypt: subtract 1 from each letter's position"] },
  { id:"d11", cipher:"Caesar", difficulty:"Easy", points:100,
    keyInfo:"Shift: 2",
    plaintext:"LIGHT THE WAY",
    ciphertext:"NKIJV VJG YCA",
    hints:["Caesar cipher: shift each letter by 2", "A → C, B → D", "Decrypt: subtract 2 from each letter's position"] },
  { id:"d12", cipher:"Caesar", difficulty:"Easy", points:100,
    keyInfo:"Shift: 3",
    plaintext:"HOLD THE LINE",
    ciphertext:"KROG WKH OLQH",
    hints:["Caesar cipher: shift each letter by 3", "A → D, B → E", "Decrypt: subtract 3 from each letter's position"] },
  { id:"d13", cipher:"Caesar", difficulty:"Easy", points:100,
    keyInfo:"Shift: 4",
    plaintext:"MARCH TO VICTORY",
    ciphertext:"QEVGL XS ZMGXSVC",
    hints:["Caesar cipher: shift each letter by 4", "A → E, B → F", "Decrypt: subtract 4 from each letter's position"] },
  { id:"d14", cipher:"Caesar", difficulty:"Easy", points:100,
    keyInfo:"Shift: 5",
    plaintext:"THE SUN RISES",
    ciphertext:"YMJ XZS WNXJX",
    hints:["Caesar cipher: shift each letter by 5", "A → F, B → G", "Decrypt: subtract 5 from each letter's position"] },
  { id:"d15", cipher:"Caesar", difficulty:"Easy", points:100,
    keyInfo:"Shift: 6",
    plaintext:"SEND THE SIGNAL",
    ciphertext:"YKTJ ZNK YOMTGR",
    hints:["Caesar cipher: shift each letter by 6", "A → G, B → H", "Decrypt: subtract 6 from each letter's position"] },
  { id:"d16", cipher:"Caesar", difficulty:"Easy", points:100,
    keyInfo:"Shift: 7",
    plaintext:"GUARD THE DOOR",
    ciphertext:"NBHYK AOL KVVY",
    hints:["Caesar cipher: shift each letter by 7", "A → H, B → I", "Decrypt: subtract 7 from each letter's position"] },
  { id:"d17", cipher:"Caesar", difficulty:"Easy", points:100,
    keyInfo:"Shift: 8",
    plaintext:"READ THE MAP",
    ciphertext:"ZMIL BPM UIX",
    hints:["Caesar cipher: shift each letter by 8", "A → I, B → J", "Decrypt: subtract 8 from each letter's position"] },
  { id:"d18", cipher:"Caesar", difficulty:"Easy", points:100,
    keyInfo:"Shift: 9",
    plaintext:"CROSS THE RIVER",
    ciphertext:"LAXBB CQN ARENA",
    hints:["Caesar cipher: shift each letter by 9", "A → J, B → K", "Decrypt: subtract 9 from each letter's position"] },
  { id:"d19", cipher:"Caesar", difficulty:"Easy", points:100,
    keyInfo:"Shift: 1",
    plaintext:"FOLLOW THE PATH",
    ciphertext:"GPMMPX UIF QBUI",
    hints:["Caesar cipher: shift each letter by 1", "A → B, B → C", "Decrypt: subtract 1 from each letter's position"] },
  { id:"d20", cipher:"Caesar", difficulty:"Easy", points:100,
    keyInfo:"Shift: 2",
    plaintext:"RING THE BELL",
    ciphertext:"TKPI VJG DGNN",
    hints:["Caesar cipher: shift each letter by 2", "A → C, B → D", "Decrypt: subtract 2 from each letter's position"] },
  { id:"d21", cipher:"Caesar", difficulty:"Easy", points:100,
    keyInfo:"Shift: 3",
    plaintext:"LOCK THE VAULT",
    ciphertext:"ORFN WKH YDXOW",
    hints:["Caesar cipher: shift each letter by 3", "A → D, B → E", "Decrypt: subtract 3 from each letter's position"] },
  { id:"d22", cipher:"Caesar", difficulty:"Easy", points:100,
    keyInfo:"Shift: 4",
    plaintext:"TURN THE PAGE",
    ciphertext:"XYVR XLI TEKI",
    hints:["Caesar cipher: shift each letter by 4", "A → E, B → F", "Decrypt: subtract 4 from each letter's position"] },
  { id:"d23", cipher:"Caesar", difficulty:"Easy", points:100,
    keyInfo:"Shift: 5",
    plaintext:"FACE THE TRUTH",
    ciphertext:"KFHJ YMJ YWZYM",
    hints:["Caesar cipher: shift each letter by 5", "A → F, B → G", "Decrypt: subtract 5 from each letter's position"] },
  { id:"d24", cipher:"Caesar", difficulty:"Easy", points:100,
    keyInfo:"Shift: 6",
    plaintext:"CARRY THE FLAG",
    ciphertext:"IGXXE ZNK LRGM",
    hints:["Caesar cipher: shift each letter by 6", "A → G, B → H", "Decrypt: subtract 6 from each letter's position"] },
  { id:"d25", cipher:"Caesar", difficulty:"Easy", points:100,
    keyInfo:"Shift: 7",
    plaintext:"MOVE IN SILENCE",
    ciphertext:"TVCL PU ZPSLUJL",
    hints:["Caesar cipher: shift each letter by 7", "A → H, B → I", "Decrypt: subtract 7 from each letter's position"] },
  { id:"d26", cipher:"Caesar", difficulty:"Easy", points:100,
    keyInfo:"Shift: 8",
    plaintext:"TRUST YOUR EYES",
    ciphertext:"BZCAB GWCZ MGMA",
    hints:["Caesar cipher: shift each letter by 8", "A → I, B → J", "Decrypt: subtract 8 from each letter's position"] },
  { id:"d27", cipher:"Caesar", difficulty:"Easy", points:100,
    keyInfo:"Shift: 9",
    plaintext:"STAND YOUR GROUND",
    ciphertext:"BCJWM HXDA PAXDWM",
    hints:["Caesar cipher: shift each letter by 9", "A → J, B → K", "Decrypt: subtract 9 from each letter's position"] },
  { id:"d28", cipher:"Caesar", difficulty:"Easy", points:100,
    keyInfo:"Shift: 1",
    plaintext:"JOIN THE CAUSE",
    ciphertext:"KPJO UIF DBVTF",
    hints:["Caesar cipher: shift each letter by 1", "A → B, B → C", "Decrypt: subtract 1 from each letter's position"] },
  { id:"d29", cipher:"Caesar", difficulty:"Easy", points:100,
    keyInfo:"Shift: 2",
    plaintext:"LEAVE NO TRACE",
    ciphertext:"NGCXG PQ VTCEG",
    hints:["Caesar cipher: shift each letter by 2", "A → C, B → D", "Decrypt: subtract 2 from each letter's position"] },
  { id:"d30", cipher:"Caesar", difficulty:"Easy", points:100,
    keyInfo:"Shift: 3",
    plaintext:"ENTER THE CAVE",
    ciphertext:"HQWHU WKH FDYH",
    hints:["Caesar cipher: shift each letter by 3", "A → D, B → E", "Decrypt: subtract 3 from each letter's position"] },
  { id:"d31", cipher:"Caesar", difficulty:"Medium", points:200,
    keyInfo:"Shift: 10",
    plaintext:"DEFEND THE CASTLE",
    ciphertext:"NOPOXN DRO MKCDVO",
    hints:["Caesar cipher with a larger shift", "Shift value is between 10 and 20", "Shift: 10"] },
  { id:"d32", cipher:"Caesar", difficulty:"Medium", points:200,
    keyInfo:"Shift: 11",
    plaintext:"SOUND THE ALARM",
    ciphertext:"DZFYO ESP LWLCX",
    hints:["Caesar cipher with a larger shift", "Shift value is between 10 and 20", "Shift: 11"] },
  { id:"d33", cipher:"Caesar", difficulty:"Medium", points:200,
    keyInfo:"Shift: 12",
    plaintext:"TRUST NO ONE",
    ciphertext:"FDGEF ZA AZQ",
    hints:["Caesar cipher with a larger shift", "Shift value is between 10 and 20", "Shift: 12"] },
  { id:"d34", cipher:"Caesar", difficulty:"Medium", points:200,
    keyInfo:"Shift: 13",
    plaintext:"THE QUICK BROWN FOX",
    ciphertext:"GUR DHVPX OEBJA SBK",
    hints:["Caesar cipher with a larger shift", "Shift value is between 10 and 20", "Shift: 13"] },
  { id:"d35", cipher:"Caesar", difficulty:"Medium", points:200,
    keyInfo:"Shift: 14",
    plaintext:"MIDNIGHT RENDEZVOUS",
    ciphertext:"AWRBWUVH FSBRSNJCIG",
    hints:["Caesar cipher with a larger shift", "Shift value is between 10 and 20", "Shift: 14"] },
  { id:"d36", cipher:"Caesar", difficulty:"Medium", points:200,
    keyInfo:"Shift: 15",
    plaintext:"OPERATION SUNRISE",
    ciphertext:"DETGPIXDC HJCGXHT",
    hints:["Caesar cipher with a larger shift", "Shift value is between 10 and 20", "Shift: 15"] },
  { id:"d37", cipher:"Caesar", difficulty:"Medium", points:200,
    keyInfo:"Shift: 16",
    plaintext:"DESTROY THE EVIDENCE",
    ciphertext:"TUIJHEO JXU ULYTUDSU",
    hints:["Caesar cipher with a larger shift", "Shift value is between 10 and 20", "Shift: 16"] },
  { id:"d38", cipher:"Caesar", difficulty:"Medium", points:200,
    keyInfo:"Shift: 17",
    plaintext:"RALLY THE TROOPS",
    ciphertext:"IRCCP KYV KIFFGJ",
    hints:["Caesar cipher with a larger shift", "Shift value is between 10 and 20", "Shift: 17"] },
  { id:"d39", cipher:"Caesar", difficulty:"Medium", points:200,
    keyInfo:"Shift: 18",
    plaintext:"SILENCE IS GOLDEN",
    ciphertext:"KADWFUW AK YGDVWF",
    hints:["Caesar cipher with a larger shift", "Shift value is between 10 and 20", "Shift: 18"] },
  { id:"d40", cipher:"Caesar", difficulty:"Medium", points:200,
    keyInfo:"Shift: 19",
    plaintext:"VICTORY OR DEATH",
    ciphertext:"OBVMHKR HK WXTMA",
    hints:["Caesar cipher with a larger shift", "Shift value is between 10 and 20", "Shift: 19"] },
  { id:"d41", cipher:"Caesar", difficulty:"Medium", points:200,
    keyInfo:"Shift: 20",
    plaintext:"THE WALLS HAVE EARS",
    ciphertext:"NBY QUFFM BUPY YULM",
    hints:["Caesar cipher with a larger shift", "Shift value is between 10 and 20", "Shift: 20"] },
  { id:"d42", cipher:"Caesar", difficulty:"Medium", points:200,
    keyInfo:"Shift: 10",
    plaintext:"ABANDON SHIP NOW",
    ciphertext:"KLKXNYX CRSZ XYG",
    hints:["Caesar cipher with a larger shift", "Shift value is between 10 and 20", "Shift: 10"] },
  { id:"d43", cipher:"Caesar", difficulty:"Medium", points:200,
    keyInfo:"Shift: 11",
    plaintext:"THE CODE IS BROKEN",
    ciphertext:"ESP NZOP TD MCZVPY",
    hints:["Caesar cipher with a larger shift", "Shift value is between 10 and 20", "Shift: 11"] },
  { id:"d44", cipher:"Caesar", difficulty:"Medium", points:200,
    keyInfo:"Shift: 12",
    plaintext:"BURN THE LETTER",
    ciphertext:"NGDZ FTQ XQFFQD",
    hints:["Caesar cipher with a larger shift", "Shift value is between 10 and 20", "Shift: 12"] },
  { id:"d45", cipher:"Caesar", difficulty:"Medium", points:200,
    keyInfo:"Shift: 13",
    plaintext:"FORGE THE ALLIANCE",
    ciphertext:"SBETR GUR NYYVNAPR",
    hints:["Caesar cipher with a larger shift", "Shift value is between 10 and 20", "Shift: 13"] },
  { id:"d46", cipher:"Caesar", difficulty:"Medium", points:200,
    keyInfo:"Shift: 14",
    plaintext:"BESIEGE THE TOWER",
    ciphertext:"PSGWSUS HVS HCKSF",
    hints:["Caesar cipher with a larger shift", "Shift value is between 10 and 20", "Shift: 14"] },
  { id:"d47", cipher:"Caesar", difficulty:"Medium", points:200,
    keyInfo:"Shift: 15",
    plaintext:"SCATTER THE ASHES",
    ciphertext:"HRPIITG IWT PHWTH",
    hints:["Caesar cipher with a larger shift", "Shift value is between 10 and 20", "Shift: 15"] },
  { id:"d48", cipher:"Caesar", difficulty:"Medium", points:200,
    keyInfo:"Shift: 16",
    plaintext:"THE TIDE HAS TURNED",
    ciphertext:"JXU JYTU XQI JKHDUT",
    hints:["Caesar cipher with a larger shift", "Shift value is between 10 and 20", "Shift: 16"] },
  { id:"d49", cipher:"Caesar", difficulty:"Medium", points:200,
    keyInfo:"Shift: 17",
    plaintext:"SHADOWS AND LIGHT",
    ciphertext:"JYRUFNJ REU CZXYK",
    hints:["Caesar cipher with a larger shift", "Shift value is between 10 and 20", "Shift: 17"] },
  { id:"d50", cipher:"Caesar", difficulty:"Medium", points:200,
    keyInfo:"Shift: 18",
    plaintext:"WINTER APPROACHES",
    ciphertext:"OAFLWJ SHHJGSUZWK",
    hints:["Caesar cipher with a larger shift", "Shift value is between 10 and 20", "Shift: 18"] },
  { id:"d51", cipher:"Caesar", difficulty:"Medium", points:200,
    keyInfo:"Shift: 19",
    plaintext:"THE FINAL CIPHER",
    ciphertext:"MAX YBGTE VBIAXK",
    hints:["Caesar cipher with a larger shift", "Shift value is between 10 and 20", "Shift: 19"] },
  { id:"d52", cipher:"Caesar", difficulty:"Medium", points:200,
    keyInfo:"Shift: 20",
    plaintext:"UNLOCK THE ARCHIVE",
    ciphertext:"OHFIWE NBY ULWBCPY",
    hints:["Caesar cipher with a larger shift", "Shift value is between 10 and 20", "Shift: 20"] },
  { id:"d53", cipher:"Caesar", difficulty:"Medium", points:200,
    keyInfo:"Shift: 10",
    plaintext:"ADVANCE AT MIDNIGHT",
    ciphertext:"KNFKXMO KD WSNXSQRD",
    hints:["Caesar cipher with a larger shift", "Shift value is between 10 and 20", "Shift: 10"] },
  { id:"d54", cipher:"Caesar", difficulty:"Medium", points:200,
    keyInfo:"Shift: 11",
    plaintext:"RETREAT TO BASE",
    ciphertext:"CPECPLE EZ MLDP",
    hints:["Caesar cipher with a larger shift", "Shift value is between 10 and 20", "Shift: 11"] },
  { id:"d55", cipher:"Caesar", difficulty:"Medium", points:200,
    keyInfo:"Shift: 12",
    plaintext:"THE PASSWORD IS DELTA",
    ciphertext:"FTQ BMEEIADP UE PQXFM",
    hints:["Caesar cipher with a larger shift", "Shift value is between 10 and 20", "Shift: 12"] },
  { id:"d56", cipher:"Caesar", difficulty:"Hard", points:300,
    keyInfo:"Shift: 15",
    plaintext:"THE CRYPTANALYST DECIPHERS ALL",
    ciphertext:"IWT RGNEIPCPANHI STRXEWTGH PAA",
    hints:["Caesar cipher — try frequency analysis", "Most common letter in ciphertext maps to E", "Shift: 15"] },
  { id:"d57", cipher:"Caesar", difficulty:"Hard", points:300,
    keyInfo:"Shift: 16",
    plaintext:"KNOWLEDGE IS THE GREATEST WEAPON",
    ciphertext:"ADEMBUTWU YI JXU WHUQJUIJ MUQFED",
    hints:["Caesar cipher — try frequency analysis", "Most common letter in ciphertext maps to E", "Shift: 16"] },
  { id:"d58", cipher:"Caesar", difficulty:"Hard", points:300,
    keyInfo:"Shift: 17",
    plaintext:"IN THE REALM OF SECRETS ALL IS CIPHER",
    ciphertext:"ZE KYV IVRCD FW JVTIVKJ RCC ZJ TZGYVI",
    hints:["Caesar cipher — try frequency analysis", "Most common letter in ciphertext maps to E", "Shift: 17"] },
  { id:"d59", cipher:"Caesar", difficulty:"Hard", points:300,
    keyInfo:"Shift: 18",
    plaintext:"MATHEMATICS UNDERLIES ALL ENCRYPTION",
    ciphertext:"ESLZWESLAUK MFVWJDAWK SDD WFUJQHLAGF",
    hints:["Caesar cipher — try frequency analysis", "Most common letter in ciphertext maps to E", "Shift: 18"] },
  { id:"d60", cipher:"Caesar", difficulty:"Hard", points:300,
    keyInfo:"Shift: 19",
    plaintext:"THE PERFECT CODE HAS NEVER BEEN WRITTEN",
    ciphertext:"MAX IXKYXVM VHWX ATL GXOXK UXXG PKBMMXG",
    hints:["Caesar cipher — try frequency analysis", "Most common letter in ciphertext maps to E", "Shift: 19"] },
  { id:"d61", cipher:"Caesar", difficulty:"Hard", points:300,
    keyInfo:"Shift: 20",
    plaintext:"ENTROPY DEFINES THE STRENGTH OF A KEY",
    ciphertext:"YHNLIJS XYZCHYM NBY MNLYHANB IZ U EYS",
    hints:["Caesar cipher — try frequency analysis", "Most common letter in ciphertext maps to E", "Shift: 20"] },
  { id:"d62", cipher:"Caesar", difficulty:"Hard", points:300,
    keyInfo:"Shift: 21",
    plaintext:"EVERY CIPHER FALLS TO A PERSISTENT MIND",
    ciphertext:"ZQZMT XDKCZM AVGGN OJ V KZMNDNOZIO HDIY",
    hints:["Caesar cipher — try frequency analysis", "Most common letter in ciphertext maps to E", "Shift: 21"] },
  { id:"d63", cipher:"Caesar", difficulty:"Hard", points:300,
    keyInfo:"Shift: 22",
    plaintext:"SECURITY THROUGH OBSCURITY IS NO SECURITY",
    ciphertext:"OAYQNEPU PDNKQCD KXOYQNEPU EO JK OAYQNEPU",
    hints:["Caesar cipher — try frequency analysis", "Most common letter in ciphertext maps to E", "Shift: 22"] },
  { id:"d64", cipher:"Caesar", difficulty:"Hard", points:300,
    keyInfo:"Shift: 23",
    plaintext:"THE KEY LIES WITHIN THE PATTERN OF LETTERS",
    ciphertext:"QEB HBV IFBP TFQEFK QEB MXQQBOK LC IBQQBOP",
    hints:["Caesar cipher — try frequency analysis", "Most common letter in ciphertext maps to E", "Shift: 23"] },
  { id:"d65", cipher:"Caesar", difficulty:"Hard", points:300,
    keyInfo:"Shift: 24",
    plaintext:"FREQUENCY ANALYSIS BREAKS SIMPLE CIPHERS",
    ciphertext:"DPCOSCLAW YLYJWQGQ ZPCYIQ QGKNJC AGNFCPQ",
    hints:["Caesar cipher — try frequency analysis", "Most common letter in ciphertext maps to E", "Shift: 24"] },
  { id:"d66", cipher:"Caesar", difficulty:"Hard", points:300,
    keyInfo:"Shift: 25",
    plaintext:"A TRANSPOSITION REARRANGES BUT DOES NOT SUBSTITUTE",
    ciphertext:"Z SQZMRONRHSHNM QDZQQZMFDR ATS CNDR MNS RTARSHSTSD",
    hints:["Caesar cipher — try frequency analysis", "Most common letter in ciphertext maps to E", "Shift: 25"] },
  { id:"d67", cipher:"Caesar", difficulty:"Hard", points:300,
    keyInfo:"Shift: 15",
    plaintext:"THE VIGENERE RESISTED CENTURIES OF ATTACK",
    ciphertext:"IWT KXVTCTGT GTHXHITS RTCIJGXTH DU PIIPRZ",
    hints:["Caesar cipher — try frequency analysis", "Most common letter in ciphertext maps to E", "Shift: 15"] },
  { id:"d68", cipher:"Caesar", difficulty:"Hard", points:300,
    keyInfo:"Shift: 16",
    plaintext:"ENIGMA FELL TO THE BRILLIANT MINDS AT BLETCHLEY",
    ciphertext:"UDYWCQ VUBB JE JXU RHYBBYQDJ CYDTI QJ RBUJSXBUO",
    hints:["Caesar cipher — try frequency analysis", "Most common letter in ciphertext maps to E", "Shift: 16"] },
  { id:"d69", cipher:"Caesar", difficulty:"Hard", points:300,
    keyInfo:"Shift: 17",
    plaintext:"DIFFIE HELLMAN CHANGED CRYPTOGRAPHY FOREVER",
    ciphertext:"UZWWZV YVCCDRE TYREXVU TIPGKFXIRGYP WFIVMVI",
    hints:["Caesar cipher — try frequency analysis", "Most common letter in ciphertext maps to E", "Shift: 17"] },
  { id:"d70", cipher:"Caesar", difficulty:"Hard", points:300,
    keyInfo:"Shift: 18",
    plaintext:"ALAN TURING BROKE THE UNBREAKABLE CODE",
    ciphertext:"SDSF LMJAFY TJGCW LZW MFTJWSCSTDW UGVW",
    hints:["Caesar cipher — try frequency analysis", "Most common letter in ciphertext maps to E", "Shift: 18"] },
  { id:"d71", cipher:"Vigenère", difficulty:"Medium", points:250,
    keyInfo:"Key: LEMON",
    plaintext:"ATTACK AT DAWN",
    ciphertext:"LXFOPV EF RNHR",
    hints:["Vigenère cipher — repeating key", "Key length is 5 letters", "Key: LEMON"] },
  { id:"d72", cipher:"Vigenère", difficulty:"Medium", points:250,
    keyInfo:"Key: KEY",
    plaintext:"SEND HELP NOW",
    ciphertext:"CILN LCVT LYA",
    hints:["Vigenère cipher — repeating key", "Key length is 3 letters", "Key: KEY"] },
  { id:"d73", cipher:"Vigenère", difficulty:"Medium", points:250,
    keyInfo:"Key: BEAM",
    plaintext:"WINTER IS COMING",
    ciphertext:"XMNFFV IE DSMUOK",
    hints:["Vigenère cipher — repeating key", "Key length is 4 letters", "Key: BEAM"] },
  { id:"d74", cipher:"Vigenère", difficulty:"Medium", points:250,
    keyInfo:"Key: CAT",
    plaintext:"WE MOVE AT NIGHT",
    ciphertext:"YE FQVX CT GKGAV",
    hints:["Vigenère cipher — repeating key", "Key length is 3 letters", "Key: CAT"] },
  { id:"d75", cipher:"Vigenère", difficulty:"Medium", points:250,
    keyInfo:"Key: DOG",
    plaintext:"THE ENEMY ADVANCES",
    ciphertext:"WVK HBKPM GGJGQQKV",
    hints:["Vigenère cipher — repeating key", "Key length is 3 letters", "Key: DOG"] },
  { id:"d76", cipher:"Vigenère", difficulty:"Medium", points:250,
    keyInfo:"Key: SUN",
    plaintext:"SECURE THE PERIMETER",
    ciphertext:"KYPMLR LBR HYEAGRLYE",
    hints:["Vigenère cipher — repeating key", "Key length is 3 letters", "Key: SUN"] },
  { id:"d77", cipher:"Vigenère", difficulty:"Medium", points:250,
    keyInfo:"Key: ACE",
    plaintext:"BRING THE DOCUMENTS",
    ciphertext:"BTMNI XHG HOEYMGRTU",
    hints:["Vigenère cipher — repeating key", "Key length is 3 letters", "Key: ACE"] },
  { id:"d78", cipher:"Vigenère", difficulty:"Medium", points:250,
    keyInfo:"Key: ICE",
    plaintext:"MEET AT THE BRIDGE",
    ciphertext:"UGIB CX BJI JTMLII",
    hints:["Vigenère cipher — repeating key", "Key length is 3 letters", "Key: ICE"] },
  { id:"d79", cipher:"Vigenère", difficulty:"Medium", points:250,
    keyInfo:"Key: OAK",
    plaintext:"LAUNCH THE OPERATION",
    ciphertext:"ZAEBCR HHO CPOFADWOX",
    hints:["Vigenère cipher — repeating key", "Key length is 3 letters", "Key: OAK"] },
  { id:"d80", cipher:"Vigenère", difficulty:"Medium", points:250,
    keyInfo:"Key: FIG",
    plaintext:"HOLD YOUR POSITION",
    ciphertext:"MWRI GUZZ VTAOYQUS",
    hints:["Vigenère cipher — repeating key", "Key length is 3 letters", "Key: FIG"] },
  { id:"d81", cipher:"Vigenère", difficulty:"Medium", points:250,
    keyInfo:"Key: BAT",
    plaintext:"THE AGENT IS COMPROMISED",
    ciphertext:"UHX BGXOT BT CHNPKPMBTEW",
    hints:["Vigenère cipher — repeating key", "Key length is 3 letters", "Key: BAT"] },
  { id:"d82", cipher:"Vigenère", difficulty:"Medium", points:250,
    keyInfo:"Key: ZAP",
    plaintext:"CHANGE THE FREQUENCY",
    ciphertext:"BHPMGT SHT ERTPUTMCN",
    hints:["Vigenère cipher — repeating key", "Key length is 3 letters", "Key: ZAP"] },
  { id:"d83", cipher:"Vigenère", difficulty:"Medium", points:250,
    keyInfo:"Key: MAP",
    plaintext:"ABORT THE MISSION",
    ciphertext:"MBDDT ITE BUSHUOC",
    hints:["Vigenère cipher — repeating key", "Key length is 3 letters", "Key: MAP"] },
  { id:"d84", cipher:"Vigenère", difficulty:"Medium", points:250,
    keyInfo:"Key: NET",
    plaintext:"EXTRACT THE ASSET NOW",
    ciphertext:"RBMEEVG XAR ELFIM ASP",
    hints:["Vigenère cipher — repeating key", "Key length is 3 letters", "Key: NET"] },
  { id:"d85", cipher:"Vigenère", difficulty:"Medium", points:250,
    keyInfo:"Key: ORB",
    plaintext:"THE DROP IS TONIGHT",
    ciphertext:"HYF RIPD ZT HFOWXIH",
    hints:["Vigenère cipher — repeating key", "Key length is 3 letters", "Key: ORB"] },
  { id:"d86", cipher:"Vigenère", difficulty:"Medium", points:250,
    keyInfo:"Key: JAY",
    plaintext:"CONFIRM THE RENDEZVOUS",
    ciphertext:"LOLOIPV TFN RCWDCIVMDS",
    hints:["Vigenère cipher — repeating key", "Key length is 3 letters", "Key: JAY"] },
  { id:"d87", cipher:"Vigenère", difficulty:"Medium", points:250,
    keyInfo:"Key: DEN",
    plaintext:"SIGNAL RECEIVED AND UNDERSTOOD",
    ciphertext:"VMTQEY UIPHMIHH NQH HQHRUWGRSQ",
    hints:["Vigenère cipher — repeating key", "Key length is 3 letters", "Key: DEN"] },
  { id:"d88", cipher:"Vigenère", difficulty:"Medium", points:250,
    keyInfo:"Key: ARC",
    plaintext:"THE PACKAGE HAS ARRIVED",
    ciphertext:"TYG PREKRIE YCS RTRZXEU",
    hints:["Vigenère cipher — repeating key", "Key length is 3 letters", "Key: ARC"] },
  { id:"d89", cipher:"Vigenère", difficulty:"Medium", points:250,
    keyInfo:"Key: TAO",
    plaintext:"PROCEED WITH CAUTION TODAY",
    ciphertext:"IRCVESW WWMH QTUHBOB MORTY",
    hints:["Vigenère cipher — repeating key", "Key length is 3 letters", "Key: TAO"] },
  { id:"d90", cipher:"Vigenère", difficulty:"Medium", points:250,
    keyInfo:"Key: BEE",
    plaintext:"THE COAST IS CLEAR NOW",
    ciphertext:"ULI DSETX MT GPFEV OSA",
    hints:["Vigenère cipher — repeating key", "Key length is 3 letters", "Key: BEE"] },
  { id:"d91", cipher:"Vigenère", difficulty:"Medium", points:250,
    keyInfo:"Key: WEB",
    plaintext:"RENDEZVOUS AT THE CHECKPOINT",
    ciphertext:"NIOZIARSVO EU PLF YLFYOQKMOP",
    hints:["Vigenère cipher — repeating key", "Key length is 3 letters", "Key: WEB"] },
  { id:"d92", cipher:"Vigenère", difficulty:"Medium", points:250,
    keyInfo:"Key: NIT",
    plaintext:"THE KEY IS HIDDEN BELOW",
    ciphertext:"GPX XMR VA AVLWRV URTHJ",
    hints:["Vigenère cipher — repeating key", "Key length is 3 letters", "Key: NIT"] },
  { id:"d93", cipher:"Vigenère", difficulty:"Medium", points:250,
    keyInfo:"Key: ZEN",
    plaintext:"SHADOWS MOVE AT DUSK",
    ciphertext:"RLNCSJR QBUI NS HHRO",
    hints:["Vigenère cipher — repeating key", "Key length is 3 letters", "Key: ZEN"] },
  { id:"d94", cipher:"Vigenère", difficulty:"Medium", points:250,
    keyInfo:"Key: RYE",
    plaintext:"THE CIPHER MUST FALL",
    ciphertext:"KFI TGTYCV DSWK DECJ",
    hints:["Vigenère cipher — repeating key", "Key length is 3 letters", "Key: RYE"] },
  { id:"d95", cipher:"Vigenère", difficulty:"Medium", points:250,
    keyInfo:"Key: IVY",
    plaintext:"ENCODE THE NEXT MESSAGE",
    ciphertext:"MIAWYC BCC VZVB HCANYOZ",
    hints:["Vigenère cipher — repeating key", "Key length is 3 letters", "Key: IVY"] },
  { id:"d96", cipher:"Vigenère", difficulty:"Medium", points:250,
    keyInfo:"Key: ELM",
    plaintext:"DECRYPT WITH CAUTION",
    ciphertext:"HPOVJBX HUXS OEFFMZZ",
    hints:["Vigenère cipher — repeating key", "Key length is 3 letters", "Key: ELM"] },
  { id:"d97", cipher:"Vigenère", difficulty:"Medium", points:250,
    keyInfo:"Key: OAT",
    plaintext:"THE VAULT IS OPEN NOW",
    ciphertext:"HHX JANZT BG OISN GCW",
    hints:["Vigenère cipher — repeating key", "Key length is 3 letters", "Key: OAT"] },
  { id:"d98", cipher:"Vigenère", difficulty:"Medium", points:250,
    keyInfo:"Key: APE",
    plaintext:"SECURE ALL CHANNELS",
    ciphertext:"STGUGI AAP CWENCILH",
    hints:["Vigenère cipher — repeating key", "Key length is 3 letters", "Key: APE"] },
  { id:"d99", cipher:"Vigenère", difficulty:"Medium", points:250,
    keyInfo:"Key: GNU",
    plaintext:"OPERATION IS A SUCCESS",
    ciphertext:"UCYXNNOBH OF U YHWIRMY",
    hints:["Vigenère cipher — repeating key", "Key length is 3 letters", "Key: GNU"] },
  { id:"d100", cipher:"Vigenère", difficulty:"Medium", points:250,
    keyInfo:"Key: COD",
    plaintext:"THE MISSION IS COMPLETE",
    ciphertext:"VVH OWVUWRP WV ECPRZHVS",
    hints:["Vigenère cipher — repeating key", "Key length is 3 letters", "Key: COD"] },
  { id:"d101", cipher:"Vigenère", difficulty:"Hard", points:350,
    keyInfo:"Key: CRYPTO",
    plaintext:"THE POLYALPHABETIC CIPHER RESISTS SIMPLE ANALYSIS",
    ciphertext:"VYC EHZARJEAODVRXV QKGFTK FGJGHMG UZKEES CEYARGKJ",
    hints:["Vigenère cipher — use Kasiski or IoC to find key length", "Key length: 6", "Key: CRYPTO"] },
  { id:"d102", cipher:"Vigenère", difficulty:"Hard", points:350,
    keyInfo:"Key: PYTHON",
    plaintext:"KASISKI EXAMINATION REVEALS THE KEY LENGTH",
    ciphertext:"ZYLPGXX CQHAVCYMPCA GCOLOYH RAL YRN JXUUGW",
    hints:["Vigenère cipher — use Kasiski or IoC to find key length", "Key length: 6", "Key: PYTHON"] },
  { id:"d103", cipher:"Vigenère", difficulty:"Hard", points:350,
    keyInfo:"Key: ENIGMA",
    plaintext:"INDEX OF COINCIDENCE MEASURES CIPHER STRENGTH",
    ciphertext:"MALKJ OJ PWOZCMQMTOE QRIYGRIF KOBHIE AZDERTBN",
    hints:["Vigenère cipher — use Kasiski or IoC to find key length", "Key length: 6", "Key: ENIGMA"] },
  { id:"d104", cipher:"Vigenère", difficulty:"Hard", points:350,
    keyInfo:"Key: CIPHER",
    plaintext:"VIGENERE SQUARE MAPS EVERY LETTER COMBINATION",
    ciphertext:"XQVLRVTM HXYRTM BHTJ GDTYC CGBILV TQUQPRRVQDU",
    hints:["Vigenère cipher — use Kasiski or IoC to find key length", "Key length: 6", "Key: CIPHER"] },
  { id:"d105", cipher:"Vigenère", difficulty:"Hard", points:350,
    keyInfo:"Key: QUANTUM",
    plaintext:"RUNNING KEY CIPHER USES A TEXT AS THE KEY",
    ciphertext:"HONABHS AYY PBJTUL UFXM M JYXG TM FXY KRR",
    hints:["Vigenère cipher — use Kasiski or IoC to find key length", "Key length: 7", "Key: QUANTUM"] },
  { id:"d106", cipher:"Vigenère", difficulty:"Hard", points:350,
    keyInfo:"Key: MATRIX",
    plaintext:"AUTOKEY CIPHER EXTENDS THE KEY WITH PLAINTEXT",
    ciphertext:"MUMFSBK CBGPBD EQKMKPS MYM HQY PZBE BLTZVQQXM",
    hints:["Vigenère cipher — use Kasiski or IoC to find key length", "Key length: 6", "Key: MATRIX"] },
  { id:"d107", cipher:"Vigenère", difficulty:"Hard", points:350,
    keyInfo:"Key: FALCON",
    plaintext:"BEAUFORT CIPHER IS THE RECIPROCAL OF VIGENERE",
    ciphertext:"GELWTBWT NKDUJR TU HUJ RPEWCWONCZ BK VTISAJRP",
    hints:["Vigenère cipher — use Kasiski or IoC to find key length", "Key length: 6", "Key: FALCON"] },
  { id:"d108", cipher:"Vigenère", difficulty:"Hard", points:350,
    keyInfo:"Key: VECTOR",
    plaintext:"GRONSFELD CIPHER USES DIGITS INSTEAD OF LETTERS",
    ciphertext:"BVQGGWZPF VWGCIT NGVN HKZWKN MPLHVVH QY ZVOXGKG",
    hints:["Vigenère cipher — use Kasiski or IoC to find key length", "Key length: 6", "Key: VECTOR"] },
  { id:"d109", cipher:"Vigenère", difficulty:"Hard", points:350,
    keyInfo:"Key: PHOTON",
    plaintext:"PORTA CIPHER WAS INVENTED BY GIAMBATTISTA DELLA PORTA",
    ciphertext:"EVFMO PXWVXF JPZ WGJRCASW PL VPOFPNIAWLHN SLZEO CDYHT",
    hints:["Vigenère cipher — use Kasiski or IoC to find key length", "Key length: 6", "Key: PHOTON"] },
  { id:"d110", cipher:"Vigenère", difficulty:"Hard", points:350,
    keyInfo:"Key: BINARY",
    plaintext:"QUAGMIRE CIPHER IS A COMPLEX VIGENERE VARIANT",
    ciphertext:"RCNGDGSM PIGFFZ VS R APUCLVV WQTEECSM IAIGBVG",
    hints:["Vigenère cipher — use Kasiski or IoC to find key length", "Key length: 6", "Key: BINARY"] },
  { id:"d111", cipher:"Vigenère", difficulty:"Hard", points:350,
    keyInfo:"Key: SIGNAL",
    plaintext:"THE KEYWORD DETERMINES THE ENTIRE ENCRYPTION SCHEME",
    ciphertext:"LPK XEJOWXQ DPLMXZIYWA ZUE PFBOEE PFKXLPEAWT FCSWUK",
    hints:["Vigenère cipher — use Kasiski or IoC to find key length", "Key length: 6", "Key: SIGNAL"] },
  { id:"d112", cipher:"Vigenère", difficulty:"Hard", points:350,
    keyInfo:"Key: LAMBDA",
    plaintext:"REPEATED PATTERNS IN CIPHERTEXT BETRAY THE KEY LENGTH",
    ciphertext:"CEBFDTPD BBWTPRZT LN NIBIHREEJU EEERMZ WHP KQZ OEYGFI",
    hints:["Vigenère cipher — use Kasiski or IoC to find key length", "Key length: 6", "Key: LAMBDA"] },
  { id:"d113", cipher:"Vigenère", difficulty:"Hard", points:350,
    keyInfo:"Key: PASCAL",
    plaintext:"CRYPTANALYSIS RELIES ON STATISTICAL PROPERTIES OF LANGUAGE",
    ciphertext:"RRQRTLCADASTH RWNIPH OF UTLIIKVINPL HTOATRLKED DF DCNRJAYG",
    hints:["Vigenère cipher — use Kasiski or IoC to find key length", "Key length: 6", "Key: PASCAL"] },
  { id:"d114", cipher:"Vigenère", difficulty:"Hard", points:350,
    keyInfo:"Key: NEWTON",
    plaintext:"THE FRIEDMAN TEST ESTIMATES KEY LENGTH STATISTICALLY",
    ciphertext:"GLA YFVRHITB GRWP XGGVQWMSF XIU ESATXD LHNGMOMWPNPHR",
    hints:["Vigenère cipher — use Kasiski or IoC to find key length", "Key length: 6", "Key: NEWTON"] },
  { id:"d115", cipher:"Vigenère", difficulty:"Hard", points:350,
    keyInfo:"Key: EUCLID",
    plaintext:"ENTROPY IS THE MEASURE OF INFORMATION IN A MESSAGE",
    ciphertext:"IHVCWSC CU EPH QYCDCUI IH TVISLOLBLSH KY I PIMULOH",
    hints:["Vigenère cipher — use Kasiski or IoC to find key length", "Key length: 6", "Key: EUCLID"] },
  { id:"d116", cipher:"Vigenère", difficulty:"Hard", points:350,
    keyInfo:"Key: FERMAT",
    plaintext:"PERFECT SECRECY REQUIRES A KEY AS LONG AS THE MESSAGE",
    ciphertext:"UIIREVY WVORXHC IQQNNVVE A DJC RE LHSK RE TAJ QVESTLI",
    hints:["Vigenère cipher — use Kasiski or IoC to find key length", "Key length: 6", "Key: FERMAT"] },
  { id:"d117", cipher:"Vigenère", difficulty:"Hard", points:350,
    keyInfo:"Key: GALOIS",
    plaintext:"ONE TIME PAD IS THEORETICALLY UNBREAKABLE IF USED CORRECTLY",
    ciphertext:"UNP HQEK PLR QK ZHPCZWZINOTDE UYPZWGKLPTW OF FGMV IOCFMUZLJ",
    hints:["Vigenère cipher — use Kasiski or IoC to find key length", "Key length: 6", "Key: GALOIS"] },
  { id:"d118", cipher:"Vigenère", difficulty:"Hard", points:350,
    keyInfo:"Key: TURING",
    plaintext:"CLAUDE SHANNON PROVED THE SECURITY OF THE ONE TIME PAD",
    ciphertext:"VFRCQK LBRVAUG JIWIKW NYM FKVOIQGE HZ KPR UGY KQZK IUU",
    hints:["Vigenère cipher — use Kasiski or IoC to find key length", "Key length: 6", "Key: TURING"] },
  { id:"d119", cipher:"Vigenère", difficulty:"Hard", points:350,
    keyInfo:"Key: CANTOR",
    plaintext:"MODERN ENCRYPTION BUILDS ON CENTURIES OF CLASSICAL WORK",
    ciphertext:"OOQXFE GNPKMGVIBG PLKLQL CE EEAMIIKEF HT TNAFLWTCL JHFB",
    hints:["Vigenère cipher — use Kasiski or IoC to find key length", "Key length: 6", "Key: CANTOR"] },
  { id:"d120", cipher:"Vigenère", difficulty:"Hard", points:350,
    keyInfo:"Key: HILBERT",
    plaintext:"THE HISTORY OF CRYPTOGRAPHY IS A HISTORY OF SECRETS",
    ciphertext:"APP IMJMVZJ PJ TKFXEPKITWPJ JW R APAEPVP HM APDVVMZ",
    hints:["Vigenère cipher — use Kasiski or IoC to find key length", "Key length: 7", "Key: HILBERT"] },
  { id:"d121", cipher:"Atbash", difficulty:"Easy", points:100,
    keyInfo:"Mirror alphabet: A↔Z, B↔Y...",
    plaintext:"HELLO",
    ciphertext:"SVOOL",
    hints:["Atbash: mirror the alphabet", "A becomes Z, B becomes Y, etc.", "Decrypt: mirror each letter"] },
  { id:"d122", cipher:"Atbash", difficulty:"Easy", points:100,
    keyInfo:"Mirror alphabet: A↔Z, B↔Y...",
    plaintext:"WORLD",
    ciphertext:"DLIOW",
    hints:["Atbash: mirror the alphabet", "A becomes Z, B becomes Y, etc.", "Decrypt: mirror each letter"] },
  { id:"d123", cipher:"Atbash", difficulty:"Easy", points:100,
    keyInfo:"Mirror alphabet: A↔Z, B↔Y...",
    plaintext:"CRYPTO",
    ciphertext:"XIBKGL",
    hints:["Atbash: mirror the alphabet", "A becomes Z, B becomes Y, etc.", "Decrypt: mirror each letter"] },
  { id:"d124", cipher:"Atbash", difficulty:"Easy", points:100,
    keyInfo:"Mirror alphabet: A↔Z, B↔Y...",
    plaintext:"SECRET",
    ciphertext:"HVXIVG",
    hints:["Atbash: mirror the alphabet", "A becomes Z, B becomes Y, etc.", "Decrypt: mirror each letter"] },
  { id:"d125", cipher:"Atbash", difficulty:"Easy", points:100,
    keyInfo:"Mirror alphabet: A↔Z, B↔Y...",
    plaintext:"ATTACK",
    ciphertext:"ZGGZXP",
    hints:["Atbash: mirror the alphabet", "A becomes Z, B becomes Y, etc.", "Decrypt: mirror each letter"] },
  { id:"d126", cipher:"Atbash", difficulty:"Easy", points:100,
    keyInfo:"Mirror alphabet: A↔Z, B↔Y...",
    plaintext:"DEFEND",
    ciphertext:"WVUVMW",
    hints:["Atbash: mirror the alphabet", "A becomes Z, B becomes Y, etc.", "Decrypt: mirror each letter"] },
  { id:"d127", cipher:"Atbash", difficulty:"Easy", points:100,
    keyInfo:"Mirror alphabet: A↔Z, B↔Y...",
    plaintext:"CIPHER",
    ciphertext:"XRKSVI",
    hints:["Atbash: mirror the alphabet", "A becomes Z, B becomes Y, etc.", "Decrypt: mirror each letter"] },
  { id:"d128", cipher:"Atbash", difficulty:"Easy", points:100,
    keyInfo:"Mirror alphabet: A↔Z, B↔Y...",
    plaintext:"DECODE",
    ciphertext:"WVXLWV",
    hints:["Atbash: mirror the alphabet", "A becomes Z, B becomes Y, etc.", "Decrypt: mirror each letter"] },
  { id:"d129", cipher:"Atbash", difficulty:"Easy", points:100,
    keyInfo:"Mirror alphabet: A↔Z, B↔Y...",
    plaintext:"ENIGMA",
    ciphertext:"VMRTNZ",
    hints:["Atbash: mirror the alphabet", "A becomes Z, B becomes Y, etc.", "Decrypt: mirror each letter"] },
  { id:"d130", cipher:"Atbash", difficulty:"Easy", points:100,
    keyInfo:"Mirror alphabet: A↔Z, B↔Y...",
    plaintext:"SIGNAL",
    ciphertext:"HRTMZO",
    hints:["Atbash: mirror the alphabet", "A becomes Z, B becomes Y, etc.", "Decrypt: mirror each letter"] },
  { id:"d131", cipher:"Atbash", difficulty:"Medium", points:200,
    keyInfo:"Mirror alphabet: A↔Z, B↔Y...",
    plaintext:"BEACON",
    ciphertext:"YVZXLM",
    hints:["Atbash: mirror the alphabet", "A becomes Z, B becomes Y, etc.", "Decrypt: mirror each letter"] },
  { id:"d132", cipher:"Atbash", difficulty:"Medium", points:200,
    keyInfo:"Mirror alphabet: A↔Z, B↔Y...",
    plaintext:"SHADOW",
    ciphertext:"HSZWLD",
    hints:["Atbash: mirror the alphabet", "A becomes Z, B becomes Y, etc.", "Decrypt: mirror each letter"] },
  { id:"d133", cipher:"Atbash", difficulty:"Medium", points:200,
    keyInfo:"Mirror alphabet: A↔Z, B↔Y...",
    plaintext:"FALCON",
    ciphertext:"UZOXLM",
    hints:["Atbash: mirror the alphabet", "A becomes Z, B becomes Y, etc.", "Decrypt: mirror each letter"] },
  { id:"d134", cipher:"Atbash", difficulty:"Medium", points:200,
    keyInfo:"Mirror alphabet: A↔Z, B↔Y...",
    plaintext:"VECTOR",
    ciphertext:"EVXGLI",
    hints:["Atbash: mirror the alphabet", "A becomes Z, B becomes Y, etc.", "Decrypt: mirror each letter"] },
  { id:"d135", cipher:"Atbash", difficulty:"Medium", points:200,
    keyInfo:"Mirror alphabet: A↔Z, B↔Y...",
    plaintext:"BINARY",
    ciphertext:"YRMZIB",
    hints:["Atbash: mirror the alphabet", "A becomes Z, B becomes Y, etc.", "Decrypt: mirror each letter"] },
  { id:"d136", cipher:"Atbash", difficulty:"Medium", points:200,
    keyInfo:"Mirror alphabet: A↔Z, B↔Y...",
    plaintext:"MATRIX",
    ciphertext:"NZGIRC",
    hints:["Atbash: mirror the alphabet", "A becomes Z, B becomes Y, etc.", "Decrypt: mirror each letter"] },
  { id:"d137", cipher:"Atbash", difficulty:"Medium", points:200,
    keyInfo:"Mirror alphabet: A↔Z, B↔Y...",
    plaintext:"PYTHON",
    ciphertext:"KBGSLM",
    hints:["Atbash: mirror the alphabet", "A becomes Z, B becomes Y, etc.", "Decrypt: mirror each letter"] },
  { id:"d138", cipher:"Atbash", difficulty:"Medium", points:200,
    keyInfo:"Mirror alphabet: A↔Z, B↔Y...",
    plaintext:"LAMBDA",
    ciphertext:"OZNYWZ",
    hints:["Atbash: mirror the alphabet", "A becomes Z, B becomes Y, etc.", "Decrypt: mirror each letter"] },
  { id:"d139", cipher:"Atbash", difficulty:"Medium", points:200,
    keyInfo:"Mirror alphabet: A↔Z, B↔Y...",
    plaintext:"ROCKET",
    ciphertext:"ILXPVG",
    hints:["Atbash: mirror the alphabet", "A becomes Z, B becomes Y, etc.", "Decrypt: mirror each letter"] },
  { id:"d140", cipher:"Atbash", difficulty:"Medium", points:200,
    keyInfo:"Mirror alphabet: A↔Z, B↔Y...",
    plaintext:"PLANET",
    ciphertext:"KOZMVG",
    hints:["Atbash: mirror the alphabet", "A becomes Z, B becomes Y, etc.", "Decrypt: mirror each letter"] },
  { id:"d141", cipher:"ROT13", difficulty:"Easy", points:100,
    keyInfo:"Shift: 13 (self-inverse)",
    plaintext:"HELLO WORLD",
    ciphertext:"URYYB JBEYQ",
    hints:["ROT13: shift by exactly 13", "Applying ROT13 twice returns original", "A→N, B→O, C→P ..."] },
  { id:"d142", cipher:"ROT13", difficulty:"Easy", points:100,
    keyInfo:"Shift: 13 (self-inverse)",
    plaintext:"CIPHER TEXT",
    ciphertext:"PVCURE GRKG",
    hints:["ROT13: shift by exactly 13", "Applying ROT13 twice returns original", "A→N, B→O, C→P ..."] },
  { id:"d143", cipher:"ROT13", difficulty:"Easy", points:100,
    keyInfo:"Shift: 13 (self-inverse)",
    plaintext:"SECRET CODE",
    ciphertext:"FRPERG PBQR",
    hints:["ROT13: shift by exactly 13", "Applying ROT13 twice returns original", "A→N, B→O, C→P ..."] },
  { id:"d144", cipher:"ROT13", difficulty:"Easy", points:100,
    keyInfo:"Shift: 13 (self-inverse)",
    plaintext:"DECODE THIS",
    ciphertext:"QRPBQR GUVF",
    hints:["ROT13: shift by exactly 13", "Applying ROT13 twice returns original", "A→N, B→O, C→P ..."] },
  { id:"d145", cipher:"ROT13", difficulty:"Easy", points:100,
    keyInfo:"Shift: 13 (self-inverse)",
    plaintext:"BREAK THE LOCK",
    ciphertext:"OERNX GUR YBPX",
    hints:["ROT13: shift by exactly 13", "Applying ROT13 twice returns original", "A→N, B→O, C→P ..."] },
  { id:"d146", cipher:"ROT13", difficulty:"Easy", points:100,
    keyInfo:"Shift: 13 (self-inverse)",
    plaintext:"FIND THE KEY",
    ciphertext:"SVAQ GUR XRL",
    hints:["ROT13: shift by exactly 13", "Applying ROT13 twice returns original", "A→N, B→O, C→P ..."] },
  { id:"d147", cipher:"ROT13", difficulty:"Easy", points:100,
    keyInfo:"Shift: 13 (self-inverse)",
    plaintext:"THE ANSWER IS",
    ciphertext:"GUR NAFJRE VF",
    hints:["ROT13: shift by exactly 13", "Applying ROT13 twice returns original", "A→N, B→O, C→P ..."] },
  { id:"d148", cipher:"ROT13", difficulty:"Easy", points:100,
    keyInfo:"Shift: 13 (self-inverse)",
    plaintext:"OPEN SESAME",
    ciphertext:"BCRA FRFNZR",
    hints:["ROT13: shift by exactly 13", "Applying ROT13 twice returns original", "A→N, B→O, C→P ..."] },
  { id:"d149", cipher:"ROT13", difficulty:"Easy", points:100,
    keyInfo:"Shift: 13 (self-inverse)",
    plaintext:"NIGHT WATCH",
    ciphertext:"AVTUG JNGPU",
    hints:["ROT13: shift by exactly 13", "Applying ROT13 twice returns original", "A→N, B→O, C→P ..."] },
  { id:"d150", cipher:"ROT13", difficulty:"Easy", points:100,
    keyInfo:"Shift: 13 (self-inverse)",
    plaintext:"FIRE AT WILL",
    ciphertext:"SVER NG JVYY",
    hints:["ROT13: shift by exactly 13", "Applying ROT13 twice returns original", "A→N, B→O, C→P ..."] },
  { id:"d151", cipher:"ROT13", difficulty:"Easy", points:100,
    keyInfo:"Shift: 13 (self-inverse)",
    plaintext:"SEND BACKUP",
    ciphertext:"FRAQ ONPXHC",
    hints:["ROT13: shift by exactly 13", "Applying ROT13 twice returns original", "A→N, B→O, C→P ..."] },
  { id:"d152", cipher:"ROT13", difficulty:"Easy", points:100,
    keyInfo:"Shift: 13 (self-inverse)",
    plaintext:"STORM THE GATE",
    ciphertext:"FGBEZ GUR TNGR",
    hints:["ROT13: shift by exactly 13", "Applying ROT13 twice returns original", "A→N, B→O, C→P ..."] },
  { id:"d153", cipher:"ROT13", difficulty:"Easy", points:100,
    keyInfo:"Shift: 13 (self-inverse)",
    plaintext:"HOLD POSITION",
    ciphertext:"UBYQ CBFVGVBA",
    hints:["ROT13: shift by exactly 13", "Applying ROT13 twice returns original", "A→N, B→O, C→P ..."] },
  { id:"d154", cipher:"ROT13", difficulty:"Easy", points:100,
    keyInfo:"Shift: 13 (self-inverse)",
    plaintext:"FALL BACK NOW",
    ciphertext:"SNYY ONPX ABJ",
    hints:["ROT13: shift by exactly 13", "Applying ROT13 twice returns original", "A→N, B→O, C→P ..."] },
  { id:"d155", cipher:"ROT13", difficulty:"Easy", points:100,
    keyInfo:"Shift: 13 (self-inverse)",
    plaintext:"ADVANCE TROOPS",
    ciphertext:"NQINAPR GEBBCF",
    hints:["ROT13: shift by exactly 13", "Applying ROT13 twice returns original", "A→N, B→O, C→P ..."] },
  { id:"d156", cipher:"Rail Fence", difficulty:"Easy", points:100,
    keyInfo:"Rails: 2",
    plaintext:"HELLOWORLD",
    ciphertext:"HLOOLELWRD",
    hints:["Rail Fence cipher with 2 rails", "Write letters in zigzag pattern", "Read across each rail: 2 rails total"] },
  { id:"d157", cipher:"Rail Fence", difficulty:"Medium", points:200,
    keyInfo:"Rails: 3",
    plaintext:"WEAREDISCOVERED",
    ciphertext:"WECRERDSOEEAIVD",
    hints:["Rail Fence cipher with 3 rails", "Write letters in zigzag pattern", "Read across each rail: 3 rails total"] },
  { id:"d158", cipher:"Rail Fence", difficulty:"Easy", points:100,
    keyInfo:"Rails: 2",
    plaintext:"ATTACKATDAWN",
    ciphertext:"ATCADWTAKTAN",
    hints:["Rail Fence cipher with 2 rails", "Write letters in zigzag pattern", "Read across each rail: 2 rails total"] },
  { id:"d159", cipher:"Rail Fence", difficulty:"Medium", points:200,
    keyInfo:"Rails: 3",
    plaintext:"DEFENDTHEFORT",
    ciphertext:"DNETEEDHFRFTO",
    hints:["Rail Fence cipher with 3 rails", "Write letters in zigzag pattern", "Read across each rail: 3 rails total"] },
  { id:"d160", cipher:"Rail Fence", difficulty:"Easy", points:100,
    keyInfo:"Rails: 2",
    plaintext:"SENDTHESIGNAL",
    ciphertext:"SNTEINLEDHSGA",
    hints:["Rail Fence cipher with 2 rails", "Write letters in zigzag pattern", "Read across each rail: 2 rails total"] },
  { id:"d161", cipher:"Rail Fence", difficulty:"Medium", points:200,
    keyInfo:"Rails: 3",
    plaintext:"MEETATMIDNIGHT",
    ciphertext:"MADHETTINGTEMI",
    hints:["Rail Fence cipher with 3 rails", "Write letters in zigzag pattern", "Read across each rail: 3 rails total"] },
  { id:"d162", cipher:"Rail Fence", difficulty:"Easy", points:100,
    keyInfo:"Rails: 2",
    plaintext:"THECODEISBROKEN",
    ciphertext:"TEOESRKNHCDIBOE",
    hints:["Rail Fence cipher with 2 rails", "Write letters in zigzag pattern", "Read across each rail: 2 rails total"] },
  { id:"d163", cipher:"Rail Fence", difficulty:"Medium", points:200,
    keyInfo:"Rails: 3",
    plaintext:"SILENCEANDSHADOW",
    ciphertext:"SNNAIECADHDWLESO",
    hints:["Rail Fence cipher with 3 rails", "Write letters in zigzag pattern", "Read across each rail: 3 rails total"] },
  { id:"d164", cipher:"Rail Fence", difficulty:"Easy", points:100,
    keyInfo:"Rails: 2",
    plaintext:"ESCAPETHROUGHTHETUNNELS",
    ciphertext:"ECPTRUHHTNESSAEHOGTEUNL",
    hints:["Rail Fence cipher with 2 rails", "Write letters in zigzag pattern", "Read across each rail: 2 rails total"] },
  { id:"d165", cipher:"Rail Fence", difficulty:"Medium", points:200,
    keyInfo:"Rails: 3",
    plaintext:"RENDEZVOUSATSUNRISE",
    ciphertext:"REUSIEDZOSTURSNVANE",
    hints:["Rail Fence cipher with 3 rails", "Write letters in zigzag pattern", "Read across each rail: 3 rails total"] },
  { id:"d166", cipher:"Rail Fence", difficulty:"Easy", points:100,
    keyInfo:"Rails: 2",
    plaintext:"BURNAFTERREADING",
    ciphertext:"BRATREDNUNFERAIG",
    hints:["Rail Fence cipher with 2 rails", "Write letters in zigzag pattern", "Read across each rail: 2 rails total"] },
  { id:"d167", cipher:"Rail Fence", difficulty:"Medium", points:200,
    keyInfo:"Rails: 3",
    plaintext:"THEVAULTISOPEN",
    ciphertext:"TAIEHVUTSPNELO",
    hints:["Rail Fence cipher with 3 rails", "Write letters in zigzag pattern", "Read across each rail: 3 rails total"] },
  { id:"d168", cipher:"Rail Fence", difficulty:"Easy", points:100,
    keyInfo:"Rails: 2",
    plaintext:"OPERATIONNIGHTFALL",
    ciphertext:"OEAINIHFLPRTONGTAL",
    hints:["Rail Fence cipher with 2 rails", "Write letters in zigzag pattern", "Read across each rail: 2 rails total"] },
  { id:"d169", cipher:"Rail Fence", difficulty:"Medium", points:200,
    keyInfo:"Rails: 3",
    plaintext:"DESTROYALLEVIDENCE",
    ciphertext:"DRLICETOALVDNESYEE",
    hints:["Rail Fence cipher with 3 rails", "Write letters in zigzag pattern", "Read across each rail: 3 rails total"] },
  { id:"d170", cipher:"Rail Fence", difficulty:"Easy", points:100,
    keyInfo:"Rails: 2",
    plaintext:"FOLLOWTHEWHITERABBIT",
    ciphertext:"FLOTEHTRBIOLWHWIEABT",
    hints:["Rail Fence cipher with 2 rails", "Write letters in zigzag pattern", "Read across each rail: 2 rails total"] },
  { id:"d171", cipher:"Monoalphabetic", difficulty:"Hard", points:400,
    keyInfo:"Fixed substitution alphabet",
    plaintext:"THE QUICK BROWN FOX JUMPS OVER THE LAZY DOG",
    ciphertext:"ZIT JXOEA WKGVF YGB PXDHL GCTK ZIT SQMN RGU",
    hints:["Monoalphabetic: each letter maps to a unique other letter", "Use frequency analysis — E, T, A are most common", "Q→A, W→B, E→C in this substitution"] },
  { id:"d172", cipher:"Monoalphabetic", difficulty:"Hard", points:400,
    keyInfo:"Fixed substitution alphabet",
    plaintext:"PACK MY BOX WITH FIVE DOZEN LIQUOR JUGS",
    ciphertext:"HQEA DN WGB VOZI YOCT RGMTF SOJXGK PXUL",
    hints:["Monoalphabetic: each letter maps to a unique other letter", "Use frequency analysis — E, T, A are most common", "Q→A, W→B, E→C in this substitution"] },
  { id:"d173", cipher:"Monoalphabetic", difficulty:"Hard", points:400,
    keyInfo:"Fixed substitution alphabet",
    plaintext:"HOW VEXINGLY QUICK DAFT ZEBRAS JUMP",
    ciphertext:"IGV CTBOFUSN JXOEA RQYZ MTWKQL PXDH",
    hints:["Monoalphabetic: each letter maps to a unique other letter", "Use frequency analysis — E, T, A are most common", "Q→A, W→B, E→C in this substitution"] },
  { id:"d174", cipher:"Monoalphabetic", difficulty:"Hard", points:400,
    keyInfo:"Fixed substitution alphabet",
    plaintext:"THE FIVE BOXING WIZARDS JUMP QUICKLY",
    ciphertext:"ZIT YOCT WGBOFU VOMQKRL PXDH JXOEASN",
    hints:["Monoalphabetic: each letter maps to a unique other letter", "Use frequency analysis — E, T, A are most common", "Q→A, W→B, E→C in this substitution"] },
  { id:"d175", cipher:"Monoalphabetic", difficulty:"Hard", points:400,
    keyInfo:"Fixed substitution alphabet",
    plaintext:"BRIGHT VIXENS JUMP DOZY FOWL QUACK",
    ciphertext:"WKOUIZ COBTFL PXDH RGMN YGVS JXQEA",
    hints:["Monoalphabetic: each letter maps to a unique other letter", "Use frequency analysis — E, T, A are most common", "Q→A, W→B, E→C in this substitution"] },
  { id:"d176", cipher:"Monoalphabetic", difficulty:"Hard", points:400,
    keyInfo:"Fixed substitution alphabet",
    plaintext:"SPHINX OF BLACK QUARTZ JUDGE MY VOW",
    ciphertext:"LHIOFB GY WSQEA JXQKZM PXRUT DN CGV",
    hints:["Monoalphabetic: each letter maps to a unique other letter", "Use frequency analysis — E, T, A are most common", "Q→A, W→B, E→C in this substitution"] },
  { id:"d177", cipher:"Monoalphabetic", difficulty:"Hard", points:400,
    keyInfo:"Fixed substitution alphabet",
    plaintext:"WALTZ NYMPH FOR QUICK JIGS VEX BUD",
    ciphertext:"VQSZM FNDHI YGK JXOEA POUL CTB WXR",
    hints:["Monoalphabetic: each letter maps to a unique other letter", "Use frequency analysis — E, T, A are most common", "Q→A, W→B, E→C in this substitution"] },
  { id:"d178", cipher:"Monoalphabetic", difficulty:"Hard", points:400,
    keyInfo:"Fixed substitution alphabet",
    plaintext:"GLUM SCHWARTZKOPF VEX BITING JADY",
    ciphertext:"USXD LEIVQKZMAGHY CTB WOZOFU PQRN",
    hints:["Monoalphabetic: each letter maps to a unique other letter", "Use frequency analysis — E, T, A are most common", "Q→A, W→B, E→C in this substitution"] },
  { id:"d179", cipher:"Monoalphabetic", difficulty:"Hard", points:400,
    keyInfo:"Fixed substitution alphabet",
    plaintext:"JACKDAWS LOVE MY BIG SPHINX OF QUARTZ",
    ciphertext:"PQEARQVL SGCT DN WOU LHIOFB GY JXQKZM",
    hints:["Monoalphabetic: each letter maps to a unique other letter", "Use frequency analysis — E, T, A are most common", "Q→A, W→B, E→C in this substitution"] },
  { id:"d180", cipher:"Monoalphabetic", difficulty:"Hard", points:400,
    keyInfo:"Fixed substitution alphabet",
    plaintext:"CRAZY FREDRICK BOUGHT MANY VERY EXQUISITE OPAL JEWELS",
    ciphertext:"EKQMN YKTRKOEA WGXUIZ DQFN CTKN TBJXOLOZT GHQS PTVTSL",
    hints:["Monoalphabetic: each letter maps to a unique other letter", "Use frequency analysis — E, T, A are most common", "Q→A, W→B, E→C in this substitution"] },
  { id:"d181", cipher:"Vigenère", difficulty:"Hard", points:350,
    keyInfo:"Key: CIPHER",
    plaintext:"THE ENIGMA MACHINE USED ROTORS TO ENCRYPT",
    ciphertext:"VPT LRZIUP TETJQCL YJGL GVXFTA IV IEEZNWX",
    hints:["Vigenère cipher", "Key length: 6", "Key: CIPHER"] },
  { id:"d182", cipher:"Vigenère", difficulty:"Hard", points:350,
    keyInfo:"Key: SYSTEM",
    plaintext:"CRYPTOGRAPHY IS THE ART OF SECRET WRITING",
    ciphertext:"UPQIXAYPSILK AQ LAI MJR GY WQUPWM ADARAGK",
    hints:["Vigenère cipher", "Key length: 6", "Key: SYSTEM"] },
  { id:"d183", cipher:"Vigenère", difficulty:"Hard", points:350,
    keyInfo:"Key: FALCON",
    plaintext:"FREQUENCY ANALYSIS IS THE OLDEST ATTACK METHOD",
    ciphertext:"KRPSIRSCJ CBNQYDKG VX TSG CYIEDV OGYANM ARYHZF",
    hints:["Vigenère cipher", "Key length: 6", "Key: FALCON"] },
  { id:"d184", cipher:"Vigenère", difficulty:"Hard", points:350,
    keyInfo:"Key: MATRIX",
    plaintext:"THE LORENZ CIPHER WAS USED BY GERMAN HIGH COMMAND",
    ciphertext:"FHX CWOQNS TQMTEK NIP GSXU JV SEKDIK TIZY KLYMTEL",
    hints:["Vigenère cipher", "Key length: 6", "Key: MATRIX"] },
  { id:"d185", cipher:"Vigenère", difficulty:"Hard", points:350,
    keyInfo:"Key: PYTHON",
    plaintext:"BLETCHLEY PARK HOUSED THE CODE BREAKING OPERATION",
    ciphertext:"QJXAQUACR WOEZ FHBGRS RAL QBSC UYSNZGGN CCTPTAWBC",
    hints:["Vigenère cipher", "Key length: 6", "Key: PYTHON"] },
  { id:"d186", cipher:"Vigenère", difficulty:"Hard", points:350,
    keyInfo:"Key: LAMBDA",
    plaintext:"DIFFIE AND HELLMAN INVENTED PUBLIC KEY CRYPTOGRAPHY",
    ciphertext:"OIRGLE LNP IHLWMMO LNGEZUHD AUNMLC VEK DUYATAHUAAHK",
    hints:["Vigenère cipher", "Key length: 6", "Key: LAMBDA"] },
  { id:"d187", cipher:"Vigenère", difficulty:"Hard", points:350,
    keyInfo:"Key: SIGNAL",
    plaintext:"RSA ALGORITHM IS BASED ON FACTORING LARGE PRIMES",
    ciphertext:"JAG NLRGZOGHX AA HNSPV WT SANLWXVNR DIXTE AJQSRS",
    hints:["Vigenère cipher", "Key length: 6", "Key: SIGNAL"] },
  { id:"d188", cipher:"Vigenère", difficulty:"Hard", points:350,
    keyInfo:"Key: VECTOR",
    plaintext:"ELLIPTIC CURVE CRYPTOGRAPHY OFFERS SMALLER KEY SIZES",
    ciphertext:"ZPNBDKDG ENFMZ GTRDKJKTTDYT SHYSIN WOTZCZV MXM JDDGL",
    hints:["Vigenère cipher", "Key length: 6", "Key: VECTOR"] },
  { id:"d189", cipher:"Caesar", difficulty:"Medium", points:200,
    keyInfo:"Shift: 12",
    plaintext:"BEWARE OF THE TROJAN HORSE",
    ciphertext:"NQIMDQ AR FTQ FDAVMZ TADEQ",
    hints:["Caesar cipher", "Shift: 12", "A → M"] },
  { id:"d190", cipher:"Caesar", difficulty:"Medium", points:200,
    keyInfo:"Shift: 14",
    plaintext:"THE MAP IS NOT THE TERRITORY",
    ciphertext:"HVS AOD WG BCH HVS HSFFWHCFM",
    hints:["Caesar cipher", "Shift: 14", "A → O"] },
  { id:"d191", cipher:"Caesar", difficulty:"Medium", points:200,
    keyInfo:"Shift: 16",
    plaintext:"ALL THAT GLITTERS IS NOT GOLD",
    ciphertext:"QBB JXQJ WBYJJUHI YI DEJ WEBT",
    hints:["Caesar cipher", "Shift: 16", "A → Q"] },
  { id:"d192", cipher:"Caesar", difficulty:"Medium", points:200,
    keyInfo:"Shift: 18",
    plaintext:"THE PROOF IS IN THE DECRYPTION",
    ciphertext:"LZW HJGGX AK AF LZW VWUJQHLAGF",
    hints:["Caesar cipher", "Shift: 18", "A → S"] },
  { id:"d193", cipher:"ROT13", difficulty:"Easy", points:100,
    keyInfo:"Shift: 13 (self-inverse)",
    plaintext:"ENCRYPT AND SEND NOW",
    ciphertext:"RAPELCG NAQ FRAQ ABJ",
    hints:["ROT13: shift by exactly 13", "Applying ROT13 twice returns original", "A→N, B→O, C→P ..."] },
  { id:"d194", cipher:"ROT13", difficulty:"Easy", points:100,
    keyInfo:"Shift: 13 (self-inverse)",
    plaintext:"LOCK ALL THE CHANNELS",
    ciphertext:"YBPX NYY GUR PUNAARYF",
    hints:["ROT13: shift by exactly 13", "Applying ROT13 twice returns original", "A→N, B→O, C→P ..."] },
  { id:"d195", cipher:"ROT13", difficulty:"Easy", points:100,
    keyInfo:"Shift: 13 (self-inverse)",
    plaintext:"DEPLOY THE CIPHER NOW",
    ciphertext:"QRCYBL GUR PVCURE ABJ",
    hints:["ROT13: shift by exactly 13", "Applying ROT13 twice returns original", "A→N, B→O, C→P ..."] },
  { id:"d196", cipher:"ROT13", difficulty:"Easy", points:100,
    keyInfo:"Shift: 13 (self-inverse)",
    plaintext:"TRANSMIT ON FREQUENCY X",
    ciphertext:"GENAFZVG BA SERDHRAPL K",
    hints:["ROT13: shift by exactly 13", "Applying ROT13 twice returns original", "A→N, B→O, C→P ..."] },
  { id:"d197", cipher:"ROT13", difficulty:"Easy", points:100,
    keyInfo:"Shift: 13 (self-inverse)",
    plaintext:"CONFIRM AUTHENTICATION NOW",
    ciphertext:"PBASVEZ NHGURAGVPNGVBA ABJ",
    hints:["ROT13: shift by exactly 13", "Applying ROT13 twice returns original", "A→N, B→O, C→P ..."] },
  { id:"d198", cipher:"ROT13", difficulty:"Easy", points:100,
    keyInfo:"Shift: 13 (self-inverse)",
    plaintext:"ROTATE THE KEY AT MIDNIGHT",
    ciphertext:"EBGNGR GUR XRL NG ZVQAVTUG",
    hints:["ROT13: shift by exactly 13", "Applying ROT13 twice returns original", "A→N, B→O, C→P ..."] },
  { id:"d199", cipher:"ROT13", difficulty:"Easy", points:100,
    keyInfo:"Shift: 13 (self-inverse)",
    plaintext:"INITIALIZE SECURE CHANNEL",
    ciphertext:"VAVGVNYVMR FRPHER PUNAARY",
    hints:["ROT13: shift by exactly 13", "Applying ROT13 twice returns original", "A→N, B→O, C→P ..."] },
  { id:"d200", cipher:"ROT13", difficulty:"Easy", points:100,
    keyInfo:"Shift: 13 (self-inverse)",
    plaintext:"THE HANDSHAKE IS COMPLETE",
    ciphertext:"GUR UNAQFUNXR VF PBZCYRGR",
    hints:["ROT13: shift by exactly 13", "Applying ROT13 twice returns original", "A→N, B→O, C→P ..."] },
]