// ─── Battle Puzzle Bank — 250 puzzles ──────────────────────────────────────
// lib/puzzles-battle.ts

export interface BattlePuzzle {
  cipher: string; plaintext: string; ciphertext: string; hint: string
}

export const BATTLE_PUZZLES: BattlePuzzle[] = [
  { cipher:"Caesar", plaintext:"HELLO WORLD", ciphertext:"IFMMP XPSME", hint:"Shift 1" },
  { cipher:"Caesar", plaintext:"ATTACK NOW", ciphertext:"CVVCEM PQY", hint:"Shift 2" },
  { cipher:"Caesar", plaintext:"SEND BACKUP", ciphertext:"VHQG EDFNXS", hint:"Shift 3" },
  { cipher:"Caesar", plaintext:"HOLD THE LINE", ciphertext:"LSPH XLI PMRI", hint:"Shift 4" },
  { cipher:"Caesar", plaintext:"BREAK FREE", ciphertext:"GWJFP KWJJ", hint:"Shift 5" },
  { cipher:"Caesar", plaintext:"FIRE AT WILL", ciphertext:"LOXK GZ CORR", hint:"Shift 6" },
  { cipher:"Caesar", plaintext:"OPEN THE GATE", ciphertext:"VWLU AOL NHAL", hint:"Shift 7" },
  { cipher:"Caesar", plaintext:"FIND THE KEY", ciphertext:"NQVL BPM SMG", hint:"Shift 8" },
  { cipher:"Caesar", plaintext:"DECODE THIS", ciphertext:"MNLXMN CQRB", hint:"Shift 9" },
  { cipher:"Caesar", plaintext:"SECRET CODE", ciphertext:"COMBOD MYNO", hint:"Shift 10" },
  { cipher:"Caesar", plaintext:"MOVE OUT NOW", ciphertext:"XZGP ZFE YZH", hint:"Shift 11" },
  { cipher:"Caesar", plaintext:"RALLY HERE", ciphertext:"DMXXK TQDQ", hint:"Shift 12" },
  { cipher:"Caesar", plaintext:"STORM THE BASE", ciphertext:"FGBEZ GUR ONFR", hint:"Shift 13" },
  { cipher:"Caesar", plaintext:"ENTER THE VAULT", ciphertext:"SBHSF HVS JOIZH", hint:"Shift 14" },
  { cipher:"Caesar", plaintext:"TIME IS UP", ciphertext:"IXBT XH JE", hint:"Shift 15" },
  { cipher:"Caesar", plaintext:"SIGNAL CLEAR", ciphertext:"IYWDQB SBUQH", hint:"Shift 16" },
  { cipher:"Caesar", plaintext:"ABORT MISSION", ciphertext:"RSFIK DZJJZFE", hint:"Shift 17" },
  { cipher:"Caesar", plaintext:"MARK THE TARGET", ciphertext:"ESJC LZW LSJYWL", hint:"Shift 18" },
  { cipher:"Caesar", plaintext:"RETURN TO BASE", ciphertext:"KXMNKG MH UTLX", hint:"Shift 19" },
  { cipher:"Caesar", plaintext:"GO DARK NOW", ciphertext:"AI XULE HIQ", hint:"Shift 20" },
  { cipher:"Caesar", plaintext:"THE CODE FALLS", ciphertext:"OCZ XJYZ AVGGN", hint:"Shift 21" },
  { cipher:"Caesar", plaintext:"CIPHER BROKEN", ciphertext:"YELDAN XNKGAJ", hint:"Shift 22" },
  { cipher:"Caesar", plaintext:"KEY REVEALED", ciphertext:"HBV OBSBXIBA", hint:"Shift 23" },
  { cipher:"Caesar", plaintext:"LOCK AND LOAD", ciphertext:"JMAI YLB JMYB", hint:"Shift 24" },
  { cipher:"Caesar", plaintext:"EYES OPEN", ciphertext:"DXDR NODM", hint:"Shift 25" },
  { cipher:"Caesar", plaintext:"STAND DOWN NOW", ciphertext:"TUBOE EPXO OPX", hint:"Shift 1" },
  { cipher:"Caesar", plaintext:"ADVANCE QUICKLY", ciphertext:"CFXCPEG SWKEMNA", hint:"Shift 2" },
  { cipher:"Caesar", plaintext:"COVER ME NOW", ciphertext:"FRYHU PH QRZ", hint:"Shift 3" },
  { cipher:"Caesar", plaintext:"SILENT APPROACH", ciphertext:"WMPIRX ETTVSEGL", hint:"Shift 4" },
  { cipher:"Caesar", plaintext:"BREACH NOW", ciphertext:"GWJFHM STB", hint:"Shift 5" },
  { cipher:"Caesar", plaintext:"FLANK THEM NOW", ciphertext:"LRGTQ ZNKS TUC", hint:"Shift 6" },
  { cipher:"Caesar", plaintext:"HOLD YOUR FIRE", ciphertext:"OVSK FVBY MPYL", hint:"Shift 7" },
  { cipher:"Caesar", plaintext:"SECURE THE ZONE", ciphertext:"AMKCZM BPM HWVM", hint:"Shift 8" },
  { cipher:"Caesar", plaintext:"EXTRACT ASSET", ciphertext:"NGCAJLC JBBNC", hint:"Shift 9" },
  { cipher:"Caesar", plaintext:"MOVE FAST", ciphertext:"WYFO PKCD", hint:"Shift 10" },
  { cipher:"Caesar", plaintext:"NIGHT VISION ON", ciphertext:"YTRSE GTDTZY ZY", hint:"Shift 11" },
  { cipher:"Caesar", plaintext:"RADIO SILENCE", ciphertext:"DMPUA EUXQZOQ", hint:"Shift 12" },
  { cipher:"Caesar", plaintext:"WATCH YOUR SIX", ciphertext:"JNGPU LBHE FVK", hint:"Shift 13" },
  { cipher:"Caesar", plaintext:"FRIENDLIES AHEAD", ciphertext:"TFWSBRZWSG OVSOR", hint:"Shift 14" },
  { cipher:"Caesar", plaintext:"ENEMY SPOTTED", ciphertext:"TCTBN HEDIITS", hint:"Shift 15" },
  { cipher:"Caesar", plaintext:"PACKAGE SECURED", ciphertext:"FQSAQWU IUSKHUT", hint:"Shift 16" },
  { cipher:"Caesar", plaintext:"RENDEZVOUS SET", ciphertext:"IVEUVQMFLJ JVK", hint:"Shift 17" },
  { cipher:"Caesar", plaintext:"INTEL CONFIRMED", ciphertext:"AFLWD UGFXAJEWV", hint:"Shift 18" },
  { cipher:"Caesar", plaintext:"TARGET ACQUIRED", ciphertext:"MTKZXM TVJNBKXW", hint:"Shift 19" },
  { cipher:"Caesar", plaintext:"MISSION GO", ciphertext:"GCMMCIH AI", hint:"Shift 20" },
  { cipher:"Caesar", plaintext:"CODE RED NOW", ciphertext:"XJYZ MZY IJR", hint:"Shift 21" },
  { cipher:"Caesar", plaintext:"FULL LOCKDOWN", ciphertext:"BQHH HKYGZKSJ", hint:"Shift 22" },
  { cipher:"Caesar", plaintext:"INITIATE SEQUENCE", ciphertext:"FKFQFXQB PBNRBKZB", hint:"Shift 23" },
  { cipher:"Caesar", plaintext:"ENGAGE TARGETS", ciphertext:"CLEYEC RYPECRQ", hint:"Shift 24" },
  { cipher:"Caesar", plaintext:"DISENGAGE NOW", ciphertext:"CHRDMFZFD MNV", hint:"Shift 25" },
  { cipher:"ROT13", plaintext:"HELLO", ciphertext:"URYYB", hint:"ROT13" },
  { cipher:"ROT13", plaintext:"WORLD", ciphertext:"JBEYQ", hint:"ROT13" },
  { cipher:"ROT13", plaintext:"CIPHER", ciphertext:"PVCURE", hint:"ROT13" },
  { cipher:"ROT13", plaintext:"SECRET", ciphertext:"FRPERG", hint:"ROT13" },
  { cipher:"ROT13", plaintext:"DECODE", ciphertext:"QRPBQR", hint:"ROT13" },
  { cipher:"ROT13", plaintext:"ATTACK", ciphertext:"NGGNPX", hint:"ROT13" },
  { cipher:"ROT13", plaintext:"DEFEND", ciphertext:"QRSRAQ", hint:"ROT13" },
  { cipher:"ROT13", plaintext:"SIGNAL", ciphertext:"FVTANY", hint:"ROT13" },
  { cipher:"ROT13", plaintext:"BEACON", ciphertext:"ORNPBA", hint:"ROT13" },
  { cipher:"ROT13", plaintext:"SHADOW", ciphertext:"FUNQBJ", hint:"ROT13" },
  { cipher:"ROT13", plaintext:"FALCON", ciphertext:"SNYPBA", hint:"ROT13" },
  { cipher:"ROT13", plaintext:"VECTOR", ciphertext:"IRPGBE", hint:"ROT13" },
  { cipher:"ROT13", plaintext:"MATRIX", ciphertext:"ZNGEVK", hint:"ROT13" },
  { cipher:"ROT13", plaintext:"PYTHON", ciphertext:"CLGUBA", hint:"ROT13" },
  { cipher:"ROT13", plaintext:"BINARY", ciphertext:"OVANEL", hint:"ROT13" },
  { cipher:"ROT13", plaintext:"ROCKET", ciphertext:"EBPXRG", hint:"ROT13" },
  { cipher:"ROT13", plaintext:"PLANET", ciphertext:"CYNARG", hint:"ROT13" },
  { cipher:"ROT13", plaintext:"SYSTEM", ciphertext:"FLFGRZ", hint:"ROT13" },
  { cipher:"ROT13", plaintext:"NETWORK", ciphertext:"ARGJBEX", hint:"ROT13" },
  { cipher:"ROT13", plaintext:"KERNEL", ciphertext:"XREARY", hint:"ROT13" },
  { cipher:"ROT13", plaintext:"SERVER", ciphertext:"FREIRE", hint:"ROT13" },
  { cipher:"ROT13", plaintext:"CLIENT", ciphertext:"PYVRAG", hint:"ROT13" },
  { cipher:"ROT13", plaintext:"BRIDGE", ciphertext:"OEVQTR", hint:"ROT13" },
  { cipher:"ROT13", plaintext:"TUNNEL", ciphertext:"GHAARY", hint:"ROT13" },
  { cipher:"ROT13", plaintext:"CIPHER TEXT", ciphertext:"PVCURE GRKG", hint:"ROT13" },
  { cipher:"ROT13", plaintext:"SECRET CODE", ciphertext:"FRPERG PBQR", hint:"ROT13" },
  { cipher:"ROT13", plaintext:"BREAK THE CODE", ciphertext:"OERNX GUR PBQR", hint:"ROT13" },
  { cipher:"ROT13", plaintext:"FIND THE KEY", ciphertext:"SVAQ GUR XRL", hint:"ROT13" },
  { cipher:"ROT13", plaintext:"OPEN THE DOOR", ciphertext:"BCRA GUR QBBE", hint:"ROT13" },
  { cipher:"ROT13", plaintext:"NIGHT WATCH", ciphertext:"AVTUG JNGPU", hint:"ROT13" },
  { cipher:"ROT13", plaintext:"FIRE AT WILL", ciphertext:"SVER NG JVYY", hint:"ROT13" },
  { cipher:"ROT13", plaintext:"SEND BACKUP", ciphertext:"FRAQ ONPXHC", hint:"ROT13" },
  { cipher:"ROT13", plaintext:"STORM THE GATE", ciphertext:"FGBEZ GUR TNGR", hint:"ROT13" },
  { cipher:"ROT13", plaintext:"HOLD GROUND", ciphertext:"UBYQ TEBHAQ", hint:"ROT13" },
  { cipher:"ROT13", plaintext:"ADVANCE TROOPS", ciphertext:"NQINAPR GEBBCF", hint:"ROT13" },
  { cipher:"ROT13", plaintext:"RETREAT NOW", ciphertext:"ERGERNG ABJ", hint:"ROT13" },
  { cipher:"ROT13", plaintext:"FLANK RIGHT", ciphertext:"SYNAX EVTUG", hint:"ROT13" },
  { cipher:"ROT13", plaintext:"COVER LEFT", ciphertext:"PBIRE YRSG", hint:"ROT13" },
  { cipher:"ROT13", plaintext:"EYES OPEN", ciphertext:"RLRF BCRA", hint:"ROT13" },
  { cipher:"ROT13", plaintext:"STAND BY", ciphertext:"FGNAQ OL", hint:"ROT13" },
  { cipher:"Atbash", plaintext:"HELLO", ciphertext:"SVOOL", hint:"Reverse A↔Z" },
  { cipher:"Atbash", plaintext:"WORLD", ciphertext:"DLIOW", hint:"Reverse A↔Z" },
  { cipher:"Atbash", plaintext:"CIPHER", ciphertext:"XRKSVI", hint:"Reverse A↔Z" },
  { cipher:"Atbash", plaintext:"SECRET", ciphertext:"HVXIVG", hint:"Reverse A↔Z" },
  { cipher:"Atbash", plaintext:"ATTACK", ciphertext:"ZGGZXP", hint:"Reverse A↔Z" },
  { cipher:"Atbash", plaintext:"DEFEND", ciphertext:"WVUVMW", hint:"Reverse A↔Z" },
  { cipher:"Atbash", plaintext:"SIGNAL", ciphertext:"HRTMZO", hint:"Reverse A↔Z" },
  { cipher:"Atbash", plaintext:"BEACON", ciphertext:"YVZXLM", hint:"Reverse A↔Z" },
  { cipher:"Atbash", plaintext:"SHADOW", ciphertext:"HSZWLD", hint:"Reverse A↔Z" },
  { cipher:"Atbash", plaintext:"FALCON", ciphertext:"UZOXLM", hint:"Reverse A↔Z" },
  { cipher:"Atbash", plaintext:"VECTOR", ciphertext:"EVXGLI", hint:"Reverse A↔Z" },
  { cipher:"Atbash", plaintext:"MATRIX", ciphertext:"NZGIRC", hint:"Reverse A↔Z" },
  { cipher:"Atbash", plaintext:"PYTHON", ciphertext:"KBGSLM", hint:"Reverse A↔Z" },
  { cipher:"Atbash", plaintext:"LAMBDA", ciphertext:"OZNYWZ", hint:"Reverse A↔Z" },
  { cipher:"Atbash", plaintext:"ROCKET", ciphertext:"ILXPVG", hint:"Reverse A↔Z" },
  { cipher:"Atbash", plaintext:"PLANET", ciphertext:"KOZMVG", hint:"Reverse A↔Z" },
  { cipher:"Atbash", plaintext:"ENIGMA", ciphertext:"VMRTNZ", hint:"Reverse A↔Z" },
  { cipher:"Atbash", plaintext:"CRYPTO", ciphertext:"XIBKGL", hint:"Reverse A↔Z" },
  { cipher:"Atbash", plaintext:"BINARY", ciphertext:"YRMZIB", hint:"Reverse A↔Z" },
  { cipher:"Atbash", plaintext:"SYSTEM", ciphertext:"HBHGVN", hint:"Reverse A↔Z" },
  { cipher:"Atbash", plaintext:"UNLOCK", ciphertext:"FMOLXP", hint:"Reverse A↔Z" },
  { cipher:"Atbash", plaintext:"ENCODE", ciphertext:"VMXLWV", hint:"Reverse A↔Z" },
  { cipher:"Atbash", plaintext:"DECODE", ciphertext:"WVXLWV", hint:"Reverse A↔Z" },
  { cipher:"Atbash", plaintext:"BREAKER", ciphertext:"YIVZPVI", hint:"Reverse A↔Z" },
  { cipher:"Atbash", plaintext:"KEYHOLE", ciphertext:"PVBSLOV", hint:"Reverse A↔Z" },
  { cipher:"Atbash", plaintext:"CODEWORD", ciphertext:"XLWVDLIW", hint:"Reverse A↔Z" },
  { cipher:"Atbash", plaintext:"FIREWALL", ciphertext:"URIVDZOO", hint:"Reverse A↔Z" },
  { cipher:"Atbash", plaintext:"DARKZONE", ciphertext:"WZIPALMV", hint:"Reverse A↔Z" },
  { cipher:"Atbash", plaintext:"REDSHIFT", ciphertext:"IVWHSRUG", hint:"Reverse A↔Z" },
  { cipher:"Atbash", plaintext:"BLUEBIRD", ciphertext:"YOFVYRIW", hint:"Reverse A↔Z" },
  { cipher:"Atbash", plaintext:"GHOST NET", ciphertext:"TSLHG MVG", hint:"Reverse A↔Z" },
  { cipher:"Atbash", plaintext:"IRON MASK", ciphertext:"RILM NZHP", hint:"Reverse A↔Z" },
  { cipher:"Atbash", plaintext:"COLD WAVE", ciphertext:"XLOW DZEV", hint:"Reverse A↔Z" },
  { cipher:"Atbash", plaintext:"DARK STAR", ciphertext:"WZIP HGZI", hint:"Reverse A↔Z" },
  { cipher:"Atbash", plaintext:"BLUE FLAG", ciphertext:"YOFV UOZT", hint:"Reverse A↔Z" },
  { cipher:"Atbash", plaintext:"RED ALERT", ciphertext:"IVW ZOVIG", hint:"Reverse A↔Z" },
  { cipher:"Atbash", plaintext:"CODE ZERO", ciphertext:"XLWV AVIL", hint:"Reverse A↔Z" },
  { cipher:"Atbash", plaintext:"LOCK DOWN", ciphertext:"OLXP WLDM", hint:"Reverse A↔Z" },
  { cipher:"Atbash", plaintext:"OPEN FIRE", ciphertext:"LKVM URIV", hint:"Reverse A↔Z" },
  { cipher:"Atbash", plaintext:"STAND OFF", ciphertext:"HGZMW LUU", hint:"Reverse A↔Z" },
  { cipher:"Vigenère", plaintext:"ATTACK AT DAWN", ciphertext:"KXRKGI KX BKAL", hint:"Key: KEY" },
  { cipher:"Vigenère", plaintext:"SEND HELP NOW", ciphertext:"UEGF HXNP GQW", hint:"Key: CAT" },
  { cipher:"Vigenère", plaintext:"HOLD THE LINE", ciphertext:"KCRG HNH ZOQS", hint:"Key: DOG" },
  { cipher:"Vigenère", plaintext:"BREACH THE WALL", ciphertext:"TLRSWU LBR OUYD", hint:"Key: SUN" },
  { cipher:"Vigenère", plaintext:"SECURE THE BASE", ciphertext:"SGGUTI TJI BCWE", hint:"Key: ACE" },
  { cipher:"Vigenère", plaintext:"EXTRACT THE KEY", ciphertext:"MZXZCGB VLM MIG", hint:"Key: ICE" },
  { cipher:"Vigenère", plaintext:"SIGNAL THE TEAM", ciphertext:"GIQBAV HHO HEKA", hint:"Key: OAK" },
  { cipher:"Vigenère", plaintext:"ABORT THE RUN", ciphertext:"FJUWB ZMM XZV", hint:"Key: FIG" },
  { cipher:"Vigenère", plaintext:"GO TO GROUND", ciphertext:"HO MP GKPUGE", hint:"Key: BAT" },
  { cipher:"Vigenère", plaintext:"THE HUNT BEGINS", ciphertext:"SHT GUCS BTFICR", hint:"Key: ZAP" },
  { cipher:"Vigenère", plaintext:"OPEN THE VAULT", ciphertext:"APTZ TWQ VPGLI", hint:"Key: MAP" },
  { cipher:"Vigenère", plaintext:"FIND THE TARGET", ciphertext:"SMGQ XAR XTEKXG", hint:"Key: NET" },
  { cipher:"Vigenère", plaintext:"CODE IS BROKEN", ciphertext:"QFES ZT PIPYVO", hint:"Key: ORB" },
  { cipher:"Vigenère", plaintext:"RALLY THE SQUAD", ciphertext:"AAJUY RQE QZUYM", hint:"Key: JAY" },
  { cipher:"Vigenère", plaintext:"MOVE IN SILENCE", ciphertext:"PSIH MA VMYHRPH", hint:"Key: DEN" },
  { cipher:"Vigenère", plaintext:"LIGHTS ARE OUT", ciphertext:"LZIHKU AIG OLV", hint:"Key: ARC" },
  { cipher:"Vigenère", plaintext:"FIRE ON SIGNAL", ciphertext:"YIFX OB LIUGAZ", hint:"Key: TAO" },
  { cipher:"Vigenère", plaintext:"STORM THE GATES", ciphertext:"TXSSQ XII KBXIT", hint:"Key: BEE" },
  { cipher:"Vigenère", plaintext:"WATCH THE CLOCK", ciphertext:"SEUYL UDI DHSDG", hint:"Key: WEB" },
  { cipher:"Vigenère", plaintext:"TIME TO STRIKE", ciphertext:"GQFR BH FBKVSX", hint:"Key: NIT" },
  { cipher:"Vigenère", plaintext:"THE PATH IS CLEAR", ciphertext:"SLR OEGG MF BPRZV", hint:"Key: ZEN" },
  { cipher:"Vigenère", plaintext:"SHADOWS IN MOTION", ciphertext:"JFEUMAJ GR DMXZMR", hint:"Key: RYE" },
  { cipher:"Vigenère", plaintext:"KEEP YOUR COVER", ciphertext:"SZCX TMCM AWQCZ", hint:"Key: IVY" },
  { cipher:"Vigenère", plaintext:"RADIO IS DOWN", ciphertext:"VLPMZ UW OAAY", hint:"Key: ELM" },
  { cipher:"Vigenère", plaintext:"THE NET IS CLOSING", ciphertext:"HHX BEM WS VZOLWNZ", hint:"Key: OAT" },
  { cipher:"Vigenère", plaintext:"BURN THE EVIDENCE", ciphertext:"BJVN ILE TZISINRI", hint:"Key: APE" },
  { cipher:"Vigenère", plaintext:"MARK THE LOCATION", ciphertext:"SNLQ GBK YIINNOBH", hint:"Key: GNU" },
  { cipher:"Vigenère", plaintext:"FLEE THE SCENE", ciphertext:"HZHG HKG GFGBH", hint:"Key: COD" },
  { cipher:"Vigenère", plaintext:"COVER THE RETREAT", ciphertext:"FWHHZ FKM DHBDHIF", hint:"Key: DIM" },
  { cipher:"Vigenère", plaintext:"THE MISSION ENDS", ciphertext:"YVK RWYXWUS STIG", hint:"Key: FOG" },
  { cipher:"Vigenère", plaintext:"LAUNCH THE ATTACK", ciphertext:"SOJUQW AVT HHIHQZ", hint:"Key: HOP" },
  { cipher:"Vigenère", plaintext:"HOLD YOUR BREATH", ciphertext:"QCJM MMDF ZASYCV", hint:"Key: JOY" },
  { cipher:"Vigenère", plaintext:"THE KEY IS HIDDEN", ciphertext:"DPX UMR SA ASLWOV", hint:"Key: KIT" },
  { cipher:"Vigenère", plaintext:"DECODE THE MESSAGE", ciphertext:"OSIZRK EVK XSYDOMP", hint:"Key: LOG" },
  { cipher:"Vigenère", plaintext:"CRACK THE CIPHER", ciphertext:"OLDOE WTY FUJKQL", hint:"Key: MUD" },
  { cipher:"Vigenère", plaintext:"FIND THE ANSWER", ciphertext:"SCAQ NUR UAFQRE", hint:"Key: NUN" },
  { cipher:"Vigenère", plaintext:"THE VAULT IS EMPTY", ciphertext:"HWX JPNZI BG TFDIR", hint:"Key: OPT" },
  { cipher:"Vigenère", plaintext:"TRUST NO MACHINE", ciphertext:"IVAHX TD QGRLOCI", hint:"Key: PEG" },
  { cipher:"Vigenère", plaintext:"THE CODE HAS CHANGED", ciphertext:"JBE SIDU BAI WHQHGUX", hint:"Key: QUA" },
  { cipher:"Vigenère", plaintext:"NEW ORDERS RECEIVED", ciphertext:"EEJ FRQVRF IEPVIIVD", hint:"Key: RAN" },
  { cipher:"Vigenère", plaintext:"NIGHT OPS BEGIN", ciphertext:"FIVZT DHS QWGXF", hint:"Key: SAP" },
  { cipher:"Vigenère", plaintext:"DAYBREAK APPROACHES", ciphertext:"WUZULFTE BIJSHUDAYT", hint:"Key: TUB" },
  { cipher:"Vigenère", plaintext:"THE ENEMY RETREATS", ciphertext:"NYR YERGP EYKEYRGM", hint:"Key: URN" },
  { cipher:"Vigenère", plaintext:"VICTORY IS OURS", ciphertext:"QIVOOKT IL JUKN", hint:"Key: VAT" },
  { cipher:"Vigenère", plaintext:"STAND DOWN TROOPS", ciphertext:"OTXJD AKWK PRLKPP", hint:"Key: WAX" },
  { cipher:"Vigenère", plaintext:"SECURE ALL POSTS", ciphertext:"QEOSRQ YLX NOERS", hint:"Key: YAM" },
  { cipher:"Vigenère", plaintext:"RETURN TO COMMAND", ciphertext:"QMMTZG SW VNUFZVW", hint:"Key: ZIT" },
  { cipher:"Vigenère", plaintext:"DEBRIEF AT DAWN", ciphertext:"DFZRJCF BR DBUN", hint:"Key: ABY" },
  { cipher:"Vigenère", plaintext:"OPERATION COMPLETE", ciphertext:"ORXRCMIQG CQFPNXTG", hint:"Key: ACT" },
  { cipher:"Vigenère", plaintext:"MISSION ACCOMPLISHED", ciphertext:"MLGSLCN DQCRAPOWSKSD", hint:"Key: ADO" },
  { cipher:"Vigenère", plaintext:"THE PACKAGE IS SAFE", ciphertext:"TPH PIFKIJE QV SIIE", hint:"Key: AID" },
  { cipher:"Vigenère", plaintext:"ALL CLEAR SIGNAL", ciphertext:"ATX CTQAZ EIOZAT", hint:"Key: AIM" },
  { cipher:"Vigenère", plaintext:"THE BRIDGE IS TAKEN", ciphertext:"TPV BZZDOV IA KASVN", hint:"Key: AIR" },
  { cipher:"Vigenère", plaintext:"REINFORCE THE FLANK", ciphertext:"RMBNNHRKX TPX FTTNS", hint:"Key: AIT" },
  { cipher:"Vigenère", plaintext:"ENEMY AT THE GATES", ciphertext:"EXEMI AT DHE QATOS", hint:"Key: AKA" },
  { cipher:"Vigenère", plaintext:"WE HOLD THIS LINE", ciphertext:"WP HOWD TSIS WINP", hint:"Key: ALA" },
  { cipher:"Vigenère", plaintext:"THE CIPHER IS BROKEN", ciphertext:"TSF CTQHPS ID CRZLEY", hint:"Key: ALB" },
  { cipher:"Vigenère", plaintext:"ENCRYPT ALL TRAFFIC", ciphertext:"EYGRJTT LPL EVAQJIN", hint:"Key: ALE" },
  { cipher:"Vigenère", plaintext:"CHANGE THE FREQUENCY", ciphertext:"CSTNRX TSX FCXQFXNNR", hint:"Key: ALT" },
  { cipher:"Vigenère", plaintext:"NEW CODE ISSUED", ciphertext:"NQE CALE UASGMD", hint:"Key: AMI" },
  { cipher:"Rail Fence", plaintext:"HELLOWORLD", ciphertext:"HLOOLELWRD", hint:"2 rails" },
  { cipher:"Rail Fence", plaintext:"ATTACKATDAWN", ciphertext:"ATCADWTAKTAN", hint:"2 rails" },
  { cipher:"Rail Fence", plaintext:"SENDBACKUP", ciphertext:"SNBCUEDAKP", hint:"2 rails" },
  { cipher:"Rail Fence", plaintext:"HOLDTHELINE", ciphertext:"HLTEIEODHLN", hint:"2 rails" },
  { cipher:"Rail Fence", plaintext:"BREAKTHECODE", ciphertext:"BEKHCDRATEOE", hint:"2 rails" },
  { cipher:"Rail Fence", plaintext:"FINDTHEKEY", ciphertext:"FNTEEIDHKY", hint:"2 rails" },
  { cipher:"Rail Fence", plaintext:"DECRYPTTHIS", ciphertext:"DCYTHSERPTI", hint:"2 rails" },
  { cipher:"Rail Fence", plaintext:"MISSIONGO", ciphertext:"MSINOISOG", hint:"2 rails" },
  { cipher:"Rail Fence", plaintext:"NIGHTWATCH", ciphertext:"NGTACIHWTH", hint:"2 rails" },
  { cipher:"Rail Fence", plaintext:"CODEISRED", ciphertext:"CDIRDOESE", hint:"2 rails" },
  { cipher:"Rail Fence", plaintext:"WEAREDISCOVERED", ciphertext:"WECRERDSOEEAIVD", hint:"3 rails" },
  { cipher:"Rail Fence", plaintext:"DEFENDTHEFORT", ciphertext:"DNETEEDHFRFTO", hint:"3 rails" },
  { cipher:"Rail Fence", plaintext:"SENDTHESIGNAL", ciphertext:"STILEDHSGANEN", hint:"3 rails" },
  { cipher:"Rail Fence", plaintext:"MEETATMIDNIGHT", ciphertext:"MADHETTINGTEMI", hint:"3 rails" },
  { cipher:"Rail Fence", plaintext:"THECODEISBROKEN", ciphertext:"TOSKHCDIBOEEERN", hint:"3 rails" },
  { cipher:"Rail Fence", plaintext:"SILENCEANDSHADOW", ciphertext:"SNNAIECADHDWLESO", hint:"3 rails" },
  { cipher:"Rail Fence", plaintext:"ESCAPETHETUNNEL", ciphertext:"EPENSAEHTNECTUL", hint:"3 rails" },
  { cipher:"Rail Fence", plaintext:"RENDEZVOUSATDAWN", ciphertext:"REUDEDZOSTANNVAW", hint:"3 rails" },
  { cipher:"Rail Fence", plaintext:"BURNAFTERREADING", ciphertext:"BARDUNFERAIGRTEN", hint:"3 rails" },
  { cipher:"Rail Fence", plaintext:"THEVAULTISOPEN", ciphertext:"TAIEHVUTSPNELO", hint:"3 rails" },
  { cipher:"Rail Fence", plaintext:"OPERATIONNIGHTFALL", ciphertext:"OANHLPRTONGTALEIIF", hint:"3 rails" },
  { cipher:"Rail Fence", plaintext:"DESTROYALLEVIDENCE", ciphertext:"DRLICETOALVDNESYEE", hint:"3 rails" },
  { cipher:"Rail Fence", plaintext:"FOLLOWTHEWHITERABBIT", ciphertext:"FOETBOLWHWIEABTLTHRI", hint:"3 rails" },
  { cipher:"Rail Fence", plaintext:"SECURETHEDOCUMENTS", ciphertext:"SREUTEUEHDCMNSCTOE", hint:"3 rails" },
  { cipher:"Rail Fence", plaintext:"ADVANCEATMIDNIGHT", ciphertext:"ANTNTDACAMDIHVEIG", hint:"3 rails" },
  { cipher:"Rail Fence", plaintext:"RETREATTOBASE", ciphertext:"REOEERATBSTTA", hint:"3 rails" },
  { cipher:"Rail Fence", plaintext:"EXTRACTTHEASSET", ciphertext:"EAHSXRCTESETTAT", hint:"3 rails" },
  { cipher:"Rail Fence", plaintext:"CONFIRMRENDEZVOUS", ciphertext:"CIEZSOFRRNEVUNMDO", hint:"3 rails" },
  { cipher:"Rail Fence", plaintext:"PROCEEDWITHCAUTION", ciphertext:"PEIAORCEWTCUINODHT", hint:"3 rails" },
  { cipher:"Rail Fence", plaintext:"THEKEYISBELOW", ciphertext:"TEBWHKYSEOEIL", hint:"3 rails" },
  { cipher:"Monoalphabetic", plaintext:"HELLO WORLD", ciphertext:"ITSSG VGKSR", hint:"Q=A, W=B, E=C..." },
  { cipher:"Monoalphabetic", plaintext:"CRYPTO CODE", ciphertext:"EKNHZG EGRT", hint:"Q=A, W=B, E=C..." },
  { cipher:"Monoalphabetic", plaintext:"SECRET KEY", ciphertext:"LTEKTZ ATN", hint:"Q=A, W=B, E=C..." },
  { cipher:"Monoalphabetic", plaintext:"OPEN LOCK", ciphertext:"GHTF SGEA", hint:"Q=A, W=B, E=C..." },
  { cipher:"Monoalphabetic", plaintext:"FIND EXIT", ciphertext:"YOFR TBOZ", hint:"Q=A, W=B, E=C..." },
  { cipher:"Monoalphabetic", plaintext:"BREAK FREE", ciphertext:"WKTQA YKTT", hint:"Q=A, W=B, E=C..." },
  { cipher:"Monoalphabetic", plaintext:"DARK FORCE", ciphertext:"RQKA YGKET", hint:"Q=A, W=B, E=C..." },
  { cipher:"Monoalphabetic", plaintext:"LIGHT BEAM", ciphertext:"SOUIZ WTQD", hint:"Q=A, W=B, E=C..." },
  { cipher:"Monoalphabetic", plaintext:"FAST TRACK", ciphertext:"YQLZ ZKQEA", hint:"Q=A, W=B, E=C..." },
  { cipher:"Monoalphabetic", plaintext:"CODE ZERO", ciphertext:"EGRT MTKG", hint:"Q=A, W=B, E=C..." },
  { cipher:"Monoalphabetic", plaintext:"THE CIPHER", ciphertext:"ZIT EOHITK", hint:"Q=A, W=B, E=C..." },
  { cipher:"Monoalphabetic", plaintext:"KEY MASTER", ciphertext:"ATN DQLZTK", hint:"Q=A, W=B, E=C..." },
  { cipher:"Monoalphabetic", plaintext:"DARK NIGHT", ciphertext:"RQKA FOUIZ", hint:"Q=A, W=B, E=C..." },
  { cipher:"Monoalphabetic", plaintext:"FIRE STORM", ciphertext:"YOKT LZGKD", hint:"Q=A, W=B, E=C..." },
  { cipher:"Monoalphabetic", plaintext:"COLD FRONT", ciphertext:"EGSR YKGFZ", hint:"Q=A, W=B, E=C..." },
  { cipher:"Monoalphabetic", plaintext:"BLUE ALERT", ciphertext:"WSXT QSTKZ", hint:"Q=A, W=B, E=C..." },
  { cipher:"Monoalphabetic", plaintext:"RED SIGNAL", ciphertext:"KTR LOUFQS", hint:"Q=A, W=B, E=C..." },
  { cipher:"Monoalphabetic", plaintext:"NIGHT HAWK", ciphertext:"FOUIZ IQVA", hint:"Q=A, W=B, E=C..." },
  { cipher:"Monoalphabetic", plaintext:"STORM BIRD", ciphertext:"LZGKD WOKR", hint:"Q=A, W=B, E=C..." },
  { cipher:"Monoalphabetic", plaintext:"IRON GATE", ciphertext:"OKGF UQZT", hint:"Q=A, W=B, E=C..." },
  { cipher:"Monoalphabetic", plaintext:"SHADOW MOVE", ciphertext:"LIQRGV DGCT", hint:"Q=A, W=B, E=C..." },
  { cipher:"Monoalphabetic", plaintext:"GHOST LINE", ciphertext:"UIGLZ SOFT", hint:"Q=A, W=B, E=C..." },
  { cipher:"Monoalphabetic", plaintext:"WAVE RIDER", ciphertext:"VQCT KORTK", hint:"Q=A, W=B, E=C..." },
  { cipher:"Monoalphabetic", plaintext:"STAR FIELD", ciphertext:"LZQK YOTSR", hint:"Q=A, W=B, E=C..." },
  { cipher:"Monoalphabetic", plaintext:"DARK ZONE", ciphertext:"RQKA MGFT", hint:"Q=A, W=B, E=C..." },
  { cipher:"Monoalphabetic", plaintext:"FIRE EAGLE", ciphertext:"YOKT TQUST", hint:"Q=A, W=B, E=C..." },
  { cipher:"Monoalphabetic", plaintext:"COLD STEEL", ciphertext:"EGSR LZTTS", hint:"Q=A, W=B, E=C..." },
  { cipher:"Monoalphabetic", plaintext:"BLUE FLAME", ciphertext:"WSXT YSQDT", hint:"Q=A, W=B, E=C..." },
  { cipher:"Monoalphabetic", plaintext:"RED ARROW", ciphertext:"KTR QKKGV", hint:"Q=A, W=B, E=C..." },
  { cipher:"Monoalphabetic", plaintext:"NIGHT RAID", ciphertext:"FOUIZ KQOR", hint:"Q=A, W=B, E=C..." },
]